INSERT INTO kairo.questions (id, subject, topic, subtopic, learning_objective, concepts_tested, prerequisite_concepts, difficulty_rating, cognitive_level, estimated_solving_time_sec, reading_load, calculation_load, distractors, skills_assessed, source, year, exam_body, related_question_ids, stem, options, correct_option, explanation, lifecycle_state, empirical_stats) VALUES
('use_of_english_0300', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "An ''audition'' is a tryout for a role, unrelated to the ending of a play.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "''Criticism'' is commentary about the play, not the opposite of its ending.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "A ''climax'' is the peak of tension, close to but not the same as the final resolution -- and not its opposite.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

The dramatist provided a satisfactory

denouement

to the play?', '[{"label": "A", "text": "audition", "isCorrect": false}, {"label": "B", "text": "criticism", "isCorrect": false}, {"label": "C", "text": "introduction", "isCorrect": true}, {"label": "D", "text": "climax", "isCorrect": false}]'::jsonb, 'C', '''Denouement'' means the final resolution/ending of a play; its opposite is ''introduction'' (the beginning).', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0301', 'Use of English', 'Consonants', 'Consonant Sounds', NULL, '[{"weight": 1, "conceptId": "3p5hul"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Father'' has the voiced /ð/ sound, not voiceless /θ/.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''They'' has the voiced /ð/ sound.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "''That'' also has the voiced /ð/ sound.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that has the same consonant sound as the one represented by the letters underlined.

Heal

th

y?', '[{"label": "A", "text": "father", "isCorrect": false}, {"label": "B", "text": "path", "isCorrect": true}, {"label": "C", "text": "they", "isCorrect": false}, {"label": "D", "text": "that", "isCorrect": false}]'::jsonb, 'B', 'The ''th'' in ''healthy'' is the voiceless /θ/ sound (as in ''thin''). ''Path'' also has voiceless /θ/, while ''father'', ''they'', and ''that'' all have the voiced /ð/.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0302', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "B", "explanation": "''Imperative'' means urgent or commanding, an unrelated quality.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "''Subjective'' is essentially a synonym of opinionated (biased by personal views), not its opposite.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Discursive'' means rambling or wide-ranging in discussion, not the opposite of being opinionated.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

Manu is hard to convince because he is an

opinionated

person?', '[{"label": "A", "text": "an objective", "isCorrect": true}, {"label": "B", "text": "an imperative", "isCorrect": false}, {"label": "C", "text": "a subjective", "isCorrect": false}, {"label": "D", "text": "a discursive", "isCorrect": false}]'::jsonb, 'A', '''Opinionated'' means stubbornly attached to one''s own views; its opposite is ''objective'' (open-minded, unbiased).', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0303', 'Use of English', 'Stress', 'Word Stress', NULL, '[{"weight": 1, "conceptId": "stfgmb"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Downgrading'' as a continuous verb form is naturally stressed on ''grad'' (down-GRAD-ing), a different pattern.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "''Prescribing'' is stressed on its second syllable (pre-SCRIB-ing), not the first.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "''Internal'' is stressed on its second syllable (in-TER-nal), not the first.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that has the same stress pattern as the given word.

downtrodden?', '[{"label": "A", "text": "downgrading", "isCorrect": false}, {"label": "B", "text": "prescribing", "isCorrect": false}, {"label": "C", "text": "functional", "isCorrect": true}, {"label": "D", "text": "internal", "isCorrect": false}]'::jsonb, 'C', '''Downtrodden'' is stressed on its first syllable (DOWN-trod-den), a strong-weak-weak pattern. ''Functional'' (FUNC-tion-al) shares this exact pattern.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0304', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Vivid'' means vibrant or bright, an unrelated quality.", "misconceptionId": "misunderstood_terminology"}, {"option": "B", "explanation": "''Cruel'' is a different negative quality, not the opposite of invidious.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Difficult'' is close in feeling to invidious (a hard task) rather than its opposite.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

The officer was given an

invidious

task?', '[{"label": "A", "text": "vivid", "isCorrect": false}, {"label": "B", "text": "cruel", "isCorrect": false}, {"label": "C", "text": "pleasant", "isCorrect": true}, {"label": "D", "text": "difficult", "isCorrect": false}]'::jsonb, 'C', '''Invidious'' describes something unpleasant or likely to cause resentment; its opposite is ''pleasant''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0305', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'medium', 'none', '[{"option": "B", "explanation": "Being ''represented by a counsel'' is itself a form of appearing by proxy, not its opposite.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Not appear at all'' is a different scenario entirely, not the direct opposite of appearing via a representative.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "Answering by phone is still a form of remote (proxy-like) participation, not its opposite.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option

opposite in meaning

to the underlined word or phrase.

The judge did not grant the request that the witness should

appear by proxy

.', '[{"label": "A", "text": "be present in person", "isCorrect": true}, {"label": "B", "text": "be represented by a counsel", "isCorrect": false}, {"label": "C", "text": "not appear at all", "isCorrect": false}, {"label": "D", "text": "answer questions by phone", "isCorrect": false}]'::jsonb, 'A', 'To ''appear by proxy'' means to be represented by someone else rather than attending in person; its opposite is ''be present in person''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0306', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Attractive'' describes appearance, not energy level.", "misconceptionId": "misunderstood_terminology"}, {"option": "B", "explanation": "''Howling'' describes a specific sound the dog makes, not general liveliness.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Barking'' is also just a specific sound, not a synonym for being lively.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the

option nearest in meaning

to the word or phrase underlined.

Obi''s dog is old but still

lively', '[{"label": "A", "text": "attractive", "isCorrect": false}, {"label": "B", "text": "howling", "isCorrect": false}, {"label": "C", "text": "barking", "isCorrect": false}, {"label": "D", "text": "frisky", "isCorrect": true}]'::jsonb, 'D', '''Lively'' means full of energy; ''frisky'' (playfully energetic) is the nearest match, fitting an old dog that is still active.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0307', 'Use of English', 'Stress', 'Word Stress', NULL, '[{"weight": 1, "conceptId": "stfgmb"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Reform'' is stressed on its second syllable (re-FORM).", "misconceptionId": "overgeneralized_rule"}, {"option": "B", "explanation": "''Intact'' is stressed on its second syllable (in-TACT).", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "''Obscure'' is stressed on its second syllable (ob-SCURE).", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that has the same stress pattern as the given word.

Refuse (noun)', '[{"label": "A", "text": "reform", "isCorrect": false}, {"label": "B", "text": "intact", "isCorrect": false}, {"label": "C", "text": "obscure", "isCorrect": false}, {"label": "D", "text": "phantom", "isCorrect": true}]'::jsonb, 'D', '''Refuse'' as a noun is stressed on the first syllable (REF-use). ''Phantom'' (PHAN-tom) shares this first-syllable stress pattern.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0308', 'Use of English', 'Idiomatic expressions', 'Figures of Speech', NULL, '[{"weight": 1, "conceptId": "lwt4xp"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "This is the opposite meaning -- ''made a pile'' means gained money, not lost it.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Broke even'' means neither gained nor lost money, a different outcome from ''making a pile''.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "''Cut corners'' means to take shortcuts, an unrelated idiom about method rather than profit.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option nearest in meaning to the underlined word(s).

We

made a pie

in the business deal.', '[{"label": "A", "text": "lost a lot of money", "isCorrect": false}, {"label": "B", "text": "earned alot of money", "isCorrect": true}, {"label": "C", "text": "broke even", "isCorrect": false}, {"label": "D", "text": "cut corners", "isCorrect": false}]'::jsonb, 'B', '''Made a pile'' (rendered ''pie'' in the source) is an idiom meaning to earn a large sum of money.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0309', 'Use of English', 'Grammatical usage', 'Gerunds after Prepositions', NULL, '[{"weight": 1, "conceptId": "e1a7oj"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Sell'' is a bare infinitive, but ''with a view to'' requires a gerund, not a bare infinitive.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "''Have sold'' is a perfect infinitive form, which doesn''t fit after the fixed phrase ''with a view to''.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Be selling'' is not the required gerund form after ''to'' in this fixed phrase.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

The man is refurbishing the flat with a view to ......it?', '[{"label": "A", "text": "sell", "isCorrect": false}, {"label": "B", "text": "selling", "isCorrect": true}, {"label": "C", "text": "have sold", "isCorrect": false}, {"label": "D", "text": "be selling", "isCorrect": false}]'::jsonb, 'B', '''With a view to'' is a fixed phrase always followed by a gerund (''-ing'' form), not a bare infinitive: ''with a view to selling it''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0310', 'Use of English', 'Vocabulary', 'Contextual Word Pairs', NULL, '[{"weight": 1, "conceptId": "nvgfyg"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Understanding'' doesn''t capture the specific respect/submission that African custom expects toward elders.", "misconceptionId": "overgeneralized_rule"}, {"option": "B", "explanation": "''Indifference'' (not caring) contradicts the idea of showing something positive to elders.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "''Satisfaction'' is unrelated to the respectful attitude expected toward elders.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

It is African for a younger person to show ...... to elders?', '[{"label": "A", "text": "understanding", "isCorrect": false}, {"label": "B", "text": "indifference", "isCorrect": false}, {"label": "C", "text": "deference", "isCorrect": true}, {"label": "D", "text": "satisfaction", "isCorrect": false}]'::jsonb, 'C', '''Deference'' means respectful submission to someone''s wishes or authority, exactly what a younger person is expected to show elders.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0311', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Instability'' refers to lack of stability generally, not specifically material lack.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Difficulty'' is too generic and doesn''t specifically mean material deprivation.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "''The slums'' describes a place associated with poverty, not the word''s actual meaning.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the

option nearest in meaning

to the word or phrase underlined.

Many people used to live in

poverty

.', '[{"label": "A", "text": "instability", "isCorrect": false}, {"label": "B", "text": "want", "isCorrect": true}, {"label": "C", "text": "difficulty", "isCorrect": false}, {"label": "D", "text": "the slums", "isCorrect": false}]'::jsonb, 'B', '''Poverty'' means lack of basic necessities; ''want'' is the classic literary synonym for this state of need.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0312', 'Use of English', 'Vocabulary and expressions in context', 'Sentence Interpretation (Idiom)', NULL, '[{"weight": 1, "conceptId": "fno6b9"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "This only restates the beginning, ignoring what the sentence says about the ending.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "This wrongly projects into the future (''will not end''), while the sentence describes something that already happened.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "Hedging with ''almost'' softens the sentence''s direct claim that the crisis simply ended suddenly.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Select the option that best explains the information conveyed in the sentence.

The crisis ended as suddenly as it began?', '[{"label": "A", "text": "The crisis had suddenly begun", "isCorrect": false}, {"label": "B", "text": "The crisis will not end suddenly", "isCorrect": false}, {"label": "C", "text": "The crisis stopped almost immediately", "isCorrect": false}, {"label": "D", "text": "The crisis stopped immediately", "isCorrect": true}]'::jsonb, 'D', '''Ended as suddenly as it began'' emphasizes the crisis stopped abruptly and without warning; ''stopped immediately'' captures this directly.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0313', 'Use of English', 'Grammatical usage', 'Conditionals', NULL, '[{"weight": 1, "conceptId": "fbl55l"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Wrong tense entirely -- the sentence describes a past hypothetical, not a present/future one.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "This wrongly concludes the rain did NOT fall, the opposite of what the third conditional implies.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "This also wrongly concludes the rain didn''t fall and that the match wasn''t missed, both opposite to reality.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Select the option that best explains the information conveyed in the sentence.

If the rain hadn''t fallen, we wouldn''t have missed the match?', '[{"label": "A", "text": "The rain is falling, so we will miss the match", "isCorrect": false}, {"label": "B", "text": "The rain fell, so we didn''t watch the match", "isCorrect": true}, {"label": "C", "text": "The rain didn''t fall, so we didn''t watch the match", "isCorrect": false}, {"label": "D", "text": "The rain didn''t fall, so we didn''t miss the match", "isCorrect": false}]'::jsonb, 'B', 'The third conditional (''if...hadn''t...wouldn''t have'') describes contrary-to-fact past events: the rain actually DID fall, and we actually DID miss the match.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0314', 'Use of English', 'Idiomatic expressions', 'Sentence Interpretation (Idiom)', NULL, '[{"weight": 1, "conceptId": "91ez3x"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "B", "explanation": "''Compose themselves'' means to calm down, not to cooperate as a team.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "Nothing in ''pull together'' suggests mass resignation -- the opposite, in fact.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Pull together'' describes teamwork, not an improvement in conditions.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Select the option that best explains the information conveyed in the sentence.

The new Headmaster hoped that his men would pull together?', '[{"label": "A", "text": "He expected that the men would cooperate with him", "isCorrect": true}, {"label": "B", "text": "He thought that the men would compose themselves at work", "isCorrect": false}, {"label": "C", "text": "He was certain that they would resign en masse", "isCorrect": false}, {"label": "D", "text": "He was certain that their condition would improve under him", "isCorrect": false}]'::jsonb, 'A', '''Pull together'' is an idiom meaning to cooperate as a team, which is what the headmaster hoped for from his staff.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0315', 'Use of English', 'Vocabulary', 'Spelling', NULL, '[{"weight": 1, "conceptId": "k8pk3y"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Missing the double ''p'' and misspells the ending as ''temus''.", "misconceptionId": "memorized_not_understood"}, {"option": "B", "explanation": "Has an extra ''p'' in the wrong place and misspells the ending.", "misconceptionId": "memorized_not_understood"}, {"option": "C", "explanation": "Missing the double ''p'' after ''hip''.", "misconceptionId": "memorized_not_understood"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

A nursery rhyme is used to teach pupils how to spell the word ...... ?', '[{"label": "A", "text": "hipoppotemus", "isCorrect": false}, {"label": "B", "text": "hippoppotemus", "isCorrect": false}, {"label": "C", "text": "hipoppotamus", "isCorrect": false}, {"label": "D", "text": "hippopotamus", "isCorrect": true}]'::jsonb, 'D', '''Hippopotamus'' is the correct spelling -- double ''p'' after ''hip'', then ''popotamus''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0316', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Respectability'' is about social standing, not being answerable for actions.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "''Courage'' is an unrelated virtue.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "''Diligence'' means careful effort, a different quality from being answerable for one''s conduct.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the

option nearest in meaning

to the word or phrase underlined.

Accountability

is certainly a desirable quality in a politician.', '[{"label": "A", "text": "respectability", "isCorrect": false}, {"label": "B", "text": "courage", "isCorrect": false}, {"label": "C", "text": "responsibility", "isCorrect": true}, {"label": "D", "text": "diligence", "isCorrect": false}]'::jsonb, 'C', '''Accountability'' means being answerable for one''s actions; ''responsibility'' is its nearest match.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0317', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Weak and interesting'' is close to the opposite of vehement''s forcefulness.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Troublesome and noisy'' describes disruptive behaviour, not forceful conviction specifically.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "''Clever and helpful'' are unrelated positive traits.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the

option nearest in meaning

to the word or phrase underlined.

The manager described Mfon as a man of

vehement character.', '[{"label": "A", "text": "weak and interesting", "isCorrect": false}, {"label": "B", "text": "strong and insistent", "isCorrect": true}, {"label": "C", "text": "troublesome and noisy", "isCorrect": false}, {"label": "D", "text": "clever and helpful", "isCorrect": false}]'::jsonb, 'B', '''Vehement'' describes forceful, intensely expressed conviction; ''strong and insistent'' captures this precisely.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0318', 'Use of English', 'Grammatical usage', 'Tense', NULL, '[{"weight": 1, "conceptId": "hbp4zb"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Was leaving'' (past continuous) suggests an action in progress, not one completed before another past event.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "''Has left'' (present perfect) doesn''t fit a narrative told entirely in the past.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "''Would leave'' expresses a future-in-the-past intention, not a completed prior action.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

The train ...... before I arrived?', '[{"label": "A", "text": "was leaving", "isCorrect": false}, {"label": "B", "text": "has left", "isCorrect": false}, {"label": "C", "text": "had left", "isCorrect": true}, {"label": "D", "text": "would leave", "isCorrect": false}]'::jsonb, 'C', 'The train''s departure happened before another past event (the speaker''s arrival), which requires the past perfect: ''had left''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0319', 'Use of English', 'Vowels', 'Vowel Sounds', NULL, '[{"weight": 1, "conceptId": "namskj"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Gourd'' has a different vowel sound (/ʊə/ or /ɔː/), not /ɑː/.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "''Guide'' has the diphthong /aɪ/, a different sound.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "''Chat'' has the short /æ/ sound, not the long /ɑː/ in ''guard''.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that has the same vowel sound as the one represented by the letter(s) underlined.

Gu

ar

d?', '[{"label": "A", "text": "gourd", "isCorrect": false}, {"label": "B", "text": "guide", "isCorrect": false}, {"label": "C", "text": "argue", "isCorrect": true}, {"label": "D", "text": "chat", "isCorrect": false}]'::jsonb, 'C', 'The ''ar'' in ''guard'' is pronounced /ɑː/. ''Argue'' also has this /ɑː/ sound in its first syllable.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0320', 'Use of English', 'Idiomatic expressions', 'Sentence Interpretation (Idiom)', NULL, '[{"weight": 1, "conceptId": "91ez3x"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Parrying means evading, the opposite of answering brilliantly.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Parrying is a skilful deflection, not a failure to answer.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "Parrying avoids direct engagement, so it doesn''t mean mastering the questions.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Select the option that best explains the information conveyed in the sentence.

The Governor parried all the questions put to him by the journalist?', '[{"label": "A", "text": "The governor answered all the questions  brilliantly", "isCorrect": false}, {"label": "B", "text": "The Governor evaded all the questions", "isCorrect": true}, {"label": "C", "text": "The Governor failed all the questions", "isCorrect": false}, {"label": "D", "text": "The  Governor mastered all the questions", "isCorrect": false}]'::jsonb, 'B', 'To ''parry'' a question means to skilfully evade or deflect it, so the Governor evaded all the questions.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0321', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Ordinary and uninteresting'' is a synonym of workaday, not its opposite.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "''Comfortable'' isn''t the dimension workaday addresses; this shifts the meaning rather than reversing it.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Ugly and unfascinating'' intensifies workaday''s meaning rather than opposing it.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

The views of the plateau are in stark contrast to the

workaday

cottages below.', '[{"label": "A", "text": "ordinary and uninteresting", "isCorrect": false}, {"label": "B", "text": "beautiful and interesting", "isCorrect": true}, {"label": "C", "text": "comfortable and fascinating", "isCorrect": false}, {"label": "D", "text": "ugly and unfascinating", "isCorrect": false}]'::jsonb, 'B', '''Workaday'' means ordinary and unremarkable; its opposite is ''beautiful and interesting''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0322', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Contempt'' is a direct synonym of scorn, not its opposite.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "''Anger'' is a different negative emotion, not the opposite of scorn.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Pity'' is close to sympathy but carries a different, slightly condescending connotation -- sympathy is the more precise opposite.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

The principal was filled with

scorn

when we gave our reason for coming late.', '[{"label": "A", "text": "contempt", "isCorrect": false}, {"label": "B", "text": "sympathy", "isCorrect": true}, {"label": "C", "text": "anger", "isCorrect": false}, {"label": "D", "text": "pity", "isCorrect": false}]'::jsonb, 'B', '''Scorn'' means contempt or disdain; its opposite is ''sympathy''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0323', 'Use of English', 'Stress', 'Emphatic Stress', NULL, '[{"weight": 1, "conceptId": "odd0o9"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Queries the subject (''who''), not the emphasized ability.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "Changes the subject to ''father'' instead of keeping ''mother''.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "Too open-ended (''what can...do''), rather than confirming the specific ability to cook.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'The word in capital letters has the emphatic stress. Choose the option to which the given sentence relates.

Your mother CAN cook the meal.', '[{"label": "A", "text": "Who will cook the meal?", "isCorrect": false}, {"label": "B", "text": "Can my father cook the meal?", "isCorrect": false}, {"label": "C", "text": "Isn''t my mother able to cook the meal?", "isCorrect": true}, {"label": "D", "text": "What can my mother do?", "isCorrect": false}]'::jsonb, 'C', 'The stress on CAN highlights ability, so the matching question confirms that ability while keeping the subject ''mother'' unchanged: ''Isn''t my mother able to cook the meal?''', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0324', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Wonderful'' has a positive connotation opposite to the negative weight ''fateful'' usually carries.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Uncontrollable'' describes a lack of control, not the significance of consequences.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "''Unsuccessful'' is narrower than the broad, momentous sense of ''fateful''.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the

option nearest in meaning

to the word or phrase underlined.

That

fateful

decision changed the company''s outlook in many ways.', '[{"label": "A", "text": "wonderful", "isCorrect": false}, {"label": "B", "text": "disastrous", "isCorrect": true}, {"label": "C", "text": "uncontrollable", "isCorrect": false}, {"label": "D", "text": "unsuccessful", "isCorrect": false}]'::jsonb, 'B', '''Fateful'' describes a decision with momentous, often disastrous, consequences; ''disastrous'' is the nearest match here.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb);