-- 78 HIGH-confidence Chemistry/Physics/Biology matches from
-- scripts/generate-planner-topic-map-candidates.js, human-reviewed before
-- insert. Mathematics/Use of English intentionally excluded (see
-- 20260830102441_create_kairo_planner_topic_map.sql's own comment) —
-- Physics' "Vapours" and Biology's "Soil" are also intentionally
-- excluded: real kairo.questions topics with no matching Blueprint topic
-- (not even a close runner-up in the candidate scoring), left for manual
-- authoring post-launch rather than guessed at.
insert into kairo.planner_topic_map (subject_slug, topic_title, engine_subject, engine_topics, confidence) values
('chemistry', 'Separation of Mixtures & Purification', 'Chemistry', ARRAY['Separation of mixtures and purification of chemical substances']::text[], 'reviewed'),
('chemistry', 'Chemical Combination', 'Chemistry', ARRAY['Chemical combination']::text[], 'reviewed'),
('chemistry', 'Kinetic Theory & Gas Laws', 'Chemistry', ARRAY['Kinetic theory of matter and Gas Laws']::text[], 'reviewed'),
('chemistry', 'Atomic Structure & Bonding', 'Chemistry', ARRAY['Atomic structure and bonding']::text[], 'reviewed'),
('chemistry', 'Air', 'Chemistry', ARRAY['Air']::text[], 'reviewed'),
('chemistry', 'Water', 'Chemistry', ARRAY['Water']::text[], 'reviewed'),
('chemistry', 'Solubility', 'Chemistry', ARRAY['Solubility']::text[], 'reviewed'),
('chemistry', 'Environmental Pollution', 'Chemistry', ARRAY['Environmental Pollution']::text[], 'reviewed'),
('chemistry', 'Acids, Bases & Salts', 'Chemistry', ARRAY['Acids, bases and salts']::text[], 'reviewed'),
('chemistry', 'Oxidation & Reduction', 'Chemistry', ARRAY['Oxidation and reduction']::text[], 'reviewed'),
('chemistry', 'Electrolysis', 'Chemistry', ARRAY['Electrolysis']::text[], 'reviewed'),
('chemistry', 'Energy Changes', 'Chemistry', ARRAY['Energy changes']::text[], 'reviewed'),
('chemistry', 'Rates of Chemical Reaction', 'Chemistry', ARRAY['Rates of Chemical Reaction']::text[], 'reviewed'),
('chemistry', 'Chemical Equilibrium', 'Chemistry', ARRAY['Chemical equilibria']::text[], 'reviewed'),
('chemistry', 'Non-metals & Their Compounds', 'Chemistry', ARRAY['Non-metals and their compounds']::text[], 'reviewed'),
('chemistry', 'Metals & Their Compounds', 'Chemistry', ARRAY['Metals and their compounds']::text[], 'reviewed'),
('chemistry', 'Organic Compounds', 'Chemistry', ARRAY['Organic Compounds']::text[], 'reviewed'),
('chemistry', 'Chemistry & Industry', 'Chemistry', ARRAY['Chemistry and Industry']::text[], 'reviewed'),
('physics', 'Measurements and Units', 'Physics', ARRAY['Measurements and Units']::text[], 'reviewed'),
('physics', 'Scalars and Vectors', 'Physics', ARRAY['Scalars and Vectors']::text[], 'reviewed'),
('physics', 'Motion', 'Physics', ARRAY['Motion']::text[], 'reviewed'),
('physics', 'Gravitational Field', 'Physics', ARRAY['Gravitational Field']::text[], 'reviewed'),
('physics', 'Equilibrium of Forces', 'Physics', ARRAY['Equilibrium of Forces']::text[], 'reviewed'),
('physics', 'Simple Machines', 'Physics', ARRAY['Simple Machines']::text[], 'reviewed'),
('physics', 'Friction', 'Physics', ARRAY['Friction']::text[], 'reviewed'),
('physics', 'Elasticity', 'Physics', ARRAY['Elasticity']::text[], 'reviewed'),
('physics', 'Work, Energy and Power', 'Physics', ARRAY['Work, Energy and Power']::text[], 'reviewed'),
('physics', 'Liquids at Rest', 'Physics', ARRAY['Liquids at Rest']::text[], 'reviewed'),
('physics', 'Pressure', 'Physics', ARRAY['Pressure']::text[], 'reviewed'),
('physics', 'Temperature and Its Measurement', 'Physics', ARRAY['Temperature and its Measurement']::text[], 'reviewed'),
('physics', 'Quantity of Heat', 'Physics', ARRAY['Quantity of Heat']::text[], 'reviewed'),
('physics', 'Change of State', 'Physics', ARRAY['Change of State']::text[], 'reviewed'),
('physics', 'Thermal Expansion', 'Physics', ARRAY['Thermal Expansion']::text[], 'reviewed'),
('physics', 'Kinetic Theory of Matter', 'Physics', ARRAY['Kinetic Theory of Matter']::text[], 'reviewed'),
('physics', 'Gas Laws', 'Physics', ARRAY['Gas Laws']::text[], 'reviewed'),
('physics', 'Propagation of Sound Waves', 'Physics', ARRAY['Propagation of Sound Waves']::text[], 'reviewed'),
('physics', 'Waves', 'Physics', ARRAY['Waves']::text[], 'reviewed'),
('physics', 'Light Energy', 'Physics', ARRAY['Light Energy']::text[], 'reviewed'),
('physics', 'Reflection of Light', 'Physics', ARRAY['Reflection of Light']::text[], 'reviewed'),
('physics', 'Refraction of Light', 'Physics', ARRAY['Refraction of Light']::text[], 'reviewed'),
('physics', 'Dispersion of Light and Colours', 'Physics', ARRAY['Dispersion of Light and Colours']::text[], 'reviewed'),
('physics', 'Optical Instruments', 'Physics', ARRAY['Optical Instruments']::text[], 'reviewed'),
('physics', 'Electrostatics', 'Physics', ARRAY['Electrostatics']::text[], 'reviewed'),
('physics', 'Current Electricity', 'Physics', ARRAY['Current Electricity']::text[], 'reviewed'),
('physics', 'Electrical Energy and Power', 'Physics', ARRAY['Electrical Energy and Power']::text[], 'reviewed'),
('physics', 'Electric Cells', 'Physics', ARRAY['Electric Cells']::text[], 'reviewed'),
('physics', 'Electrical Measuring Instruments', 'Physics', ARRAY['Electrical Measuring Instruments']::text[], 'reviewed'),
('physics', 'Capacitors', 'Physics', ARRAY['Capacitors']::text[], 'reviewed'),
('physics', 'Magnetic Field', 'Physics', ARRAY['Magnetic Field']::text[], 'reviewed'),
('physics', 'Electromagnetic Induction', 'Physics', ARRAY['Electromagnetic Induction']::text[], 'reviewed'),
('physics', 'Alternating Current', 'Physics', ARRAY['Alternating Current']::text[], 'reviewed'),
('physics', 'Semiconductors', 'Physics', ARRAY['Semiconductors']::text[], 'reviewed'),
('physics', 'Energy Quantization', 'Physics', ARRAY['Energy Quantization']::text[], 'reviewed'),
('physics', 'Elementary Modern Physics', 'Physics', ARRAY['Elementary Modern Physics']::text[], 'reviewed'),
('physics', 'Nuclear Physics', 'Physics', ARRAY['Nuclear Physics']::text[], 'reviewed'),
('physics', 'Heat Transfer', 'Physics', ARRAY['Heat Transfer']::text[], 'reviewed'),
('biology', 'Living organisms', 'Biology', ARRAY['Living organisms']::text[], 'reviewed'),
('biology', 'Structural/functional and behavioural adaptations of organisms', 'Biology', ARRAY['Structural/functional and behavioural adaptations of organisms']::text[], 'reviewed'),
('biology', 'Natural habitats', 'Biology', ARRAY['Natural habitats']::text[], 'reviewed'),
('biology', 'Local (Nigerian) biomes', 'Biology', ARRAY['Local (Nigerian) biomes']::text[], 'reviewed'),
('biology', 'The ecology of populations', 'Biology', ARRAY['The ecology of populations']::text[], 'reviewed'),
('biology', 'Factors affecting the distribution of organisms', 'Biology', ARRAY['Factors affecting the distribution of organisms']::text[], 'reviewed'),
('biology', 'Symbiotic interactions of plants and animals', 'Biology', ARRAY['Symbiotic interactions of plants and animals']::text[], 'reviewed'),
('biology', 'Internal structure of plants and animals', 'Biology', ARRAY['Internal structure of plants and animals']::text[], 'reviewed'),
('biology', 'Nutrition', 'Biology', ARRAY['Nutrition']::text[], 'reviewed'),
('biology', 'Transport', 'Biology', ARRAY['Transport']::text[], 'reviewed'),
('biology', 'Respiration', 'Biology', ARRAY['Respiration']::text[], 'reviewed'),
('biology', 'Excretion', 'Biology', ARRAY['Excretion']::text[], 'reviewed'),
('biology', 'Support and movement', 'Biology', ARRAY['Support and movement']::text[], 'reviewed'),
('biology', 'Co-ordination and control', 'Biology', ARRAY['Co-ordination and control']::text[], 'reviewed'),
('biology', 'Growth', 'Biology', ARRAY['Growth']::text[], 'reviewed'),
('biology', 'Reproduction', 'Biology', ARRAY['Reproduction']::text[], 'reviewed'),
('biology', 'Variation in population', 'Biology', ARRAY['Variation in population']::text[], 'reviewed'),
('biology', 'Heredity', 'Biology', ARRAY['Heredity']::text[], 'reviewed'),
('biology', 'Evolution among organisms', 'Biology', ARRAY['Evolution among organisms']::text[], 'reviewed'),
('biology', 'Theories of evolution', 'Biology', ARRAY['Theories of evolution']::text[], 'reviewed'),
('biology', 'Evidence of evolution', 'Biology', ARRAY['Evidence of evolution']::text[], 'reviewed'),
('biology', 'Humans and environment', 'Biology', ARRAY['Humans and environment']::text[], 'reviewed')
on conflict (subject_slug, topic_title) do update set engine_topics = excluded.engine_topics, confidence = excluded.confidence, engine_subject = excluded.engine_subject;
