INSERT INTO kairo.questions (id, subject, topic, subtopic, learning_objective, concepts_tested, prerequisite_concepts, difficulty_rating, cognitive_level, estimated_solving_time_sec, reading_load, calculation_load, distractors, skills_assessed, source, year, exam_body, related_question_ids, stem, options, correct_option, explanation, lifecycle_state, empirical_stats) VALUES
('use_of_english_0276', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "Amusing describes something as funny in a positive sense, missing the negative, immature connotation of puerile.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Empty could loosely suggest something lacking substance, but it misses the specific sense of childishness that defines puerile.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "Entertaining, like amusing, has a positive connotation that doesn''t match the mildly critical, immature sense of puerile.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option nearest in meaning to the underlined word(s).

Adigun''s jokes are always

puerile

?', '[{"label": "A", "text": "amusing", "isCorrect": false}, {"label": "B", "text": "childish", "isCorrect": true}, {"label": "C", "text": "empty", "isCorrect": false}, {"label": "D", "text": "entertaining", "isCorrect": false}]'::jsonb, 'B', '''Puerile'' means childishly silly or immature, which ''childish'' directly captures.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0277', 'Use of English', 'Idiomatic expressions', 'Sentence Interpretation (Idiom)', NULL, '[{"weight": 1, "conceptId": "91ez3x"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Temporary is not implied by meteoric; the word describes the speed and brilliance of the rise, not how long it lasted.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "This captures suddenness but misses the vivid sense of speed and brilliance that meteoric specifically conveys.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "This captures the surprise element from ''surprised everyone'' but doesn''t as precisely convey the swift, dramatic quality of a meteoric rise.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Select the option that best explain the information conveyed in the sentence.

His meteoric rise  to fame surprise everyone?', '[{"label": "A", "text": "His rise to fame was only temporary", "isCorrect": false}, {"label": "B", "text": "He rose to fame with astonishing speed", "isCorrect": true}, {"label": "C", "text": "He became successful very suddenly", "isCorrect": false}, {"label": "D", "text": "He rose to the top quite unexpectedly", "isCorrect": false}]'::jsonb, 'B', '''Meteoric rise'' evokes the image of a meteor -- something moving with spectacular speed and brilliance -- so ''he rose to fame with astonishing speed'' best captures both the rapidity and brilliance implied, beyond either suddenness or unexpectedness alone.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0278', 'Use of English', 'Grammatical usage', 'Concord (Collective Nouns)', NULL, '[{"weight": 1, "conceptId": "q64m7x"}]'::jsonb, '{}', 3, 'application', 60, 'low', 'none', '[{"option": "B", "explanation": "The word choice encomiums is correct, but ''its'' treats the audience as a single unified entity rather than individuals each clapping their own hands.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "The pronoun is correct, but invectives (insults) contradicts the description of an appreciative audience.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "This combines both errors: the wrong collective pronoun and a word meaning insults instead of praise.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

The highly appreciative audience clapped  ........ hands and showered  ......... on the lecturer?', '[{"label": "A", "text": "their / encomiums", "isCorrect": true}, {"label": "B", "text": "its / encomiums", "isCorrect": false}, {"label": "C", "text": "their / invectives", "isCorrect": false}, {"label": "D", "text": "its / invectives", "isCorrect": false}]'::jsonb, 'A', '''Audience'' as a collective noun of individuals each clapping their own hands takes ''their'', and since the audience was ''highly appreciative'', they would shower praise, i.e. ''encomiums'', not insults.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0279', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "Clever is a synonym of adroit rather than its opposite, so it fails to reverse the intended meaning.", "misconceptionId": "misunderstood_terminology"}, {"option": "B", "explanation": "Tactless relates to social sensitivity rather than skill, so while it feels negative, it isn''t the precise antonym of a word about dexterity.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Skilful is essentially a direct synonym for adroit, showing the antonym instruction was overlooked.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

Everyone admired the manager''s

adroit

handling of the crises in the company.', '[{"label": "A", "text": "clever", "isCorrect": false}, {"label": "B", "text": "tactless", "isCorrect": false}, {"label": "C", "text": "skilful", "isCorrect": false}, {"label": "D", "text": "clumsy", "isCorrect": true}]'::jsonb, 'D', '''Adroit'' means skilful and dexterous; its most precise opposite is ''clumsy'', describing a lack of skill.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0280', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 3, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "Indictment is a formal legal charge, a more official and specific process than the mutual blame-exchange implied by recrimination.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "Accusation is close but too general; it misses the retaliatory, mutual-blame quality specifically carried by recrimination.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "This wrongly assumes recrimination implies the accusation is false, when the word simply concerns retaliatory blame regardless of truth.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option nearest in meaning to the underlined word(s).

Let us not indulge in

recrimination

?', '[{"label": "A", "text": "indictment", "isCorrect": false}, {"label": "B", "text": "accusation", "isCorrect": false}, {"label": "C", "text": "counter-accusation", "isCorrect": true}, {"label": "D", "text": "unfounded allegation", "isCorrect": false}]'::jsonb, 'C', '''Recrimination'' specifically means a retaliatory or counter-accusation made in response to another''s accusation, which ''counter-accusation'' captures precisely.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0281', 'Use of English', 'Comprehension', 'Cloze/Gap-fill in Context', NULL, '[{"weight": 1, "conceptId": "hbrpoi"}]'::jsonb, '{}', 2, 'application', 60, 'high', 'none', '[{"option": "A", "explanation": "Climate refers to long-term weather patterns of a region, not a single recurring growing period within a year.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "Period is a vague generic term that could fit loosely without the precise agricultural meaning that season carries.", "misconceptionId": "guessed_no_reasoning"}, {"option": "D", "explanation": "Weather refers to short-term atmospheric conditions, not the longer, recurring timeframe relevant to crop yields.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'The passage below has gaps numbered 11 to 20. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.

It is the business of the scientist to accumulate knowledge about the universe and all that is in it and to find if he is able, common

……11…..[A. experiment B. instruments C. approaches D. factors]

which underlie and account for the facts that he knows. He chooses when he can, the method of the controlled

…….12…..[A. respondent B. experiment C. system D. data]

. If he wants to find out the effect of light on growing plants, he takes many plants, as alike as possible. Some he stands in the sun, some in the shade, some in the dark, all the time keeping all other

.....13.....[A. studies B. procedures C. objects D. conditions]

(temperature, moisture, nourishments) the same. In this way, by keeping other variables

……..14……[A. constant B. good C. dark D. natural]

and by varying the light only, the effect of light on plants can be clearly seen. This

…….15…..[A. research B. method C. tool D. rationale]

of using ‘controls’ can be applied to a variety of situations and can be used to find the answers to questions as widely different as ‘must moisture be present if

…….16….[A. an alloy B. gold C. bar D. iron]

is to rust?’ and which variety of beans give the greatest yield in one

……17…..[A. climate B. period C. season D. weather]?

In the course of his

……18…..[A. finding B. queries C. experiment D. inquiries]

, the scientist may find what he thinks is one common explanation for an increasing number of facts the explanation, if it seems consistently to fit the various facts, is called

…….19……[A. an antithesis B. a principle C. a thesis D. a hypothesis]

. If this continues to stand the test of numerous experiments and remains unshaken, it becomes a

……20…..[A. deduction B. law C. notion D. thesis].

In question number 17 above, choose the best option from letters A-D that best completes the gap.', '[{"label": "A", "text": "climate", "isCorrect": false}, {"label": "B", "text": "period", "isCorrect": false}, {"label": "C", "text": "season", "isCorrect": true}, {"label": "D", "text": "weather", "isCorrect": false}]'::jsonb, 'C', 'The passage asks which variety of beans gives the greatest yield in one ''season'', the standard term for a recurring agricultural growing period.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0282', 'Use of English', 'Comprehension', 'Comprehension and Summary', NULL, '[{"weight": 1, "conceptId": "3r5lb7"}]'::jsonb, '{}', 2, 'application', 60, 'high', 'none', '[{"option": "B", "explanation": "This misreads ''fixing'' in the sense of retaliation or settling a score, rather than its intended sense of establishing or determining.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "This mistakes ''fixing'' for repairing damage already done, rather than the passage''s actual sense of establishing meaning in advance.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "Vocabulary building is a plausible-sounding but unsupported extension; the passage is about clarity of meaning for communication, not vocabulary acquisition.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'If our thoughts is to be clear and we are to succeed in communicating it to other people, we must have some method of fixing the meaning of the words we use. When we use a word whose meaning is not certain, we may well be asked to define it. There is a usual traditional device for doing this by indicating the class to which whatever is indicated by the term belongs and also other particular property which distinguishes it from all other members of the same class. Thus we may define a whale as a ‘marine animal that spouts’. ‘Marine animals’ in this definition indicates the general class to which the whale belongs and ‘spouts’ indicates the particular property that distinguishes whales from other such marine animals as fishes, seals, jellyfish and lobsters. In the same way, we can define an even number as a finite integer divisible by two or a democracy as a system of government in which the people themselves rule.

there are other ways, of course of indicating the meaning of words. We may for example, find it hard to make a suitable definition of the word ‘animal’, as we say that an animal is such a thing as a rabbit, dog fish or goat. Similarly, we may say that religion is such a system as Christianity, Islam, Judaism and Buddhism. This way of indicating the meaning of a term by enumerating examples of what it includes is obviously of limited usefulness. If we indicate our use of the word ‘animal’ as above, our hearers might for example be doubtful whether a sea-anemone or a slug was to be included in the class of animals. It is however, a useful way of supplementing a definition if the definition itself id definite without being easily understandable. Failure of an attempt at definition to serve its purpose may result from giving as distinguishing mark one which either does not belong to all the things the definition id intended to include, or does belong to some members of the same general class which the definition is intended to exclude.

the writer uses the expression ''fixing the meaning of the words we use'' to mean', '[{"label": "A", "text": "establishing a precise and definite meaning for words to ensure clear communication", "isCorrect": true}, {"label": "B", "text": "getting even with the people who always ask for definitions", "isCorrect": false}, {"label": "C", "text": "repair the damage done by inadequate definition during communication", "isCorrect": false}, {"label": "D", "text": "using definition to help people build up their vocabulary", "isCorrect": false}]'::jsonb, 'A', 'The passage opens by stating that for our thoughts to be clear and communicable, ''we must have some method of fixing the meaning of the words we use'' -- meaning establishing a precise, definite meaning for words.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0283', 'Use of English', 'Synthesis of ideas from passages', 'Comprehension and Summary', NULL, '[{"weight": 1, "conceptId": "m80o2r"}]'::jsonb, '{}', 3, 'application', 60, 'high', 'none', '[{"option": "A", "explanation": "This captures only the traditional class-plus-property method and omits the enumeration-by-examples approach also discussed in the passage.", "misconceptionId": "overgeneralized_rule"}, {"option": "B", "explanation": "This muddles the two approaches by combining ''general property'' with ''examples'', which the passage actually treats as two distinct methods.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "This restates only half of the traditional method, the distinguishing property, without mentioning the class, and ignores the enumeration approach entirely.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'If our thoughts is to be clear and we are to succeed in communicating it to other people, we must have some method of fixing the meaning of the words we use. When we use a word whose meaning is not certain, we may well be asked to define it. There is a usual traditional device for doing this by indicating the class to which whatever is indicated by the term belongs and also other particular property which distinguishes it from all other members of the same class. Thus we may define a whale as a ‘marine animal that spouts’. ‘Marine animals’ in this definition indicates the general class to which the whale belongs and ‘spouts’ indicates the particular property that distinguishes whales from other such marine animals as fishes, seals, jellyfish and lobsters. In the same way, we can define an even number as a finite integer divisible by two or a democracy as a system of government in which the people themselves rule.

there are other ways, of course of indicating the meaning of words. We may for example, find it hard to make a suitable definition of the word ‘animal’, as we say that an animal is such a thing as a rabbit, dog fish or goat. Similarly, we may say that religion is such a system as Christianity, Islam, Judaism and Buddhism. This way of indicating the meaning of a term by enumerating examples of what it includes is obviously of limited usefulness. If we indicate our use of the word ‘animal’ as above, our hearers might for example be doubtful whether a sea-anemone or a slug was to be included in the class of animals. It is however, a useful way of supplementing a definition if the definition itself id definite without being easily understandable. Failure of an attempt at definition to serve its purpose may result from giving as distinguishing mark one which either does not belong to all the things the definition id intended to include, or does belong to some members of the same general class which the definition is intended to exclude.

One of these summarizes the approaches to definition discussed in the passage', '[{"label": "A", "text": "mentioning the class of a word or object with its specific property", "isCorrect": false}, {"label": "B", "text": "indicating the class of a word and mentioning its general property with examples", "isCorrect": false}, {"label": "C", "text": "specifying clearly what distinguishes a particular word or object from its traditional group", "isCorrect": false}, {"label": "D", "text": "defining a term either by naming its class and distinguishing property, or by listing examples of what it includes", "isCorrect": true}]'::jsonb, 'D', 'The passage describes two separate approaches to definition -- the traditional class-plus-distinguishing-property method, and the supplementary method of enumerating examples -- and only this option accurately summarizes both.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0284', 'Use of English', 'Comprehension', 'Comprehension and Summary', NULL, '[{"weight": 1, "conceptId": "3r5lb7"}]'::jsonb, '{}', 2, 'application', 60, 'high', 'none', '[{"option": "B", "explanation": "The reader''s expectations are one factor the writer considers, but the passage frames this as only part of the broader situational judgment.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "The writer makes the decision, but the passage says this decision is based on the circumstances, not on the writer as a determining factor in himself.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "Theme (subject matter) is not discussed in the passage as a factor determining style at all, making this an unsupported guess.", "misconceptionId": "guessed_no_reasoning"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Recgnizing the need for objectivity in their work, the early report writers to develop a writing style which convey this attitude. They reasoned that the source of the subjective quality in a report is the human being.  And they reasoned that objectivity is best attained by emphasizing the factual material of a report rather 5than the personalities involved. So they worked to remove the human being from their writing. Impersonal writing style was the result. By impersonal writing is meant writing in the third person-without I’s, we’s or you’s.

In recent years, impersonal writing has been strenuously questioned by many writers. These writers point out that personal writing is more forceful and direct than is impersonal writing. They contend that writing which brings both reader and writer into the picture is more like conversation and therefore more interesting. And the answer to the point on objectivity when written in personal style as when in impersonal style. Frequently, they counter with the argument that impersonal writing leads to an overuse of passive voice and a generally dull writing style. This last argument however lacks substances. Impersonal writing can and should be interesting. Any dullness it may have is wholly the fault of the writer. As proof, one has only to look at the lovely styles used by the writers for newspapers, news magazines and journals. Most of this writing is impersonal and usually it is not dull.

As in most cases of controversy, there is some merit to the arguments on both sides. There are situations in which personal writing is best. There are situations in which impersonal writing is best. And there are situations in which either style is appropriate. The writer must decide at the outset of his work which style is best for his own situation.

Her decision should be based on the circumstances of each report situation. First, he should consider the expectations or desires of those for whom he is preparing the report. More than likely he will find a preference for impersonal style for like most human beings; businessman has been slow to break tradition. Next, the writer should consider the formality of the report situation. If the situation is informal, as when the report is really a personal communication of information between business associates, personal writing is appropriate. But if the situation is formal, as is case with most reports, the conventional impersonal style is best.

From the passage, what determines the appropriateness of a style is the', '[{"label": "A", "text": "situation", "isCorrect": true}, {"label": "B", "text": "reader", "isCorrect": false}, {"label": "C", "text": "writer", "isCorrect": false}, {"label": "D", "text": "theme", "isCorrect": false}]'::jsonb, 'A', 'The passage states the writer must base his decision on ''the circumstances of each report situation'' -- weighing both audience expectations and the formality of the situation -- so the situation as a whole, not any single factor, determines appropriateness.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0285', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 3, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "Sentimental misreads adamant''s firmness as emotional attachment, and rehearsed misreads reprisal as something practiced rather than retaliatory.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "Retributive correctly matches reprisal, but ''supportive of'' wrongly softens adamant''s meaning of firm insistence into approval.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "Both words here are close to opposite meanings: adamant means unyielding, not tolerant, and reprisal means retaliatory, not a surprise attack.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option nearest in meaning to the underlined word(s).

I wish the commander were less

adamant

about his proposed

reprisal

attack on the enemy?', '[{"label": "A", "text": "sentimental about / rehearsed", "isCorrect": false}, {"label": "B", "text": "insistent on / retaliatory", "isCorrect": true}, {"label": "C", "text": "supportive of / retributive", "isCorrect": false}, {"label": "D", "text": "tolerant of / surprise", "isCorrect": false}]'::jsonb, 'B', '''Adamant about'' means firmly insistent on, and a ''reprisal attack'' is a retaliatory attack made in response to an earlier act; ''insistent on / retaliatory'' matches both meanings precisely.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0286', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "Perfect describes quality, an unrelated dimension to whether an event has happened before, so it doesn''t reverse the meaning of unprecedented.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "Momentous means highly significant, which is actually close in feel to unprecedented rather than its opposite.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "Unnecessary describes something not needed, an unrelated quality to whether the event is a first occurrence.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

The governor''s visit is

an unprecedented

event in the history of the social club', '[{"label": "A", "text": "a perfect", "isCorrect": false}, {"label": "B", "text": "a momentous", "isCorrect": false}, {"label": "C", "text": "a common", "isCorrect": true}, {"label": "D", "text": "an unnecessary", "isCorrect": false}]'::jsonb, 'C', '''Unprecedented'' means never having happened before; its opposite is ''common'', meaning ordinary or frequently occurring.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0287', 'Use of English', 'Comprehension', 'Cloze/Gap-fill in Context', NULL, '[{"weight": 1, "conceptId": "hbrpoi"}]'::jsonb, '{}', 2, 'application', 60, 'high', 'none', '[{"option": "A", "explanation": "Alloy is a plausible material-sounding word, but rusting is specifically associated with iron and iron-containing metals, not alloys generally.", "misconceptionId": "overgeneralized_rule"}, {"option": "B", "explanation": "Gold is a metal but famously does not rust, making it inconsistent with the passage''s example about the role of moisture in rusting.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Bar describes a shape, not a material, so it doesn''t fit the sentence''s need for a substance that can rust.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'The passage below has gaps numbered 11 to 20. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.

It is the business of the scientist to accumulate knowledge about the universe and all that is in it and to find if he is able, common

……11…..[A. experiment B. instruments C. approaches D. factors]

which underlie and account for the facts that he knows. He chooses when he can, the method of the controlled

…….12…..[A. respondent B. experiment C. system D. data]

. If he wants to find out the effect of light on growing plants, he takes many plants, as alike as possible. Some he stands in the sun, some in the shade, some in the dark, all the time keeping all other

.....13.....[A. studies B. procedures C. objects D. conditions]

(temperature, moisture, nourishments) the same. In this way, by keeping other variables

……..14……[A. constant B. good C. dark D. natural]

and by varying the light only, the effect of light on plants can be clearly seen. This

…….15…..[A. research B. method C. tool D. rationale]

of using ‘controls’ can be applied to a variety of situations and can be used to find the answers to questions as widely different as ‘must moisture be present if

…….16….[A. an alloy B. gold C. bar D. iron]

is to rust?’ and which variety of beans give the greatest yield in one

……17…..[A. climate B. period C. season D. weather]?

In the course of his

……18…..[A. finding B. queries C. experiment D. inquiries]

, the scientist may find what he thinks is one common explanation for an increasing number of facts the explanation, if it seems consistently to fit the various facts, is called

…….19……[A. an antithesis B. a principle C. a thesis D. a hypothesis]

. If this continues to stand the test of numerous experiments and remains unshaken, it becomes a

……20…..[A. deduction B. law C. notion D. thesis].

In question number 16 above, choose the best option from letters A-D that best completes the gap.', '[{"label": "A", "text": "an alloy", "isCorrect": false}, {"label": "B", "text": "gold", "isCorrect": false}, {"label": "C", "text": "bar", "isCorrect": false}, {"label": "D", "text": "iron", "isCorrect": true}]'::jsonb, 'D', 'The passage''s example question is ''must moisture be present if iron is to rust?'' -- rusting is a property specifically associated with iron.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0288', 'Use of English', 'Idiomatic expressions', 'Sentence Interpretation (Idiom)', NULL, '[{"weight": 1, "conceptId": "91ez3x"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Snubbed means to be deliberately ignored or slighted, which is nearly opposite to being publicly attacked and mocked.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "Criticized is a reasonable general term but is too mild to capture the public ridicule and condemnation specifically implied by pilloried.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "This describes interrogation, not the public mockery and condemnation that being pilloried specifically evokes.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Select the option that best explain the information conveyed in the sentence.

The politician was pilloried by the press for his inflammatory remarks?', '[{"label": "A", "text": "The politician was snubbed by the press for his remarks", "isCorrect": false}, {"label": "B", "text": "The politician was criticized by the press for his remarks", "isCorrect": false}, {"label": "C", "text": "The politician was closely questioned by the press for his remarks", "isCorrect": false}, {"label": "D", "text": "The politician was publicly ridiculed and condemned by the press for his remarks", "isCorrect": true}]'::jsonb, 'D', 'To be ''pilloried'' means to be publicly exposed to ridicule and harsh condemnation, historically evoking the punishment of being placed in a pillory for public mockery -- a stronger and more precise meaning than plain criticism.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0289', 'Use of English', 'Stress', 'Word Stress', NULL, '[{"weight": 1, "conceptId": "stfgmb"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "Convenient is stressed on the second syllable (con-VE-nient), so a student unfamiliar with its pronunciation might mistakenly flag it as different.", "misconceptionId": "memorized_not_understood"}, {"option": "C", "explanation": "Embarrass is stressed on the second syllable (em-BAR-rass), sharing the pattern with the other two words rather than differing from them.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "Contribute is stressed on the second syllable (con-TRIB-ute), matching the shared pattern rather than standing apart from it.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the word that has a different stress pattern from the others.', '[{"label": "A", "text": "convenient", "isCorrect": false}, {"label": "B", "text": "confident", "isCorrect": true}, {"label": "C", "text": "embarrass", "isCorrect": false}, {"label": "D", "text": "contribute", "isCorrect": false}]'::jsonb, 'B', '''Confident'' is stressed on its first syllable (CON-fi-dent), while ''convenient'', ''embarrass'', and ''contribute'' are all stressed on the second syllable.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0290', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "Resumed implies he had previously stopped and is now continuing, but assumed office describes taking up a role, not returning to interrupted work.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "This is close but too generic; it could describe any new job, missing the specific formal, official sense that assumed office carries.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "Returned wrongly implies he was there before and has come back, which is not implied by assumed office.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option nearest in meaning to the underlined word(s).

The Executive Secretary has just

assumed office

.', '[{"label": "A", "text": "resumed work", "isCorrect": false}, {"label": "B", "text": "started work", "isCorrect": false}, {"label": "C", "text": "returned", "isCorrect": false}, {"label": "D", "text": "formally taken up his official position", "isCorrect": true}]'::jsonb, 'D', '''Assumed office'' specifically means to formally take up a position of authority or duty, a more precise meaning than a generic phrase about starting or resuming work.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0291', 'Use of English', 'Vocabulary', 'Spelling', NULL, '[{"weight": 1, "conceptId": "k8pk3y"}]'::jsonb, '{}', 1, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "This is missing one of the two ''l''s, a common spelling slip made in haste with an unfamiliar loanword.", "misconceptionId": "rushed_under_pressure"}, {"option": "C", "explanation": "This transposes the ''e'' and ''u'' and also drops a letter ''l'', compounding two separate spelling errors.", "misconceptionId": "memorized_not_understood"}, {"option": "D", "explanation": "This transposes the ''e'' and ''u'' at the start, a plausible mishearing of the word''s pronunciation.", "misconceptionId": "memorized_not_understood"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

The army officer said that more ...... would be needed to prosecute the war?', '[{"label": "A", "text": "guerrilas", "isCorrect": false}, {"label": "B", "text": "guerrillas", "isCorrect": true}, {"label": "C", "text": "geurrilas", "isCorrect": false}, {"label": "D", "text": "geurrillas", "isCorrect": false}]'::jsonb, 'B', '''Guerrillas'' is the correct spelling -- with ''gue-'' (not ''geur-'') and a double ''l'' -- referring to irregular fighters, as needed to prosecute the war.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0292', 'Use of English', 'Comprehension', 'Comprehension and Summary', NULL, '[{"weight": 1, "conceptId": "3r5lb7"}]'::jsonb, '{}', 3, 'application', 60, 'high', 'none', '[{"option": "A", "explanation": "This overstates the passage''s treatment of enumeration, which is explicitly said to be ''of limited usefulness'' even when handled carefully.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "This is an unsupported generalization; the passage never claims every speaker or writer actually has such a method, only that one is needed for clarity.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "The passage contrasts a ''traditional'' method with ''other ways'', but never labels any method as specifically ''modern'', so this overreads the text.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'If our thoughts is to be clear and we are to succeed in communicating it to other people, we must have some method of fixing the meaning of the words we use. When we use a word whose meaning is not certain, we may well be asked to define it. There is a usual traditional device for doing this by indicating the class to which whatever is indicated by the term belongs and also other particular property which distinguishes it from all other members of the same class. Thus we may define a whale as a ‘marine animal that spouts’. ‘Marine animals’ in this definition indicates the general class to which the whale belongs and ‘spouts’ indicates the particular property that distinguishes whales from other such marine animals as fishes, seals, jellyfish and lobsters. In the same way, we can define an even number as a finite integer divisible by two or a democracy as a system of government in which the people themselves rule.

there are other ways, of course of indicating the meaning of words. We may for example, find it hard to make a suitable definition of the word ‘animal’, as we say that an animal is such a thing as a rabbit, dog fish or goat. Similarly, we may say that religion is such a system as Christianity, Islam, Judaism and Buddhism. This way of indicating the meaning of a term by enumerating examples of what it includes is obviously of limited usefulness. If we indicate our use of the word ‘animal’ as above, our hearers might for example be doubtful whether a sea-anemone or a slug was to be included in the class of animals. It is however, a useful way of supplementing a definition if the definition itself id definite without being easily understandable. Failure of an attempt at definition to serve its purpose may result from giving as distinguishing mark one which either does not belong to all the things the definition id intended to include, or does belong to some members of the same general class which the definition is intended to exclude.

Which of the following statements can be deduced from the passage?', '[{"label": "A", "text": "definition aid communication when enumeration is accurately handled", "isCorrect": false}, {"label": "B", "text": "effective communication requires a precise method of determining the meaning of the words used", "isCorrect": true}, {"label": "C", "text": "every speaker or writer has a method of defining words", "isCorrect": false}, {"label": "D", "text": "there are both traditional and modern methods of defining words", "isCorrect": false}]'::jsonb, 'B', 'This follows directly from the passage''s opening claim that clear thought and communication require ''some method of fixing the meaning of the words we use.''', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0293', 'Use of English', 'Grammatical usage', 'Prepositional Collocations', NULL, '[{"weight": 1, "conceptId": "cepp3x"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Inserting ''by'' wrongly treats solicit as needing a preposition before its object, similar to passive-voice agent phrases.", "misconceptionId": "overgeneralized_rule"}, {"option": "B", "explanation": "For seems plausible since one might ''ask for'' support, but solicit already means ''to ask for'' and takes a direct object without a preposition.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "Adding the article ''a'' wrongly treats ''financial support'' as a countable singular noun phrase rather than an uncountable one.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

You are free to solicit ....... support from the board?', '[{"label": "A", "text": "by financial", "isCorrect": false}, {"label": "B", "text": "for financial", "isCorrect": false}, {"label": "C", "text": "financial", "isCorrect": true}, {"label": "D", "text": "a financial", "isCorrect": false}]'::jsonb, 'C', '''Solicit'' takes a direct object without a preposition or article (''solicit financial support''), so no extra word is needed before ''financial support''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0294', 'Use of English', 'Idiomatic expressions', 'Sentence Interpretation (Idiom)', NULL, '[{"weight": 1, "conceptId": "91ez3x"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Caught suggests being apprehended in wrongdoing, unrelated to the idiom''s meaning of falling ill.", "misconceptionId": "misunderstood_terminology"}, {"option": "B", "explanation": "Robbed introduces a crime scenario that isn''t implied by the idiom taken bad, which concerns sudden illness.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "Drunk might be guessed from the vague negative tone of ''bad'', but the idiom specifically refers to sudden sickness, not intoxication.", "misconceptionId": "guessed_no_reasoning"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Select the option that best explain the information conveyed in the sentence.

Audu was taken bad in the middle of the night?', '[{"label": "A", "text": "He was caught", "isCorrect": false}, {"label": "B", "text": "He was robbed", "isCorrect": false}, {"label": "C", "text": "He suddenly became ill", "isCorrect": true}, {"label": "D", "text": "He was drunk", "isCorrect": false}]'::jsonb, 'C', '''Taken bad'' is an informal idiom meaning to suddenly fall ill or become sick.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0295', 'Use of English', 'Grammatical usage', 'Concord (Subject-Verb Agreement)', NULL, '[{"weight": 1, "conceptId": "59ii9v"}]'::jsonb, '{}', 3, 'application', 60, 'low', 'none', '[{"option": "B", "explanation": "This correctly matches the relative clause but wrongly applies the plural verb to the singular main subject quality as well.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "This correctly matches the main clause but wrongly applies the singular verb to the plural antecedent questions in the relative clause.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "This reverses the correct pattern entirely, applying the singular verb to the plural antecedent and the plural verb to the singular main subject.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

The quality of your questions which ....... always attracted attention ....... never been in doubt.', '[{"label": "A", "text": "have / has", "isCorrect": true}, {"label": "B", "text": "have / have", "isCorrect": false}, {"label": "C", "text": "has / has", "isCorrect": false}, {"label": "D", "text": "has / have", "isCorrect": false}]'::jsonb, 'A', 'The relative clause verb agrees with its antecedent ''questions'' (plural: ''which have always attracted attention''), while the main verb agrees with the singular head noun ''quality'' (''has never been in doubt'').', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0296', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 3, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "Stoic describes someone who endures hardship without complaint, a trait actually similar to phlegmatic calmness rather than its opposite.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "Irritable feels like a plausible opposite since it implies quick temper, but it is a narrower quality than the general emotional volatility that best opposes phlegmatic.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "Cold, like phlegmatic, describes an unemotional demeanor, making it a near-synonym rather than a true opposite.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

Her

phlegmatic

temperament endears her to her friends?', '[{"label": "A", "text": "stoic", "isCorrect": false}, {"label": "B", "text": "irritable", "isCorrect": false}, {"label": "C", "text": "excitable", "isCorrect": true}, {"label": "D", "text": "cold", "isCorrect": false}]'::jsonb, 'C', '''Phlegmatic'' means calm and not easily excited or provoked; its precise opposite is ''excitable'', describing someone easily aroused to strong emotion.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0297', 'Use of English', 'Grammatical usage', 'Pronoun Agreement', NULL, '[{"weight": 1, "conceptId": "3fkjw3"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Switching to ''she'' introduces a specific gender not established by the indefinite one, breaking pronoun consistency.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Traditional generic ''he'' was once common but breaks strict agreement with one, which calls for ''one'' to be repeated in formal usage.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "They introduces a plural pronoun for a singular indefinite antecedent, mismatching in number even though it is commonly used informally.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

If one perseveres ....... will surely succeed?', '[{"label": "A", "text": "she", "isCorrect": false}, {"label": "B", "text": "one", "isCorrect": true}, {"label": "C", "text": "he", "isCorrect": false}, {"label": "D", "text": "they", "isCorrect": false}]'::jsonb, 'B', 'The indefinite pronoun ''one'' should be referred back to consistently with ''one'' (rather than switching to a gendered or plural pronoun) in formal usage.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0298', 'Use of English', 'Comprehension', 'Comprehension and Summary', NULL, '[{"weight": 1, "conceptId": "3r5lb7"}]'::jsonb, '{}', 3, 'application', 60, 'high', 'none', '[{"option": "A", "explanation": "This overstates the passage''s claim, which says deregulation ''should bring some relief'', not that it will solve all problems.", "misconceptionId": "overgeneralized_rule"}, {"option": "B", "explanation": "This directly contradicts the passage, which explicitly states there is nothing to suggest the government intends to leave Nigerians at the mercy of a cartel.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "This is an unsupported absolute claim; the passage discusses price relief through competition, not a guarantee against high prices.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Those who have been following the argument for and against the deregulation of the oil industry in Nigeria may have got the impression that deregulation connotes lack of control or indifference on the part of the government. But there is nothing so far from official quarters to suggest that deregulation will cause the government to relinquish its control of the oil industry because the absence of direct control does not mean that it will surrender all its rights to the entrepreneurs who may want to participate in the industry. Yet the opposition expressed so far against stems from the fear that the government would leave Nigerians at the mercy of a heartless cartel who would command the heights of the oil industry and cause pump price of fuel to rise above the means of most Nigerians.

`As a result of such fears, many Nigerians have become resentful of deregulation and in fact the Nigeria Labour Congress  (NLC) has threatened to ‘deregulate’ the government if it should go ahead with the deregulation plan. But Nigerians have not fared any better with the economy totally in government control. Until recently, the most important sectors of the economy were in the hands of the government. Today, the deregulation of some of these sectors has broken its monopoly and introduced healthy competition to make a little easier for Nigerians. A good example is the breaking of the stifling monopoly of Nigeria Airways. Today, the traveller is king at the domestic airports as opposed to the struggle that air travels used to be under Nigeria Airways monopoly. Before, it was almost easier for a camel to pass through the eye of a needle than for travellers to board a plane.

Following from this, the apostles of deregulation rightly heap all the blame for the problems associated with petroleum products distribution in this country squarely on the government, which owns all the refineries and which sells fuel to local consumers through its agency, the Nigerian National Petroleum Corporation (NNPC). In the same way, the government argues that if the current NNPC monopoly were broken with the introduction of entrepreneurs to the refining and sale of petroleum products in the country, the Nigerian people would be all the better for it. It stands to reason that once the government continues to fix maximum prices would be all the better for it. It stands to reason that once the government continues to fix maximum prices for petroleum products in this country, the deregulation of the oil sector should bring some relief to the people by ensuring that wastage, corruption and inefficiency are reduced to the minimum. Consumers will also have the last laugh because competition will result in the availability of the products at reasonable prices. This appears to be the sense in deregulation.

Which of the following conclusions can be reached from the passage?', '[{"label": "A", "text": "the deregulation of the economy will solve all the problems of petroleum products distribution", "isCorrect": false}, {"label": "B", "text": "the government is hell-bent on leaving nigerians at the mercy of a heartless cartel", "isCorrect": false}, {"label": "C", "text": "nigerians cannot buy fuel at exorbitant prices", "isCorrect": false}, {"label": "D", "text": "deregulation of the oil sector could benefit consumers through competition and reduced inefficiency, leading to more reasonable prices", "isCorrect": true}]'::jsonb, 'D', 'The passage concludes that competition arising from deregulation ''will result in the availability of the products at reasonable prices'' and that wastage, corruption and inefficiency would be reduced -- directly supporting this conclusion.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0299', 'Use of English', 'Comprehension', 'Cloze/Gap-fill in Context', NULL, '[{"weight": 1, "conceptId": "hbrpoi"}]'::jsonb, '{}', 2, 'application', 60, 'high', 'none', '[{"option": "B", "explanation": "Good is a vague evaluative word that doesn''t capture the specific scientific meaning of holding variables unchanged.", "misconceptionId": "guessed_no_reasoning"}, {"option": "C", "explanation": "Dark echoes an earlier detail about plants kept in darkness but doesn''t fit the meaning of keeping variables unchanged.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "Natural describes an unmanipulated condition, which contradicts the deliberately controlled setup the experiment actually requires.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'The passage below has gaps numbered 11 to 20. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.

It is the business of the scientist to accumulate knowledge about the universe and all that is in it and to find if he is able, common

……11…..[A. experiment B. instruments C. approaches D. factors]

which underlie and account for the facts that he knows. He chooses when he can, the method of the controlled

…….12…..[A. respondent B. experiment C. system D. data]

. If he wants to find out the effect of light on growing plants, he takes many plants, as alike as possible. Some he stands in the sun, some in the shade, some in the dark, all the time keeping all other

.....13.....[A. studies B. procedures C. objects D. conditions]

(temperature, moisture, nourishments) the same. In this way, by keeping other variables

……..14……[A. constant B. good C. dark D. natural]

and by varying the light only, the effect of light on plants can be clearly seen. This

…….15…..[A. research B. method C. tool D. rationale]

of using ‘controls’ can be applied to a variety of situations and can be used to find the answers to questions as widely different as ‘must moisture be present if

…….16….[A. an alloy B. gold C. bar D. iron]

is to rust?’ and which variety of beans give the greatest yield in one

……17…..[A. climate B. period C. season D. weather]?

In the course of his

……18…..[A. finding B. queries C. experiment D. inquiries]

, the scientist may find what he thinks is one common explanation for an increasing number of facts the explanation, if it seems consistently to fit the various facts, is called

…….19……[A. an antithesis B. a principle C. a thesis D. a hypothesis]

. If this continues to stand the test of numerous experiments and remains unshaken, it becomes a

……20…..[A. deduction B. law C. notion D. thesis].

In question number 14 above, choose the best option from letters A-D that best completes the gap.', '[{"label": "A", "text": "constant", "isCorrect": true}, {"label": "B", "text": "good", "isCorrect": false}, {"label": "C", "text": "dark", "isCorrect": false}, {"label": "D", "text": "natural", "isCorrect": false}]'::jsonb, 'A', 'The passage states that by keeping other variables ''constant'' and varying only the light, the effect of light on plants can be clearly observed -- the core principle of a controlled experiment.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb);