insert into kairo.concepts (id, name, subject, topic, subtopic, difficulty_weight, dependency_ids, question_pool_ids) values
($q$mu9d5t$q$, $q$Empirical and Molecular Formula$q$, $q$Chemistry$q$, $q$Chemical Combination$q$, $q$Empirical and Molecular Formula$q$, 1.2, '{}', '{}'),
($q$jniec0$q$, $q$The Mole Concept — Atom Counting$q$, $q$Chemistry$q$, $q$Chemical Combination$q$, $q$The Mole Concept — Atom Counting$q$, 1.2, '{}', '{}'),
($q$bpogj3$q$, $q$Boiling Point and Purity$q$, $q$Chemistry$q$, $q$Nature of Matter$q$, $q$Boiling Point and Purity$q$, 1.2, '{}', '{}'),
($q$bqhgcv$q$, $q$Nitrogen Compounds — Brown Ring Test$q$, $q$Chemistry$q$, $q$Non-Metals & Their Compounds$q$, $q$Nitrogen Compounds — Brown Ring Test$q$, 1.2, '{}', '{}'),
($q$vk5zmy$q$, $q$Reactions of Metal Salts with Bases$q$, $q$Chemistry$q$, $q$Metals & Their Compounds$q$, $q$Reactions of Metal Salts with Bases$q$, 1.2, '{}', '{}'),
($q$ace3du$q$, $q$Alkenes — Addition Reactions$q$, $q$Chemistry$q$, $q$Organic Chemistry$q$, $q$Alkenes — Addition Reactions$q$, 1.1, '{}', '{}'),
($q$xn8nji$q$, $q$Classification of Alkanols$q$, $q$Chemistry$q$, $q$Organic Chemistry$q$, $q$Classification of Alkanols$q$, 1.1, '{}', '{}'),
($q$vfpcni$q$, $q$Alkynes — Terminal Alkyne Test$q$, $q$Chemistry$q$, $q$Organic Chemistry$q$, $q$Alkynes — Terminal Alkyne Test$q$, 1.3, '{}', '{}'),
($q$k2zkym$q$, $q$Haber Process and Uses of Hydrogen$q$, $q$Chemistry$q$, $q$Chemistry & Industry$q$, $q$Haber Process and Uses of Hydrogen$q$, 1.0, '{}', '{}'),
($q$x5x9l4$q$, $q$Polymers and Their Uses$q$, $q$Chemistry$q$, $q$Chemistry & Industry$q$, $q$Polymers and Their Uses$q$, 1.1, '{}', '{}'),
($q$bv73sr$q$, $q$Glass Manufacture$q$, $q$Chemistry$q$, $q$Chemistry & Industry$q$, $q$Glass Manufacture$q$, 1.0, '{}', '{}'),
($q$lteab6$q$, $q$Polymers and Macromolecules — Synthetic vs Natural$q$, $q$Chemistry$q$, $q$Organic Chemistry$q$, $q$Polymers and Macromolecules — Synthetic vs Natural$q$, 1.1, '{}', '{}'),
($q$mhljhv$q$, $q$Catenation$q$, $q$Chemistry$q$, $q$Nature of Matter$q$, $q$Catenation$q$, 1.0, '{}', '{}'),
($q$epcv95$q$, $q$Ionic vs Covalent Character — Fajan's Rules$q$, $q$Chemistry$q$, $q$Atomic Structure & Bonding$q$, $q$Ionic vs Covalent Character — Fajan's Rules$q$, 1.4, '{}', '{}'),
($q$h2ua90$q$, $q$The Carbon Cycle$q$, $q$Chemistry$q$, $q$Environmental Pollution$q$, $q$The Carbon Cycle$q$, 1.1, '{}', '{}'),
($q$gc697d$q$, $q$Iron Compounds and Redox Behaviour$q$, $q$Chemistry$q$, $q$Metals & Their Compounds$q$, $q$Iron Compounds and Redox Behaviour$q$, 1.2, '{}', '{}'),
($q$pns65n$q$, $q$Thermodynamics of Equilibrium$q$, $q$Chemistry$q$, $q$Chemical Equilibrium$q$, $q$Thermodynamics of Equilibrium$q$, 1.3, '{}', '{}'),
($q$y963w7$q$, $q$Oxidation Number Assignment$q$, $q$Chemistry$q$, $q$Oxidation & Reduction$q$, $q$Oxidation Number Assignment$q$, 1.2, '{}', '{}'),
($q$tqaefy$q$, $q$Electrolysis of Aqueous Solutions — Preferential Discharge$q$, $q$Chemistry$q$, $q$Electrolysis$q$, $q$Electrolysis of Aqueous Solutions — Preferential Discharge$q$, 1.3, '{}', '{}'),
($q$c4kxyo$q$, $q$Activation Energy and Catalysts$q$, $q$Chemistry$q$, $q$Rates of Reaction$q$, $q$Activation Energy and Catalysts$q$, 1.1, '{}', '{}'),
($q$ozo4oh$q$, $q$Qualitative Tests for Water$q$, $q$Chemistry$q$, $q$Non-Metals & Their Compounds$q$, $q$Qualitative Tests for Water$q$, 1.0, '{}', '{}'),
($q$qs067o$q$, $q$pH and Reactivity Toward Metals$q$, $q$Chemistry$q$, $q$Acids, Bases & Salts$q$, $q$pH and Reactivity Toward Metals$q$, 1.1, '{}', '{}'),
($q$mu3oy8$q$, $q$Solubility and Saturation$q$, $q$Chemistry$q$, $q$Solubility$q$, $q$Solubility and Saturation$q$, 1.1, '{}', '{}'),
($q$jis2pp$q$, $q$Hydrogen Bonding$q$, $q$Chemistry$q$, $q$Atomic Structure & Bonding$q$, $q$Hydrogen Bonding$q$, 1.1, '{}', '{}'),
($q$v4o1jb$q$, $q$Stoichiometric Calculations — Gas Volumes$q$, $q$Chemistry$q$, $q$Chemical Combination$q$, $q$Stoichiometric Calculations — Gas Volumes$q$, 1.2, '{}', '{}'),
($q$vvwi6v$q$, $q$Physical vs Chemical Change$q$, $q$Chemistry$q$, $q$Nature of Matter$q$, $q$Physical vs Chemical Change$q$, 1.0, '{}', '{}'),
($q$naed66$q$, $q$Percentage Composition$q$, $q$Chemistry$q$, $q$Chemical Combination$q$, $q$Percentage Composition$q$, 1.3, '{}', '{}'),
($q$ej7de5$q$, $q$Balancing Chemical Equations — Atom Counting$q$, $q$Chemistry$q$, $q$Chemical Combination$q$, $q$Balancing Chemical Equations — Atom Counting$q$, 1.2, '{}', '{}'),
($q$zxcqb1$q$, $q$Intermolecular Forces — Van der Waals$q$, $q$Chemistry$q$, $q$Atomic Structure & Bonding$q$, $q$Intermolecular Forces — Van der Waals$q$, 1.0, '{}', '{}'),
($q$yzd6cv$q$, $q$Acidic and Basic Ions — Salt Hydrolysis$q$, $q$Chemistry$q$, $q$Acids, Bases & Salts$q$, $q$Acidic and Basic Ions — Salt Hydrolysis$q$, 1.2, '{}', '{}'),
($q$gqm7dj$q$, $q$Soap and Detergents — Structure and Function$q$, $q$Chemistry$q$, $q$Chemistry & Industry$q$, $q$Soap and Detergents — Structure and Function$q$, 1.3, '{}', '{}'),
($q$zz7t6m$q$, $q$Solubility of Fats — Polarity$q$, $q$Chemistry$q$, $q$Nature of Matter$q$, $q$Solubility of Fats — Polarity$q$, 1.0, '{}', '{}'),
($q$gntpzm$q$, $q$Oil Spillage Remediation$q$, $q$Chemistry$q$, $q$Environmental Pollution$q$, $q$Oil Spillage Remediation$q$, 1.1, '{}', '{}'),
($q$ji3evn$q$, $q$Enthalpy of Formation and Hess's Law$q$, $q$Chemistry$q$, $q$Energy Changes$q$, $q$Enthalpy of Formation and Hess's Law$q$, 1.4, '{}', '{}'),
($q$yckr2s$q$, $q$Electrolytes vs Non-Electrolytes$q$, $q$Chemistry$q$, $q$Electrolysis$q$, $q$Electrolytes vs Non-Electrolytes$q$, 1.1, '{}', '{}'),
($q$w3jjz5$q$, $q$Laboratory Preparation of Chlorine$q$, $q$Chemistry$q$, $q$Non-Metals & Their Compounds$q$, $q$Laboratory Preparation of Chlorine$q$, 1.1, '{}', '{}'),
($q$aixz7h$q$, $q$Transition Metals and d-Orbitals$q$, $q$Chemistry$q$, $q$Atomic Structure & Bonding$q$, $q$Transition Metals and d-Orbitals$q$, 1.2, '{}', '{}'),
($q$q8of3z$q$, $q$Amphoteric Metals$q$, $q$Chemistry$q$, $q$Metals & Their Compounds$q$, $q$Amphoteric Metals$q$, 1.1, '{}', '{}'),
($q$izl9kl$q$, $q$Halogens — Starch-Iodide Test$q$, $q$Chemistry$q$, $q$Non-Metals & Their Compounds$q$, $q$Halogens — Starch-Iodide Test$q$, 1.0, '{}', '{}'),
($q$v5b5h3$q$, $q$Steel Manufacture$q$, $q$Chemistry$q$, $q$Chemistry & Industry$q$, $q$Steel Manufacture$q$, 1.0, '{}', '{}'),
($q$uej13e$q$, $q$Benzene and Aromatic Substitution$q$, $q$Chemistry$q$, $q$Organic Chemistry$q$, $q$Benzene and Aromatic Substitution$q$, 1.3, '{}', '{}'),
($q$wk11wx$q$, $q$Natural Macromolecules — Cellulose$q$, $q$Chemistry$q$, $q$Organic Chemistry$q$, $q$Natural Macromolecules — Cellulose$q$, 1.1, '{}', '{}'),
($q$xlxlql$q$, $q$Natural Gas Composition$q$, $q$Chemistry$q$, $q$Chemistry & Industry$q$, $q$Natural Gas Composition$q$, 1.0, '{}', '{}');
