INSERT INTO kairo.questions (id, subject, topic, subtopic, learning_objective, concepts_tested, prerequisite_concepts, difficulty_rating, cognitive_level, estimated_solving_time_sec, reading_load, calculation_load, distractors, skills_assessed, source, year, exam_body, related_question_ids, stem, options, correct_option, explanation, lifecycle_state, empirical_stats) VALUES
('use_of_english_0251', 'Use of English', 'Vocabulary', 'Collocations', NULL, '[{"weight": 1, "conceptId": "hyf9sx"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "A student might associate battery with chemistry (an acid battery) rather than its legal sense of physical attack.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "Insult seems plausible as a general term for verbal attack, but battery specifically pairs with the legal term assault, not general abuse.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "Touching is too mild and vague to match the fixed legal phrase, though a student might guess it from the idea of physical contact.", "misconceptionId": "guessed_no_reasoning"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

We did not understand what the magistrate said about ........ and battery?', '[{"label": "A", "text": "acid", "isCorrect": false}, {"label": "B", "text": "insult", "isCorrect": false}, {"label": "C", "text": "assault", "isCorrect": true}, {"label": "D", "text": "touching", "isCorrect": false}]'::jsonb, 'C', '''Assault and battery'' is a fixed legal collocation referring to physically attacking someone; ''assault'' is the only word that correctly pairs with ''battery'' in this legal sense.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0252', 'Use of English', 'Comprehension', 'Comprehension and Summary', NULL, '[{"weight": 1, "conceptId": "3r5lb7"}]'::jsonb, '{}', 3, 'application', 60, 'high', 'none', '[{"option": "A", "explanation": "A student might think presenting two sides means the writer lacks a firm position, mistaking balance for a lack of objectivity.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "This looks tempting because the writer avoids picking one style outright, but he does offer clear situational guidance, so he is not simply non-committal.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "A student rushing through the passage might mistake the writer''s careful analysis of both sides for excessive, unnecessary analysis.", "misconceptionId": "rushed_under_pressure"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Recgnizing the need for objectivity in their work, the early report writers to develop a writing style which convey this attitude. They reasoned that the source of the subjective quality in a report is the human being.  And they reasoned that objectivity is best attained by emphasizing the factual material of a report rather 5than the personalities involved. So they worked to remove the human being from their writing. Impersonal writing style was the result. By impersonal writing is meant writing in the third person-without I’s, we’s or you’s.

In recent years, impersonal writing has been strenuously questioned by many writers. These writers point out that personal writing is more forceful and direct than is impersonal writing. They contend that writing which brings both reader and writer into the picture is more like conversation and therefore more interesting. And the answer to the point on objectivity when written in personal style as when in impersonal style. Frequently, they counter with the argument that impersonal writing leads to an overuse of passive voice and a generally dull writing style. This last argument however lacks substances. Impersonal writing can and should be interesting. Any dullness it may have is wholly the fault of the writer. As proof, one has only to look at the lovely styles used by the writers for newspapers, news magazines and journals. Most of this writing is impersonal and usually it is not dull.

As in most cases of controversy, there is some merit to the arguments on both sides. There are situations in which personal writing is best. There are situations in which impersonal writing is best. And there are situations in which either style is appropriate. The writer must decide at the outset of his work which style is best for his own situation.

Her decision should be based on the circumstances of each report situation. First, he should consider the expectations or desires of those for whom he is preparing the report. More than likely he will find a preference for impersonal style for like most human beings; businessman has been slow to break tradition. Next, the writer should consider the formality of the report situation. If the situation is informal, as when the report is really a personal communication of information between business associates, personal writing is appropriate. But if the situation is formal, as is case with most reports, the conventional impersonal style is best.

Which of the following best describes the writer of the passage?', '[{"label": "A", "text": "he cannot be said to be objective", "isCorrect": false}, {"label": "B", "text": "he is completely non-committal", "isCorrect": false}, {"label": "C", "text": "he is objective and fair in presenting both sides of the argument", "isCorrect": true}, {"label": "D", "text": "he is being unnecessarily analytic", "isCorrect": false}]'::jsonb, 'C', 'The writer carefully presents arguments for both personal and impersonal writing styles and bases his conclusion on situational factors, showing balance and objectivity rather than bias.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0253', 'Use of English', 'Comprehension', 'Cloze/Gap-fill in Context', NULL, '[{"weight": 1, "conceptId": "hbrpoi"}]'::jsonb, '{}', 2, 'application', 60, 'high', 'none', '[{"option": "A", "explanation": "Respondent belongs to survey or interview contexts, not the controlled scientific method being described.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "System is a vague generic word that could loosely fit many contexts, making it an easy guess without close reading.", "misconceptionId": "guessed_no_reasoning"}, {"option": "D", "explanation": "Data is something a scientist collects during an experiment, not the method itself, confusing the tool with the process.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'The passage below has gaps numbered 11 to 20. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.

It is the business of the scientist to accumulate knowledge about the universe and all that is in it and to find if he is able, common

……11…..[A. experiment B. instruments C. approaches D. factors]

which underlie and account for the facts that he knows. He chooses when he can, the method of the controlled

…….12…..[A. respondent B. experiment C. system D. data]

. If he wants to find out the effect of light on growing plants, he takes many plants, as alike as possible. Some he stands in the sun, some in the shade, some in the dark, all the time keeping all other

.....13.....[A. studies B. procedures C. objects D. conditions]

(temperature, moisture, nourishments) the same. In this way, by keeping other variables

……..14……[A. constant B. good C. dark D. natural]

and by varying the light only, the effect of light on plants can be clearly seen. This

…….15…..[A. research B. method C. tool D. rationale]

of using ‘controls’ can be applied to a variety of situations and can be used to find the answers to questions as widely different as ‘must moisture be present if

…….16….[A. an alloy B. gold C. bar D. iron]

is to rust?’ and which variety of beans give the greatest yield in one

……17…..[A. climate B. period C. season D. weather]?

In the course of his

……18…..[A. finding B. queries C. experiment D. inquiries]

, the scientist may find what he thinks is one common explanation for an increasing number of facts the explanation, if it seems consistently to fit the various facts, is called

…….19……[A. an antithesis B. a principle C. a thesis D. a hypothesis]

. If this continues to stand the test of numerous experiments and remains unshaken, it becomes a

……20…..[A. deduction B. law C. notion D. thesis].

In question number 12 above, choose the best option from letters A-D that best completes the gap.', '[{"label": "A", "text": "respondent", "isCorrect": false}, {"label": "B", "text": "experiment", "isCorrect": true}, {"label": "C", "text": "system", "isCorrect": false}, {"label": "D", "text": "data", "isCorrect": false}]'::jsonb, 'B', 'The scientist ''chooses ... the method of the controlled experiment'' -- this is the standard term for the scientific method described through the rest of the passage.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0254', 'Use of English', 'Grammatical usage', 'Prepositions', NULL, '[{"weight": 1, "conceptId": "6de5er"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "B", "explanation": "Using ''at'' before a large place like a city is a common overgeneralization from its use with small, specific points such as ''at the bus stop''.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "This mixes the wrong preposition for the city with ''for'', which fits purpose in some phrases but not the idiom ''on an assignment''.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "This reverses the expected slots, a plausible slip for a student unsure which preposition belongs with a place versus a task.", "misconceptionId": "rushed_under_pressure"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

He is ....... Kaduna  ......... an official assignment?', '[{"label": "A", "text": "in / on", "isCorrect": true}, {"label": "B", "text": "at / in", "isCorrect": false}, {"label": "C", "text": "at / for", "isCorrect": false}, {"label": "D", "text": "for / in", "isCorrect": false}]'::jsonb, 'A', 'We use ''in'' with a city or town (in Kaduna) and ''on'' with the fixed expression ''on an official assignment''; the other pairings misuse at least one preposition.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0255', 'Use of English', 'Stress', 'Word Stress', NULL, '[{"weight": 1, "conceptId": "stfgmb"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "Dismiss is stressed on the second syllable (dis-MISS), so choosing it confuses first-syllable stress with simply being a short, common word.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Intact is stressed on the second syllable (in-TACT), a pattern easy to miss without pronouncing the word aloud.", "misconceptionId": "memorized_not_understood"}, {"option": "D", "explanation": "Confuse is stressed on the second syllable (con-FUSE), which is easy to mispronounce as first-syllable stress by loose analogy with other words.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Identify the word that has the stress on the first syllable.', '[{"label": "A", "text": "dismiss", "isCorrect": false}, {"label": "B", "text": "conquer", "isCorrect": true}, {"label": "C", "text": "intact", "isCorrect": false}, {"label": "D", "text": "confuse", "isCorrect": false}]'::jsonb, 'B', '''Conquer'' is stressed on its first syllable (CON-quer), while ''dismiss'', ''intact'', and ''confuse'' are all stressed on the second syllable.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0256', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "Condoned means overlooked or excused wrongdoing, an unrelated meaning a student might confuse due to a vaguely similar negative context.", "misconceptionId": "misunderstood_terminology"}, {"option": "B", "explanation": "Misrepresented implies the students actively distorted his words, whereas misconstrued is about how the attitude was wrongly interpreted, not restated.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Misquoted specifically involves incorrect wording of a quotation, not the broader interpretive error described by misconstrued.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option nearest in meaning to the underlined word(s).

The teacher''s apparent nonchalant attitude was

misconstrued

by his students?', '[{"label": "A", "text": "condoned", "isCorrect": false}, {"label": "B", "text": "misrepresented", "isCorrect": false}, {"label": "C", "text": "misquoted", "isCorrect": false}, {"label": "D", "text": "misunderstood", "isCorrect": true}]'::jsonb, 'D', '''Misconstrued'' means wrongly interpreted or misunderstood; ''misunderstood'' captures this meaning directly.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0257', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 3, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "Financier means someone who provides money, an unrelated meaning that could be guessed from the word''s unfamiliar sound.", "misconceptionId": "guessed_no_reasoning"}, {"option": "B", "explanation": "Editor is a newsroom role but refers to someone who reviews and prepares copy, not the freelance writer that stringer describes.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "This is close but too general -- it misses the key nuance that a stringer works freelance or part-time rather than as a staff reporter.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option nearest in meaning to the underlined word(s).

He is a

stringer

for a newspaper?', '[{"label": "A", "text": "a financier of", "isCorrect": false}, {"label": "B", "text": "an editor of", "isCorrect": false}, {"label": "C", "text": "a freelance correspondent for", "isCorrect": true}, {"label": "D", "text": "a reporter for", "isCorrect": false}]'::jsonb, 'C', 'A ''stringer'' is specifically a freelance or part-time correspondent who supplies reports to a newspaper without being a full-time staff member.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0258', 'Use of English', 'Grammatical usage', 'Prepositions', NULL, '[{"weight": 1, "conceptId": "6de5er"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''By'' does not collocate with ''agree'' in standard usage at all.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Agree on'' fits reaching a joint decision about something not yet settled, not accepting pre-existing contract terms.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "''Agree with'' is used for agreeing with a person''s opinion, not for accepting terms of a document.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

The members of the team agree ........ all the members of the contract?', '[{"label": "A", "text": "by", "isCorrect": false}, {"label": "B", "text": "to", "isCorrect": true}, {"label": "C", "text": "on", "isCorrect": false}, {"label": "D", "text": "with", "isCorrect": false}]'::jsonb, 'B', '''Members of the contract'' is a scraping artifact for ''terms of the contract'' -- the standard collocation for accepting a contract''s terms is ''agree TO'' them (agree on/with are for reaching mutual consensus with a person, not accepting existing terms).', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0259', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "B", "explanation": "This is a synonym, not an opposite, of the idiom''s meaning, so a student who forgets the question asks for an antonym may pick it.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "Like ''completely'', this restates the idiom''s own meaning rather than its opposite, showing the antonym instruction was overlooked.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "This idiom is about speaking bluntly, unrelated to how fully a person believes something, making it a plausible-sounding but mismatched idiom.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

He gave an unsatisfactory excuse, but the boss swallowed it

hook, line and sinker.', '[{"label": "A", "text": "half-heartedly", "isCorrect": true}, {"label": "B", "text": "completely", "isCorrect": false}, {"label": "C", "text": "entirely", "isCorrect": false}, {"label": "D", "text": "without mincing words", "isCorrect": false}]'::jsonb, 'A', '''Swallowed it hook, line and sinker'' means to accept something totally and without doubt; the opposite is to accept something only ''half-heartedly'', i.e. with reservation.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0260', 'Use of English', 'Sentence structure', 'Word Order', NULL, '[{"weight": 1, "conceptId": "mecosf"}]'::jsonb, '{}', 3, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "This reverses the correct adjective order (size before opinion), a common error when a student doesn''t apply the opinion-before-size rule.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "Placing ''together'' at the front, alongside the wrong adjective order, compounds two separate mistakes at once.", "misconceptionId": "rushed_under_pressure"}, {"option": "D", "explanation": "The adjective order is correct here, but ''together'' is still misplaced before the noun phrase instead of after it.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

Whenever we have ....... we feel better?', '[{"label": "A", "text": "a long good talk together", "isCorrect": false}, {"label": "B", "text": "a good long talk together", "isCorrect": true}, {"label": "C", "text": "together a long good talk", "isCorrect": false}, {"label": "D", "text": "together a good long talk", "isCorrect": false}]'::jsonb, 'B', 'Standard English adjective order places opinion before size/age (''good long talk''), and adverbs like ''together'' typically follow the noun phrase rather than precede it.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0261', 'Use of English', 'Stress', 'Emphatic Stress', NULL, '[{"weight": 1, "conceptId": "odd0o9"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "This targets the destination, which would be emphasized if ''palace'' carried the stress, not the verb ''ran''.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "This targets the subject ''king'', which would be relevant if ''king'' carried the stress, not the verb.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "This also targets the subject rather than the action, matching a stress on ''king'' rather than on ''RAN''.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'The word in capital letters has the emphatic stress. Choose the option that best fits the expression in the sentence.

The king RAN to the palace?', '[{"label": "A", "text": "Where did the king run to?", "isCorrect": false}, {"label": "B", "text": "Did the king walk to the palace?", "isCorrect": true}, {"label": "C", "text": "Did the queen run to the palace?", "isCorrect": false}, {"label": "D", "text": "Who ran to the palace?", "isCorrect": false}]'::jsonb, 'B', 'Emphatic stress on ''RAN'' highlights the action itself, as if correcting or contrasting it with a different action; ''Did the king walk to the palace?'' is the question this stress would directly, contrastively answer.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0262', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 3, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "Argued is a near-synonym of asserting a claim, not its opposite, so it fails to reverse the meaning as the question requires.", "misconceptionId": "misunderstood_terminology"}, {"option": "B", "explanation": "Confirmed reinforces that something is true, moving the meaning in the same direction as averred rather than opposite to it.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "Affirmed is essentially a direct synonym of averred, so picking it shows the antonym instruction was overlooked.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

The witness

averred

that had seen Dosun at the scene of the crime?', '[{"label": "A", "text": "argued", "isCorrect": false}, {"label": "B", "text": "confirmed", "isCorrect": false}, {"label": "C", "text": "denied", "isCorrect": true}, {"label": "D", "text": "affirmed", "isCorrect": false}]'::jsonb, 'C', '''Averred'' means to state firmly as true; its opposite is ''denied'', which means to state that something is not true.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0263', 'Use of English', 'Idiomatic expressions', 'Phrasal Verbs', NULL, '[{"weight": 1, "conceptId": "1fuv27"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "Come along usually means to make progress or to accompany someone, not to happen as scheduled.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Come on is typically an exclamation of encouragement or means ''to begin'' (e.g. rain came on), not ''to take place''.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "Come up usually means to arise or be mentioned, which is close in form but not the right sense of an event happening as planned.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

Despite all preparations, the wedding did not ....... ?', '[{"label": "A", "text": "come along", "isCorrect": false}, {"label": "B", "text": "come off", "isCorrect": true}, {"label": "C", "text": "come on", "isCorrect": false}, {"label": "D", "text": "come up", "isCorrect": false}]'::jsonb, 'B', '''Come off'' means to take place successfully or happen as planned; ''the wedding did not come off'' means it did not happen despite the preparations.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0264', 'Use of English', 'Grammatical usage', 'Tense', NULL, '[{"weight": 1, "conceptId": "hbp4zb"}]'::jsonb, '{}', 3, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "This is the conditional perfect, appropriate for hypothetical past situations, not a real future time expression like ''by this time next year''.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "Simple future seems natural but misses the ''by [future time]'' signal, which specifically calls for the future perfect to mark completion by that point.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "This modal expresses past possibility, which is inconsistent with a definite statement about a future age.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

By this time next year, I ...... twenty years old?', '[{"label": "A", "text": "would have been", "isCorrect": false}, {"label": "B", "text": "will be", "isCorrect": false}, {"label": "C", "text": "could have been", "isCorrect": false}, {"label": "D", "text": "will have been", "isCorrect": true}]'::jsonb, 'D', '''By this time next year'' signals a point by which a state will be complete, which requires the future perfect ''will have been'', rather than the simple future.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0265', 'Use of English', 'Vowels', 'Vowel Sounds', NULL, '[{"weight": 1, "conceptId": "namskj"}]'::jsonb, '{}', 3, 'application', 60, 'low', 'none', '[{"option": "B", "explanation": "''Hear'' shares /ɪə/ with clear and mere, so it isn''t the odd one out.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "''Clear'' also shares /ɪə/ with the other two.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "''Mere'' shares /ɪə/ as well -- all three are the same sound group.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option that has a different vowel sound from the others?', '[{"label": "A", "text": "tear (verb)", "isCorrect": true}, {"label": "B", "text": "hear", "isCorrect": false}, {"label": "C", "text": "clear", "isCorrect": false}, {"label": "D", "text": "mere", "isCorrect": false}]'::jsonb, 'A', '''Hear'', ''clear'' and ''mere'' all share the /ɪə/ diphthong. ''Tear'' as a verb (meaning to rip) is pronounced with /eə/, the different vowel sound.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0266', 'Use of English', 'Comprehension', 'Comprehension and Summary', NULL, '[{"weight": 1, "conceptId": "3r5lb7"}]'::jsonb, '{}', 2, 'application', 60, 'high', 'none', '[{"option": "A", "explanation": "This contradicts the passage, which says the impersonal style is the preferred, dominant convention, not sparingly used.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "The passage says impersonal writing has recently been ''strenuously questioned'', the opposite of being widely acclaimed.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "This sounds plausible and close to the passage''s point, but it is a broader inference the passage doesn''t state as directly as the fact that impersonal writing ''is not dull''.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Recgnizing the need for objectivity in their work, the early report writers to develop a writing style which convey this attitude. They reasoned that the source of the subjective quality in a report is the human being.  And they reasoned that objectivity is best attained by emphasizing the factual material of a report rather 5than the personalities involved. So they worked to remove the human being from their writing. Impersonal writing style was the result. By impersonal writing is meant writing in the third person-without I’s, we’s or you’s.

In recent years, impersonal writing has been strenuously questioned by many writers. These writers point out that personal writing is more forceful and direct than is impersonal writing. They contend that writing which brings both reader and writer into the picture is more like conversation and therefore more interesting. And the answer to the point on objectivity when written in personal style as when in impersonal style. Frequently, they counter with the argument that impersonal writing leads to an overuse of passive voice and a generally dull writing style. This last argument however lacks substances. Impersonal writing can and should be interesting. Any dullness it may have is wholly the fault of the writer. As proof, one has only to look at the lovely styles used by the writers for newspapers, news magazines and journals. Most of this writing is impersonal and usually it is not dull.

As in most cases of controversy, there is some merit to the arguments on both sides. There are situations in which personal writing is best. There are situations in which impersonal writing is best. And there are situations in which either style is appropriate. The writer must decide at the outset of his work which style is best for his own situation.

Her decision should be based on the circumstances of each report situation. First, he should consider the expectations or desires of those for whom he is preparing the report. More than likely he will find a preference for impersonal style for like most human beings; businessman has been slow to break tradition. Next, the writer should consider the formality of the report situation. If the situation is informal, as when the report is really a personal communication of information between business associates, personal writing is appropriate. But if the situation is formal, as is case with most reports, the conventional impersonal style is best.

Which of the following statement is true according to the passage?', '[{"label": "A", "text": "most report writing is characterized by the sparing use of the impersonal style", "isCorrect": false}, {"label": "B", "text": "impersonal writing is not necessarily dull", "isCorrect": true}, {"label": "C", "text": "the impersonal style has been widely acclaimed", "isCorrect": false}, {"label": "D", "text": "most writers use the impersonal style to achieve objectivity in their reports", "isCorrect": false}]'::jsonb, 'B', 'The passage explicitly states that impersonal writing ''can and should be interesting'' and that most impersonal writing in newspapers and journals ''is not dull'', directly supporting this statement.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0267', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 3, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "This is close in meaning to redounds to rather than its opposite, so it fails to reverse the sense as required.", "misconceptionId": "misunderstood_terminology"}, {"option": "B", "explanation": "Reflects on is a neutral paraphrase of redounds rather than a true opposite that would signal harm to the company''s image.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Contributes is essentially a direct synonym for redounds to, showing the antonym requirement was missed.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

The chairman''s conduct

redounds

to the image of the company?', '[{"label": "A", "text": "assists in", "isCorrect": false}, {"label": "B", "text": "reflects on", "isCorrect": false}, {"label": "C", "text": "contributes", "isCorrect": false}, {"label": "D", "text": "detracts from", "isCorrect": true}]'::jsonb, 'D', '''Redounds to'' means contributes positively to; its opposite is ''detracts from'', meaning it lessens or damages.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0268', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "Reproduce is unrelated to dormancy and might be guessed from a vague association with animal behaviour in general.", "misconceptionId": "guessed_no_reasoning"}, {"option": "B", "explanation": "This confuses hibernation, a seasonal, long-term dormancy, with simple nocturnal hiding behaviour.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "Relax captures rest but misses the specific, prolonged, seasonal dormancy that defines hibernation.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option nearest in meaning to the underlined word(s).

Tortoises need cool climates and must have places where they can

hibernate

?', '[{"label": "A", "text": "reproduce", "isCorrect": false}, {"label": "B", "text": "hide at night", "isCorrect": false}, {"label": "C", "text": "sleep through the cold season", "isCorrect": true}, {"label": "D", "text": "relax", "isCorrect": false}]'::jsonb, 'C', '''Hibernate'' means to spend the winter in a dormant, sleep-like state; ''sleep through the cold season'' captures this precisely.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0269', 'Use of English', 'Sentence structure', 'Complementation Patterns', NULL, '[{"weight": 1, "conceptId": "ogyr3x"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "B", "explanation": "Adding the possessive ''their'' is unnecessary and non-standard after elect in this object-complement construction.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "This wrongly adds an infinitive, treating elect like a verb that takes a to-infinitive complement, which it does not in this construction.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "This adds both an infinitive and an unnecessary article, doubling the errors from a misapplied verb pattern.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

The members elected Baba ....... of the committee?', '[{"label": "A", "text": "chairman", "isCorrect": true}, {"label": "B", "text": "their chairman", "isCorrect": false}, {"label": "C", "text": "to become chairman", "isCorrect": false}, {"label": "D", "text": "to be a chairman", "isCorrect": false}]'::jsonb, 'A', 'Verbs like ''elect'' and ''appoint'' take a bare noun as an object complement (''elected Baba chairman''), without an article, possessive, or infinitive.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0270', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "B", "explanation": "Imposing describes an impressive or commanding presence, an unrelated meaning that could be confused due to a vaguely similar tone of strength.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "Uncompromising is essentially a synonym for hardline, so choosing it shows the antonym instruction was missed.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "Difficult is a loosely related negative word but does not specifically reverse the meaning of an uncompromising stance.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

The

hardline

posture of the labour leader has not helped matters?', '[{"label": "A", "text": "conciliatory", "isCorrect": true}, {"label": "B", "text": "imposing", "isCorrect": false}, {"label": "C", "text": "uncompromising", "isCorrect": false}, {"label": "D", "text": "difficult", "isCorrect": false}]'::jsonb, 'A', '''Hardline'' describes an uncompromising, tough stance; its opposite is ''conciliatory'', meaning willing to compromise or make peace.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0271', 'Use of English', 'Appropriate word choice', 'Word Choice in Context', NULL, '[{"weight": 1, "conceptId": "kxwnre"}]'::jsonb, '{}', 1, 'recall', 60, 'low', 'none', '[{"option": "B", "explanation": "Dangerous contradicts the stated reason (amusing) and instead fits a context of risk or threat.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Sad is the opposite emotional tone to amusing, an error a student might make by rushing past the reason clause.", "misconceptionId": "rushed_under_pressure"}, {"option": "D", "explanation": "Libellous relates to damaging false statements, a legal concept unrelated to something being amusing.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

The officer described the comments as ........ because it was very amusing?', '[{"label": "A", "text": "hilarious", "isCorrect": true}, {"label": "B", "text": "dangerous", "isCorrect": false}, {"label": "C", "text": "sad", "isCorrect": false}, {"label": "D", "text": "libellous", "isCorrect": false}]'::jsonb, 'A', 'Since the comments were ''very amusing'', the officer would describe them as ''hilarious'', meaning extremely funny.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0272', 'Use of English', 'Grammatical usage', 'Gerunds vs Infinitives', NULL, '[{"weight": 1, "conceptId": "chpexv"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "The gerund subject is correct, but ''harmful for'' is a common preposition error; the fixed phrase is ''harmful to''.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Infinitive subjects are less natural for general statements, and this also repeats the wrong preposition ''for''.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "This combines two errors: an awkward infinitive subject and a preposition, ''with'', that doesn''t collocate with ''harmful'' at all.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

....... a motor cycle can be harmful ..... your health.', '[{"label": "A", "text": "riding / for", "isCorrect": false}, {"label": "B", "text": "riding / to", "isCorrect": true}, {"label": "C", "text": "to ride / for", "isCorrect": false}, {"label": "D", "text": "to ride / with", "isCorrect": false}]'::jsonb, 'B', 'A gerund (''Riding'') is the natural subject for a general statement, and the fixed collocation is ''harmful to (one''s health)'', not ''harmful for/with''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0273', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "B", "explanation": "Hissing describes a specific type of sound, not the general unsettling quality that eerie conveys.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Harsh describes an unpleasant, grating sound quality rather than the uncanny, frightening quality of eerie.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "Loud only describes volume, missing the eerie sound''s unsettling, frightening character entirely.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option nearest in meaning to the underlined word(s).

The man outran his wife when they heard the

eerie

sound?', '[{"label": "A", "text": "strange and frightening", "isCorrect": true}, {"label": "B", "text": "hissing", "isCorrect": false}, {"label": "C", "text": "harsh", "isCorrect": false}, {"label": "D", "text": "loud", "isCorrect": false}]'::jsonb, 'A', '''Eerie'' describes something strange and frightening in an uncanny way, which best matches ''strange and frightening'' among the options.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0274', 'Use of English', 'Consonants', 'Consonant Sounds', NULL, '[{"weight": 1, "conceptId": "3p5hul"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "The ''s'' sound (spelled ''ce'') in grace represents /s/, not /z/, matching the letter shape rather than the actual pronunciation.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "Rice ends in the /s/ sound, easily confused with rise due to their similar spelling, but the sounds differ.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "The initial ''s'' in sink is /s/, an easy default choice since ''s'' most commonly represents /s/ rather than /z/.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option that has the same consonant sound as the one represented by the underlined letter(s).

bu

s

iness', '[{"label": "A", "text": "grace", "isCorrect": false}, {"label": "B", "text": "rice", "isCorrect": false}, {"label": "C", "text": "rise", "isCorrect": true}, {"label": "D", "text": "sink", "isCorrect": false}]'::jsonb, 'C', 'The underlined ''s'' in ''business'' is pronounced /z/; ''rise'' is the only option whose ''s'' also represents the /z/ sound, while the others use /s/.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0275', 'Use of English', 'Stress', 'Word Stress', NULL, '[{"weight": 1, "conceptId": "stfgmb"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "B", "explanation": "Suffer is stressed on the first syllable, so a student who mispronounces it might wrongly think its pattern differs from the others.", "misconceptionId": "memorized_not_understood"}, {"option": "C", "explanation": "As a compound noun, blackboard follows the common first-syllable stress rule, which some may not recognize as shared with the other words.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "Calendar is stressed on the first syllable; a student unsure of the three-syllable pattern might mistakenly flag it as different.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the word that has a different stress pattern from the others.', '[{"label": "A", "text": "prevent", "isCorrect": true}, {"label": "B", "text": "suffer", "isCorrect": false}, {"label": "C", "text": "blackboard", "isCorrect": false}, {"label": "D", "text": "calendar", "isCorrect": false}]'::jsonb, 'A', '''Prevent'' is stressed on the second syllable (pre-VENT), while ''suffer'', ''blackboard'', and ''calendar'' are all stressed on the first syllable.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb);