INSERT INTO kairo.questions (id, subject, topic, subtopic, learning_objective, concepts_tested, prerequisite_concepts, difficulty_rating, cognitive_level, estimated_solving_time_sec, reading_load, calculation_load, distractors, skills_assessed, source, year, exam_body, related_question_ids, stem, options, correct_option, explanation, lifecycle_state, empirical_stats) VALUES
('use_of_english_0350', 'Use of English', 'Grammatical usage', 'Prepositions', NULL, '[{"weight": 1, "conceptId": "6de5er"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Differed to me'' is not a standard collocation -- ''differ'' pairs with ''from'' or ''with'', not ''to''.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "''Angry about'' fits a situation, not a person -- ''angry with'' is required for a person.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "''Angry against'' is not idiomatic English.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

I was often angry ....... Oche since he differed ....... me often?', '[{"label": "A", "text": "with / to", "isCorrect": false}, {"label": "B", "text": "about / with", "isCorrect": false}, {"label": "C", "text": "against / from", "isCorrect": false}, {"label": "D", "text": "with / with", "isCorrect": true}]'::jsonb, 'D', '''Angry with'' a person and ''differ with'' someone (meaning to disagree) are both standard, correct collocations.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0351', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Submitting to'' is a direct synonym of acquiescing, not its opposite.", "misconceptionId": "misunderstood_terminology"}, {"option": "B", "explanation": "''Adjusting'' describes adapting, not the specific compliance-vs-resistance dimension being tested.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Compromising on'' still implies some agreement, closer to acquiescing than opposing it.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

The proprietor accused Uche of silently

acquiescing

to the students'' demands?', '[{"label": "A", "text": "submitting to", "isCorrect": false}, {"label": "B", "text": "adjusting", "isCorrect": false}, {"label": "C", "text": "compromising on", "isCorrect": false}, {"label": "D", "text": "resisting", "isCorrect": true}]'::jsonb, 'D', '''Acquiescing'' means passively complying; its opposite is ''resisting''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0352', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Similar with'' is essentially a synonym of analogous, not its opposite.", "misconceptionId": "misunderstood_terminology"}, {"option": "B", "explanation": "''Distant from'' addresses physical/temporal distance, not the comparability dimension analogous concerns.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Advantageous to'' is an unrelated quality about benefit, not similarity.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

The teacher recounted two events that were

analogous with

each other.', '[{"label": "A", "text": "similar with", "isCorrect": false}, {"label": "B", "text": "distant from", "isCorrect": false}, {"label": "C", "text": "advantageous to", "isCorrect": false}, {"label": "D", "text": "different from", "isCorrect": true}]'::jsonb, 'D', '''Analogous'' means similar or comparable; its opposite is ''different from''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0353', 'Use of English', 'Grammatical usage', 'Reported Speech', NULL, '[{"weight": 1, "conceptId": "k1pf7b"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Fails to backshift the tense from ''am'' to ''was'' to match the past-tense reporting verb ''asked''.", "misconceptionId": "overgeneralized_rule"}, {"option": "B", "explanation": "This is a direct question format, not the indirect/reported form the sentence requires.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "Keeps the inverted question word order (''was I'') instead of the statement order required in reported speech (''I was'').", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

Yesterday, my mother asked me......', '[{"label": "A", "text": "if I am tired", "isCorrect": false}, {"label": "B", "text": "are you tired?", "isCorrect": false}, {"label": "C", "text": "whether was I tired", "isCorrect": false}, {"label": "D", "text": "if I was tired", "isCorrect": true}]'::jsonb, 'D', 'Reported yes/no questions use ''if''/''whether'' plus normal statement word order, with the tense backshifted to match the past reporting verb: ''asked me if I was tired''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0354', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Smooth and shiny'' is a direct restatement of glossy''s meaning, not its opposite.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "''Smooth and shining'' is also a synonym, not an opposite.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "''Rough and gummy'' gets the roughness right but ''gummy'' is an odd, unrelated addition rather than the precise opposite of ''shiny''.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option

opposite in meaning

to the underlined word(s).

Asabe bought a

glossy

pair of shoes.', '[{"label": "A", "text": "smooth and shiny", "isCorrect": false}, {"label": "B", "text": "rough and dull", "isCorrect": true}, {"label": "C", "text": "smooth and shining", "isCorrect": false}, {"label": "D", "text": "rough and gummy", "isCorrect": false}]'::jsonb, 'B', '''Glossy'' means smooth and shiny; its opposite is ''rough and dull''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0355', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Curious'' means eager to learn, a related but distinct quality from noticing details.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Inductive'' relates to a type of reasoning, not to noticing details.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "''Inquisitive'' means eager to ask questions, close to but not the same as being observant.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the

option nearest in meaning

to the word or phrase underlined.

No wonder Sikemi later became a detective; she has been very

observant.', '[{"label": "A", "text": "curious", "isCorrect": false}, {"label": "B", "text": "perceptive", "isCorrect": true}, {"label": "C", "text": "inductive", "isCorrect": false}, {"label": "D", "text": "inquisitive", "isCorrect": false}]'::jsonb, 'B', '''Observant'' means quick to notice details; ''perceptive'' is its nearest match.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0356', 'Use of English', 'Stress', 'Word Stress', NULL, '[{"weight": 1, "conceptId": "stfgmb"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Stress on the first syllable doesn''t match this word''s pronunciation.", "misconceptionId": "memorized_not_understood"}, {"option": "C", "explanation": "Stress on the third syllable is incorrect.", "misconceptionId": "memorized_not_understood"}, {"option": "D", "explanation": "Stress on the final syllable is incorrect.", "misconceptionId": "memorized_not_understood"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the appropriate stress pattern from the options. The syllables are written in capital letters.

suburbanite', '[{"label": "A", "text": "SUburbanite", "isCorrect": false}, {"label": "B", "text": "suBURbanite", "isCorrect": true}, {"label": "C", "text": "suburBAnite", "isCorrect": false}, {"label": "D", "text": "suburbaNITE", "isCorrect": false}]'::jsonb, 'B', '''Suburbanite'' is stressed on its second syllable: su-BUR-ban-ite.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0357', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Serious'' is close to the opposite of superficial (which implies minor/shallow).", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "''Painless'' addresses sensation, not depth of the wound.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "''Internal'' is essentially the opposite of superficial, not its synonym.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the

option nearest in meaning

to the word or phrase underlined.

The accident victim received

a superficial

wound from the crash', '[{"label": "A", "text": "a serious", "isCorrect": false}, {"label": "B", "text": "a painless", "isCorrect": false}, {"label": "C", "text": "an internal", "isCorrect": false}, {"label": "D", "text": "an external", "isCorrect": true}]'::jsonb, 'D', 'A ''superficial'' wound is one on the surface only, i.e. ''external'', as opposed to a deep, internal injury.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0358', 'Use of English', 'Grammatical usage', 'Conditionals', NULL, '[{"weight": 1, "conceptId": "fbl55l"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "B", "explanation": "''Must'' wrongly turns a mere possibility into an obligation.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "Wrongly asserts as settled past fact (''did not go'') what the conditional leaves hypothetical.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "Introduces an unsupported reason (not wanting to go) that the original sentence never states.", "misconceptionId": "guessed_no_reasoning"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Select the option that best explains the information conveyed in the sentence.

If I visited England, I might go to Manchester City.', '[{"label": "A", "text": "When I go to England , I could go to Manchester City", "isCorrect": true}, {"label": "B", "text": "Whenever I visit England, I must go to Manchester City", "isCorrect": false}, {"label": "C", "text": "I did not go to England and could  not go to Manchester", "isCorrect": false}, {"label": "D", "text": "I could not visit Manchester City because I did not want to go to England", "isCorrect": false}]'::jsonb, 'A', 'The second conditional (''if...might'') expresses a hypothetical possibility contingent on visiting England; ''When I go to England, I could go to Manchester City'' preserves this same England-then-possibly-Manchester relationship.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0359', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "B", "explanation": "''Bodyguards'' describes a specific protective role, not the opposite of a loyal follower.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Sycophants'' (flatterers) is very close in meaning to henchmen, not its opposite.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "''Advisers'' are a different kind of associate, not specifically opposed to henchmen.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

The president can afford to dispense with some of his

henchmen.', '[{"label": "A", "text": "detractors", "isCorrect": true}, {"label": "B", "text": "body guards", "isCorrect": false}, {"label": "C", "text": "sycophants", "isCorrect": false}, {"label": "D", "text": "advisers", "isCorrect": false}]'::jsonb, 'A', '''Henchmen'' are loyal, often unquestioning followers; their opposite is ''detractors'' (critics/opponents).', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0360', 'Use of English', 'Vocabulary and expressions in context', 'Sentence Interpretation (Idiom)', NULL, '[{"weight": 1, "conceptId": "fno6b9"}]'::jsonb, '{}', 2, 'application', 60, 'medium', 'none', '[{"option": "A", "explanation": "Nothing in the sentence suggests the job is bad -- the opposite is implied.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "This misreads the double negative as only a mild qualification rather than a full reversal.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "The sentence describes the new job''s excitement, not whether it has been done before.", "misconceptionId": "guessed_no_reasoning"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Select the option that best explains the information conveyed in the sentence.

One thing I will not be complaining about in my new job is a lack of excitement?', '[{"label": "A", "text": "The job is bad", "isCorrect": false}, {"label": "B", "text": "The job is exciting", "isCorrect": true}, {"label": "C", "text": "The job is not too  exciting", "isCorrect": false}, {"label": "D", "text": "The job has been previously done", "isCorrect": false}]'::jsonb, 'B', '''Not complaining about a lack of excitement'' is a double negative meaning there IS plenty of excitement, i.e. the job is exciting.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0361', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Worried about'' is a synonym of wary, not its opposite.", "misconceptionId": "misunderstood_terminology"}, {"option": "B", "explanation": "''Satisfied with'' addresses contentment, not fear -- a different dimension than wary concerns.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Troubled about'' is also a synonym of wary, not its opposite.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

Many Nigerian are

wary

of night journeys', '[{"label": "A", "text": "worried about", "isCorrect": false}, {"label": "B", "text": "satisfied with", "isCorrect": false}, {"label": "C", "text": "unscared of", "isCorrect": true}, {"label": "D", "text": "troubled about", "isCorrect": false}]'::jsonb, 'C', '''Wary'' means cautious or suspicious; its opposite is ''unscared of'' (not afraid of).', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0362', 'Use of English', 'Idiomatic expressions', 'Phrasal Verbs', NULL, '[{"weight": 1, "conceptId": "1fuv27"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Fizzled out'' implies a weak, disappointing end, not a decisive win by knockout.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "Showing off talents is the opposite of petering out weakly.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "''Fizzled out'' implies giving up, not fighting on spiritedly.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the

option nearest in meaning

to the word or phrase underlined.

The boxer

fizzled out

just in the sixth round', '[{"label": "A", "text": "knocked out his opponent", "isCorrect": false}, {"label": "B", "text": "showed off his talents", "isCorrect": false}, {"label": "C", "text": "became tired but fought on spiritedly", "isCorrect": false}, {"label": "D", "text": "surrendered rather disappointingly", "isCorrect": true}]'::jsonb, 'D', '''Fizzled out'' means to end weakly or disappointingly after a promising start, matching a boxer surrendering disappointingly.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0363', 'Use of English', 'Grammatical usage', 'Concord (Subject-Verb Agreement)', NULL, '[{"weight": 1, "conceptId": "59ii9v"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Has been'' is third-person singular, which doesn''t agree with the second-person ''you''.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "''Is'' is also third-person singular, mismatching ''you''.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "''Was'' is a past-tense singular form; besides tense issues, it still doesn''t fit ''you'' correctly in this construction.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

You, who ...... convicted, should appeal.', '[{"label": "A", "text": "has been", "isCorrect": false}, {"label": "B", "text": "is", "isCorrect": false}, {"label": "C", "text": "was", "isCorrect": false}, {"label": "D", "text": "are", "isCorrect": true}]'::jsonb, 'D', 'The relative clause ''who ... convicted'' refers back to ''you'', so the verb must agree with ''you'': ''are''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0364', 'Use of English', 'Vocabulary', 'Collocations', NULL, '[{"weight": 1, "conceptId": "hyf9sx"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Borrowing'' describes what readers do, not what the library does.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Libraries do not typically ''rent'' books for a fee -- that''s a different service model.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "''Loaning'' is a plausible informal synonym, but ''lending'' is the standard term paired with libraries.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

The public library has stopped ........ books to readers?', '[{"label": "A", "text": "borrowing", "isCorrect": false}, {"label": "B", "text": "lending", "isCorrect": true}, {"label": "C", "text": "renting", "isCorrect": false}, {"label": "D", "text": "loaning", "isCorrect": false}]'::jsonb, 'B', 'Libraries ''lend'' books to readers (hence ''lending library''); this is the standard verb for the service.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0365', 'Use of English', 'Vocabulary and expressions in context', 'Sentence Interpretation (Idiom)', NULL, '[{"weight": 1, "conceptId": "fno6b9"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "B", "explanation": "The sentence specifies payment ''in full'', not ''some'' payment, and talks about being ''pruned down'' (reduced), not delayed.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "The sentence describes what happens when payment IS made in full, not a threat of rejection for not paying.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "This inverts the logic -- the sentence is about paying in full to avoid reduction, not about not needing to pay.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Select the option that best explains the information conveyed in the sentence.

If the trader paid in full, his order was not pruned down.', '[{"label": "A", "text": "The trader who made full payment did not have his order reduced", "isCorrect": true}, {"label": "B", "text": "The trader who made some payment did not have his order delayed", "isCorrect": false}, {"label": "C", "text": "Unless the trader paid  in full his order would be rejected", "isCorrect": false}, {"label": "D", "text": "As the trader did not increase his order, he did not need to pay in full", "isCorrect": false}]'::jsonb, 'A', '''Paid in full'' and ''not pruned down'' directly correspond to ''made full payment'' and ''did not have his order reduced''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0366', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'medium', 'none', '[{"option": "B", "explanation": "''Belonged to'' describes membership/ownership, an unrelated dimension.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "''Friendly with'' concerns social relationship, not the shared-era meaning of ''contemporary''.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Contested against'' implies rivalry, not the temporal relationship the word ''contemporary'' addresses.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

After fifty years, he could not find anyone who was

contemporary with

him at college.', '[{"label": "A", "text": "strange to", "isCorrect": true}, {"label": "B", "text": "belonged to", "isCorrect": false}, {"label": "C", "text": "friendly with", "isCorrect": false}, {"label": "D", "text": "contested against", "isCorrect": false}]'::jsonb, 'A', '''Contemporary with'' means existing at the same time as someone; its opposite is to be ''strange to'' (unfamiliar with, as someone from a different era would be).', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0367', 'Use of English', 'Vocabulary', 'Contextual Word Pairs', NULL, '[{"weight": 1, "conceptId": "nvgfyg"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Under the silence'' is not an idiomatic preposition choice, and ''looked'' is too static for eyes moving around a room.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "''Over the silence'' is not idiomatic, and ''surrounded'' doesn''t fit eyes as the subject.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "''Along the silence'' is not idiomatic phrasing.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

As we sat ....... the silence, my eyes ....... the room?', '[{"label": "A", "text": "under / looked", "isCorrect": false}, {"label": "B", "text": "over / surrounded", "isCorrect": false}, {"label": "C", "text": "in / roamed", "isCorrect": true}, {"label": "D", "text": "along / observed", "isCorrect": false}]'::jsonb, 'C', '''Sat in the silence'' and ''eyes roamed the room'' are both natural, idiomatic collocations describing quiet stillness and eyes wandering.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0368', 'Use of English', 'Grammatical usage', 'Tense', NULL, '[{"weight": 1, "conceptId": "hbp4zb"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Could have known'' expresses past possibility, not a definite future completion.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "''Might have known'' also expresses uncertain past possibility, not future perfect certainty.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Would have known'' is a conditional perfect form, appropriate for hypotheticals, not this straightforward future statement.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

By the end of the football match today, we ...... the best player?', '[{"label": "A", "text": "could have known", "isCorrect": false}, {"label": "B", "text": "might have known", "isCorrect": false}, {"label": "C", "text": "will have known", "isCorrect": true}, {"label": "D", "text": "would have known", "isCorrect": false}]'::jsonb, 'C', '''By the end of the match today'' signals a future point by which something will be complete, requiring the future perfect: ''will have known''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0369', 'Use of English', 'Consonants', 'Consonant Sounds', NULL, '[{"weight": 1, "conceptId": "3p5hul"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "B", "explanation": "''Impugn'' has a silent ''g'' (the ''gn'' is pronounced /n/), not the /ŋɡ/ cluster.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Ink'' has only /ŋk/ (nasal + k), no /g/ sound.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "''Orange'' has no /ŋ/ sound at all.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that has the same consonant sound as the one represented by the letters in brackets.

E(ng)lish', '[{"label": "A", "text": "single", "isCorrect": true}, {"label": "B", "text": "impugn", "isCorrect": false}, {"label": "C", "text": "ink", "isCorrect": false}, {"label": "D", "text": "orange", "isCorrect": false}]'::jsonb, 'A', '''English'' has the /ŋɡ/ consonant cluster (nasal + hard g). ''Single'' also has this /ŋɡ/ cluster.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0370', 'Use of English', 'Stress', 'Word Stress', NULL, '[{"weight": 1, "conceptId": "stfgmb"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "B", "explanation": "Stress on the second syllable is incorrect for this word.", "misconceptionId": "memorized_not_understood"}, {"option": "C", "explanation": "Stress on the first syllable is incorrect.", "misconceptionId": "memorized_not_understood"}, {"option": "D", "explanation": "Stress on the final syllable is incorrect; the primary stress falls on ''men'', not ''ize''.", "misconceptionId": "memorized_not_understood"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the appropriate stress pattern from the options. The syllables are written in capital letters.

departmentalize?', '[{"label": "A", "text": "departMENtalize", "isCorrect": true}, {"label": "B", "text": "dePARTmentalize", "isCorrect": false}, {"label": "C", "text": "DEpartmentalize", "isCorrect": false}, {"label": "D", "text": "departmenTALIZE", "isCorrect": false}]'::jsonb, 'A', '''Departmentalize'' is stressed on its third syllable: de-part-MEN-tal-ize.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0371', 'Use of English', 'Stress', 'Word Stress', NULL, '[{"weight": 1, "conceptId": "stfgmb"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Interpreter'' is stressed on its second syllable (in-TER-pret-er).", "misconceptionId": "overgeneralized_rule"}, {"option": "B", "explanation": "''Impossible'' is stressed on its second syllable (im-POS-sible).", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "''Remarkable'' is stressed on its second syllable (re-MARK-able).", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that has a different stress pattern from the others.', '[{"label": "A", "text": "interpreter", "isCorrect": false}, {"label": "B", "text": "impossible", "isCorrect": false}, {"label": "C", "text": "remarkable", "isCorrect": false}, {"label": "D", "text": "criticism", "isCorrect": true}]'::jsonb, 'D', '''Interpreter'', ''impossible'', and ''remarkable'' are all stressed on their second syllable. ''Criticism'' is stressed on its first syllable, the odd one out.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0372', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Calmly'' describes composure, not specifically politeness.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Carefully'' describes caution, a different quality from politeness.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "''Patiently'' describes tolerance of delay, not politeness specifically.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the

option nearest in meaning

to the word or phrase underlined.

Courteously

, Ade stood back to let his teacher go first through the door', '[{"label": "A", "text": "calmly", "isCorrect": false}, {"label": "B", "text": "politely", "isCorrect": true}, {"label": "C", "text": "carefully", "isCorrect": false}, {"label": "D", "text": "patiently", "isCorrect": false}]'::jsonb, 'B', '''Courteously'' means in a polite manner; ''politely'' is its direct synonym.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0373', 'Use of English', 'Idiomatic expressions', 'Sentence Interpretation (Idiom)', NULL, '[{"weight": 1, "conceptId": "91ez3x"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "This is a literal misreading of ''jaw'' as the body part rather than the slang verb ''to jaw'' (talk).", "misconceptionId": "misunderstood_terminology"}, {"option": "B", "explanation": "This confuses ''jawing'' (talking) with chewing, another literal misreading.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Nothing in ''jawing away'' specifically implies causing trouble, just excessive talking.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Select the option that best explains the information conveyed in the sentence.

The class was tired of the new boy jawing away all the time?', '[{"label": "A", "text": "He bit off people''s jaws", "isCorrect": false}, {"label": "B", "text": "He was always chewing in the class", "isCorrect": false}, {"label": "C", "text": "He was always making trouble for the class", "isCorrect": false}, {"label": "D", "text": "He talked continuously in the class", "isCorrect": true}]'::jsonb, 'D', '''Jawing away'' is informal slang for talking continuously/chattering.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb);