INSERT INTO kairo.concepts (id, name, subject, topic, subtopic, difficulty_weight, dependency_ids, question_pool_ids) VALUES
('cmb4nk', 'Combinations (Choosing r from n)', 'Mathematics', 'Permutations and combinations', 'Combinations (Choosing r from n)', 1.0, '{}', '{}'),
('prdrle', 'Product Rule Differentiation (Expression Form)', 'Mathematics', 'Differentiation', 'Product Rule Differentiation (Expression Form)', 1.0, '{}', '{}'),
('abtwcv', 'Area Between Two Curves', 'Mathematics', 'Applications of integration', 'Area Between Two Curves', 1.0, '{}', '{}'),
('isoexa', 'Isosceles Triangle Angle Chasing (Exterior Angle Theorem)', 'Mathematics', 'Triangles', 'Isosceles Triangle Angle Chasing (Exterior Angle Theorem)', 1.0, '{}', '{}'),
('optmxa', 'Optimization (Maximum Area with Fixed Perimeter)', 'Mathematics', 'Applications of differentiation', 'Optimization (Maximum Area with Fixed Perimeter)', 1.0, '{}', '{}'),
('mtxply', 'Matrix Polynomial Expressions', 'Mathematics', 'Matrices and determinants', 'Matrix Polynomial Expressions', 1.0, '{}', '{}'),
('facdsq', 'Factorization by Grouping (Difference of Squares Combined)', 'Mathematics', 'Factorization', 'Factorization by Grouping (Difference of Squares Combined)', 1.0, '{}', '{}'),
('surdmn', 'Algebraic Manipulation of Surd Expressions', 'Mathematics', 'Surds', 'Algebraic Manipulation of Surd Expressions', 1.0, '{}', '{}'),
('bearfp', 'Bearings (Finding Bearing Between Two Points)', 'Mathematics', 'Trigonometric functions', 'Bearings (Finding Bearing Between Two Points)', 1.0, '{}', '{}'),
('raddfe', 'Radius from Diameter Endpoints (Distance Formula)', 'Mathematics', 'Circles', 'Radius from Diameter Endpoints (Distance Formula)', 1.0, '{}', '{}'),
('decexp', 'Evaluating Decimal Expressions to Given Decimal Places', 'Mathematics', 'Fractions, decimals and approximations', 'Evaluating Decimal Expressions to Given Decimal Places', 1.0, '{}', '{}'),
('iqrang', 'Interquartile Range', 'Mathematics', 'Measures of dispersion', 'Interquartile Range', 1.0, '{}', '{}'),
('polydv', 'Polynomial Division Using Substitution', 'Mathematics', 'Polynomials', 'Polynomial Division Using Substitution', 1.0, '{}', '{}'),
('linega', 'Equation of a Line (Gradient from Angle)', 'Mathematics', 'Coordinate geometry', 'Equation of a Line (Gradient from Angle)', 1.0, '{}', '{}'),
('isoeqp', 'Isosceles Triangle from Equidistant Point (Sine Rule)', 'Mathematics', 'Triangles', 'Isosceles Triangle from Equidistant Point (Sine Rule)', 1.0, '{}', '{}'),
('simlnq', 'Simultaneous Equations (Linear and Quadratic)', 'Mathematics', 'Simultaneous equations', 'Simultaneous Equations (Linear and Quadratic)', 1.0, '{}', '{}'),
('intsub', 'Integration by Substitution (Power Rule)', 'Mathematics', 'Integration', 'Integration by Substitution (Power Rule)', 1.0, '{}', '{}'),
('arcchr', 'Arc Length from Chord Equal to Radius', 'Mathematics', 'Circles', 'Arc Length from Chord Equal to Radius', 1.0, '{}', '{}'),
('varnc1', 'Variance', 'Mathematics', 'Measures of dispersion', 'Variance', 1.0, '{}', '{}'),
('conesc', 'Cone Formed from a Sector (Base Radius)', 'Mathematics', 'Mensuration', 'Cone Formed from a Sector (Base Radius)', 1.0, '{}', '{}'),
('algfrs', 'Evaluating Algebraic Fraction Expressions with a Substitution', 'Mathematics', 'Algebraic expressions', 'Evaluating Algebraic Fraction Expressions with a Substitution', 1.0, '{}', '{}'),
('paraqd', 'Finding a Parameter from Two Intersecting Quadratics', 'Mathematics', 'Quadratic equations', 'Finding a Parameter from Two Intersecting Quadratics', 1.0, '{}', '{}'),
('npermn', 'Permutations (nPr Notation)', 'Mathematics', 'Permutations and combinations', 'Permutations (nPr Notation)', 1.0, '{}', '{}'),
('sclmtx', 'Scalar Multiplication of a Matrix', 'Mathematics', 'Matrices and determinants', 'Scalar Multiplication of a Matrix', 1.0, '{}', '{}'),
('linint', 'Linear Inequalities (Integer Solutions)', 'Mathematics', 'Inequalities', 'Linear Inequalities (Integer Solutions)', 1.0, '{}', '{}');
