INSERT INTO kairo.questions (id, subject, topic, subtopic, learning_objective, concepts_tested, prerequisite_concepts, difficulty_rating, cognitive_level, estimated_solving_time_sec, reading_load, calculation_load, distractors, skills_assessed, source, year, exam_body, related_question_ids, stem, options, correct_option, explanation, lifecycle_state, empirical_stats) VALUES
('use_of_english_0226', 'Use of English', 'Comprehension', 'Comprehension and Summary', NULL, '[{"weight": 1, "conceptId": "3r5lb7"}]'::jsonb, '{}', 3, 'application', 60, 'high', 'none', '[{"option": "A", "explanation": "Not supported — the passage attributes resistance to specific fears, not a lack of understanding.", "misconceptionId": "guessed_no_reasoning"}, {"option": "C", "explanation": "This is literally the fear the passage explicitly rebuts (''there is nothing... to suggest deregulation will cause the government to be indifferent''), not the writer''s own conclusion.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "This is also presented as one of the rebutted fears, not the writer''s actual suggestion.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Those who have been following the argument for and against the deregulation of the oil industry in Nigeria may have got the impression that deregulation connotes lack of control or indifference on the part of the government. But there is nothing so far from official quarters to suggest that deregulation will cause the government to relinquish its control of the oil industry because the absence of direct control does not mean that it will surrender all its rights to the entrepreneurs who may want to participate in the industry. Yet the opposition expressed so far against stems from the fear that the government would leave Nigerians at the mercy of a heartless cartel who would command the heights of the oil industry and cause pump price of fuel to rise above the means of most Nigerians.

`As a result of such fears, many Nigerians have become resentful of deregulation and in fact the Nigeria Labour Congress  (NLC) has threatened to ‘deregulate’ the government if it should go ahead with the deregulation plan. But Nigerians have not fared any better with the economy totally in government control. Until recently, the most important sectors of the economy were in the hands of the government. Today, the deregulation of some of these sectors has broken its monopoly and introduced healthy competition to make a little easier for Nigerians. A good example is the breaking of the stifling monopoly of Nigeria Airways. Today, the traveller is king at the domestic airports as opposed to the struggle that air travels used to be under Nigeria Airways monopoly. Before, it was almost easier for a camel to pass through the eye of a needle than for travellers to board a plane.

Following from this, the apostles of deregulation rightly heap all the blame for the problems associated with petroleum products distribution in this country squarely on the government, which owns all the refineries and which sells fuel to local consumers through its agency, the Nigerian National Petroleum Corporation (NNPC). In the same way, the government argues that if the current NNPC monopoly were broken with the introduction of entrepreneurs to the refining and sale of petroleum products in the country, the Nigerian people would be all the better for it. It stands to reason that once the government continues to fix maximum prices would be all the better for it. It stands to reason that once the government continues to fix maximum prices for petroleum products in this country, the deregulation of the oil sector should bring some relief to the people by ensuring that wastage, corruption and inefficiency are reduced to the minimum. Consumers will also have the last laugh because competition will result in the availability of the products at reasonable prices. This appears to be the sense in deregulation.

The writer seems to suggest that', '[{"label": "A", "text": "nigerians do not understand the sense in deregulation", "isCorrect": false}, {"label": "B", "text": "deregulation, if properly implemented, will ultimately benefit ordinary nigerians through competition", "isCorrect": true}, {"label": "C", "text": "a deregulation economy will cause the government to be indifferent to the plight of ordinary nigerians", "isCorrect": false}, {"label": "D", "text": "only a heartless cartel will benefit by the deregulation of the oil industry", "isCorrect": false}]'::jsonb, 'B', 'The passage''s overall tone is cautiously pro-deregulation, arguing that competition will reduce wastage/corruption and benefit consumers — consistent only with option B.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0227', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Indubitable'' (as intended, despite the typo) is a synonym of incontrovertible — beyond doubt — not its opposite.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "''Practicable'' is about feasibility, an unrelated dimension to certainty of evidence.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Logical'' is about the validity of reasoning, not the certainty of the evidence itself.", "misconceptionId": "guessed_no_reasoning"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

The evidence the leader gave was

incontrovertible

.', '[{"label": "A", "text": "indulbitable", "isCorrect": false}, {"label": "B", "text": "disputable", "isCorrect": true}, {"label": "C", "text": "practicable", "isCorrect": false}, {"label": "D", "text": "logical", "isCorrect": false}]'::jsonb, 'B', '''Incontrovertible'' means beyond dispute/certain; its opposite is ''disputable'' (open to question).', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0228', 'Use of English', 'Grammatical usage', 'Concord (Subject-Verb Agreement)', NULL, '[{"weight": 1, "conceptId": "59ii9v"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Uses singular ''does'' with a plural subject, and the wrong verb form ''covered'' after ''not''.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "Uses singular ''does'' which does not agree with the plural subject ''operations''.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "Uses the wrong tense ''did'' and the wrong verb form ''covered'', both inconsistent with the present-tense context.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

The operations of the bank ........ not ...... cottage and small-scale industries?', '[{"label": "A", "text": "does / covered", "isCorrect": false}, {"label": "B", "text": "does / cover", "isCorrect": false}, {"label": "C", "text": "did / covered", "isCorrect": false}, {"label": "D", "text": "do / cover", "isCorrect": true}]'::jsonb, 'D', '''The operations'' is a plural subject, so it needs the plural auxiliary ''do'', not ''does'' or ''did'': ''do not cover''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0229', 'Use of English', 'Grammatical usage', 'Conditionals', NULL, '[{"weight": 1, "conceptId": "fbl55l"}]'::jsonb, '{}', 3, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''In spite'' is grammatically incomplete (needs ''of'') and expresses concession, not condition.", "misconceptionId": "misunderstood_terminology"}, {"option": "B", "explanation": "''Given'' implies assuming problems exist, the wrong nuance for ''I shall still travel as planned''.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''In case of'' implies preparing for a contingency, not the intended ''if none arise'' meaning.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

....... any problems, I shall travel to London tomorrow on a business trip?', '[{"label": "A", "text": "in spite", "isCorrect": false}, {"label": "B", "text": "given", "isCorrect": false}, {"label": "C", "text": "in case of", "isCorrect": false}, {"label": "D", "text": "barring", "isCorrect": true}]'::jsonb, 'D', '''Barring any problems'' means ''if no problems arise'', which fits ''I shall travel tomorrow'' as the plan assuming nothing goes wrong.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0230', 'Use of English', 'Idiomatic expressions', 'Sentence Interpretation (Idiom)', NULL, '[{"weight": 1, "conceptId": "91ez3x"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "B", "explanation": "Wrongly assumes the change must be negative, when flux is neutral about direction.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "Wrongly assumes the change must be positive, again missing flux''s neutral meaning.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Moribund'' means dying/stagnant, essentially the opposite of active flux/change.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Select the option that best explain the information conveyed in the sentence.

The organization is constantly in a state of flux?', '[{"label": "A", "text": "The organization is constantly/continuously changing", "isCorrect": true}, {"label": "B", "text": "The organization is facing a difficult period", "isCorrect": false}, {"label": "C", "text": "The organization is experiencing good times", "isCorrect": false}, {"label": "D", "text": "The organization is moribund", "isCorrect": false}]'::jsonb, 'A', '''In a state of flux'' means undergoing continuous change (which could be positive or negative) — not specifically bad or good times, and not stagnation.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0231', 'Use of English', 'Sentence completion', 'Contextual Word Pairs', NULL, '[{"weight": 1, "conceptId": "ak1vrj"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Okay'' and ''optimistic'' are both mildly positive, giving no real contrast for ''though'' to signal.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "''Nostalgic'' is about longing for the past, not a stance on the future, so it doesn''t fit logically.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "''Unsatisfied'' is not really a forward-looking stance on prospects, a weak fit for the sentence.", "misconceptionId": "guessed_no_reasoning"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

The future of the company is ...... though many seem .....about it?', '[{"label": "A", "text": "okay / optimistic", "isCorrect": false}, {"label": "B", "text": "promising / nostalgic", "isCorrect": false}, {"label": "C", "text": "bright / pessimistic", "isCorrect": true}, {"label": "D", "text": "dicy / unsatisfied", "isCorrect": false}]'::jsonb, 'C', '''Though'' signals a contrast: the future looks good (''bright'') even though many people''s feelings about it are negative (''pessimistic'') — the only pairing with genuine opposite valence.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0232', 'Use of English', 'Comprehension', 'Comprehension and Summary', NULL, '[{"weight": 1, "conceptId": "3r5lb7"}]'::jsonb, '{}', 2, 'application', 60, 'high', 'none', '[{"option": "A", "explanation": "Too narrow — captures only the pro-deregulation side, ignoring the fears and counterarguments the passage also discusses.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "The opposite emphasis — the passage''s overall tone favours deregulation rather than warning against it.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "Too narrow — the NNPC is only one specific example within the broader debate.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Those who have been following the argument for and against the deregulation of the oil industry in Nigeria may have got the impression that deregulation connotes lack of control or indifference on the part of the government. But there is nothing so far from official quarters to suggest that deregulation will cause the government to relinquish its control of the oil industry because the absence of direct control does not mean that it will surrender all its rights to the entrepreneurs who may want to participate in the industry. Yet the opposition expressed so far against stems from the fear that the government would leave Nigerians at the mercy of a heartless cartel who would command the heights of the oil industry and cause pump price of fuel to rise above the means of most Nigerians.

`As a result of such fears, many Nigerians have become resentful of deregulation and in fact the Nigeria Labour Congress  (NLC) has threatened to ‘deregulate’ the government if it should go ahead with the deregulation plan. But Nigerians have not fared any better with the economy totally in government control. Until recently, the most important sectors of the economy were in the hands of the government. Today, the deregulation of some of these sectors has broken its monopoly and introduced healthy competition to make a little easier for Nigerians. A good example is the breaking of the stifling monopoly of Nigeria Airways. Today, the traveller is king at the domestic airports as opposed to the struggle that air travels used to be under Nigeria Airways monopoly. Before, it was almost easier for a camel to pass through the eye of a needle than for travellers to board a plane.

Following from this, the apostles of deregulation rightly heap all the blame for the problems associated with petroleum products distribution in this country squarely on the government, which owns all the refineries and which sells fuel to local consumers through its agency, the Nigerian National Petroleum Corporation (NNPC). In the same way, the government argues that if the current NNPC monopoly were broken with the introduction of entrepreneurs to the refining and sale of petroleum products in the country, the Nigerian people would be all the better for it. It stands to reason that once the government continues to fix maximum prices would be all the better for it. It stands to reason that once the government continues to fix maximum prices for petroleum products in this country, the deregulation of the oil sector should bring some relief to the people by ensuring that wastage, corruption and inefficiency are reduced to the minimum. Consumers will also have the last laugh because competition will result in the availability of the products at reasonable prices. This appears to be the sense in deregulation.

An appropriate title for this passage is', '[{"label": "A", "text": "the advantage of a deregulated economy", "isCorrect": false}, {"label": "B", "text": "the debate over deregulation of the oil industry", "isCorrect": true}, {"label": "C", "text": "highlighting the dangers of deregulation", "isCorrect": false}, {"label": "D", "text": "the problems of the NNPC", "isCorrect": false}]'::jsonb, 'B', 'The passage presents both the fears against deregulation and the arguments for it before reaching a qualified conclusion — a title should reflect that balanced debate, not just one side.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0233', 'Use of English', 'Stress', 'Emphatic Stress', NULL, '[{"weight": 1, "conceptId": "odd0o9"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Queries the object via a relative clause instead of the emphasized verb.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "Queries the subject (''who'') rather than the emphasized verb.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "Queries the object (''what'') rather than the emphasized verb.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'The word in capital letters has the emphatic stress. Choose the option that best fits the expression in the sentence.

The man BOUGHT the newspaper.', '[{"label": "A", "text": "Is this the newspaper which the man bought?", "isCorrect": false}, {"label": "B", "text": "Did the man buy the newspaper?", "isCorrect": true}, {"label": "C", "text": "Who bought the newspaper?", "isCorrect": false}, {"label": "D", "text": "What did the man buy?", "isCorrect": false}]'::jsonb, 'B', 'The stress on BOUGHT signals the verb is being contrasted/confirmed, so the matching question should query the verb while keeping subject (''the man'') and object (''the newspaper'') unchanged.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0234', 'Use of English', 'Idiomatic expressions', 'Figures of Speech', NULL, '[{"weight": 1, "conceptId": "lwt4xp"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Worth'' relates to general value, not the specific idiom about showing courage/character.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "''Position'' refers to role/rank, unrelated to demonstrating courage.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "''Skill'' is close but ''mettle'' specifically means courage/spirit under pressure, not competence.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

The match gave the team a chance to show their ........?', '[{"label": "A", "text": "worth", "isCorrect": false}, {"label": "B", "text": "position", "isCorrect": false}, {"label": "C", "text": "skill", "isCorrect": false}, {"label": "D", "text": "mettle", "isCorrect": true}]'::jsonb, 'D', '''To show one''s mettle'' is a fixed idiom meaning to demonstrate courage and character under pressure — exactly what a competitive match provides an opportunity to do.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0235', 'Use of English', 'Comprehension', 'Cloze/Gap-fill in Context', NULL, '[{"weight": 1, "conceptId": "hbrpoi"}]'::jsonb, '{}', 2, 'application', 60, 'high', 'none', '[{"option": "A", "explanation": "''Deduction'' describes a type of reasoning, not the outcome of a well-tested hypothesis.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "''Notion'' is far too vague/informal for a scientifically validated hypothesis.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Thesis'' repeats an earlier stage of the passage''s own sequence (hypothesis→thesis-like idea) rather than the final validated status.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'The passage below has gaps numbered 11 to 20. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.

It is the business of the scientist to accumulate knowledge about the universe and all that is in it and to find if he is able, common

……11…..[A. experiment B. instruments C. approaches D. factors]

which underlie and account for the facts that he knows. He chooses when he can, the method of the controlled

…….12…..[A. respondent B. experiment C. system D. data]

. If he wants to find out the effect of light on growing plants, he takes many plants, as alike as possible. Some he stands in the sun, some in the shade, some in the dark, all the time keeping all other

.....13.....[A. studies B. procedures C. objects D. conditions]

(temperature, moisture, nourishments) the same. In this way, by keeping other variables

……..14……[A. constant B. good C. dark D. natural]

and by varying the light only, the effect of light on plants can be clearly seen. This

…….15…..[A. research B. method C. tool D. rationale]

of using ‘controls’ can be applied to a variety of situations and can be used to find the answers to questions as widely different as ‘must moisture be present if

…….16….[A. an alloy B. gold C. bar D. iron]

is to rust?’ and which variety of beans give the greatest yield in one

……17…..[A. climate B. period C. season D. weather]?

In the course of his

……18…..[A. finding B. queries C. experiment D. inquiries]

, the scientist may find what he thinks is one common explanation for an increasing number of facts the explanation, if it seems consistently to fit the various facts, is called

…….19……[A. an antithesis B. a principle C. a thesis D. a hypothesis]

. If this continues to stand the test of numerous experiments and remains unshaken, it becomes a

……20…..[A. deduction B. law C. notion D. thesis].

In question number 20 above, choose the best option from letters A-D that best completes the gap.', '[{"label": "A", "text": "deduction", "isCorrect": false}, {"label": "B", "text": "law", "isCorrect": true}, {"label": "C", "text": "notion", "isCorrect": false}, {"label": "D", "text": "thesis", "isCorrect": false}]'::jsonb, 'B', 'A hypothesis that survives repeated testing without being disproved becomes a scientific ''law''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0236', 'Use of English', 'Vowels', 'Vowel Sounds', NULL, '[{"weight": 1, "conceptId": "namskj"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Does'' shares /ʌ/ with flood and son despite its different spelling.", "misconceptionId": "overgeneralized_rule"}, {"option": "B", "explanation": "''Flood'' also shares /ʌ/ with the other two words.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "''Son'' shares /ʌ/ as well — all three are the same sound group.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option that has a different vowel sound from the others?', '[{"label": "A", "text": "does", "isCorrect": false}, {"label": "B", "text": "flood", "isCorrect": false}, {"label": "C", "text": "goes", "isCorrect": true}, {"label": "D", "text": "son", "isCorrect": false}]'::jsonb, 'C', '''Does'', ''flood'' and ''son'' all share the short vowel sound /ʌ/. ''Goes'' has the different diphthong /əʊ/.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0237', 'Use of English', 'Comprehension', 'Cloze/Gap-fill in Context', NULL, '[{"weight": 1, "conceptId": "hbrpoi"}]'::jsonb, '{}', 2, 'application', 60, 'high', 'none', '[{"option": "A", "explanation": "''Findings'' are the results of inquiry, not the process ''in the course of'' which the discovery happens.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "''Queries'' (questions) doesn''t fit ''in the course of his ___'' as naturally as the ongoing process of investigation.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "''Experiment'' (singular) was already used earlier in the passage for a different gap; repeating it here doesn''t fit the broader, ongoing process implied.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'The passage below has gaps numbered 11 to 20. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.

It is the business of the scientist to accumulate knowledge about the universe and all that is in it and to find if he is able, common

……11…..[A. experiment B. instruments C. approaches D. factors]

which underlie and account for the facts that he knows. He chooses when he can, the method of the controlled

…….12…..[A. respondent B. experiment C. system D. data]

. If he wants to find out the effect of light on growing plants, he takes many plants, as alike as possible. Some he stands in the sun, some in the shade, some in the dark, all the time keeping all other

.....13.....[A. studies B. procedures C. objects D. conditions]

(temperature, moisture, nourishments) the same. In this way, by keeping other variables

……..14……[A. constant B. good C. dark D. natural]

and by varying the light only, the effect of light on plants can be clearly seen. This

…….15…..[A. research B. method C. tool D. rationale]

of using ‘controls’ can be applied to a variety of situations and can be used to find the answers to questions as widely different as ‘must moisture be present if

…….16….[A. an alloy B. gold C. bar D. iron]

is to rust?’ and which variety of beans give the greatest yield in one

……17…..[A. climate B. period C. season D. weather]?

In the course of his

……18…..[A. finding B. queries C. experiment D. inquiries]

, the scientist may find what he thinks is one common explanation for an increasing number of facts the explanation, if it seems consistently to fit the various facts, is called

…….19……[A. an antithesis B. a principle C. a thesis D. a hypothesis]

. If this continues to stand the test of numerous experiments and remains unshaken, it becomes a

……20…..[A. deduction B. law C. notion D. thesis].

In question number 18 above, choose the best option from letters A-D that best completes the gap.', '[{"label": "A", "text": "findings", "isCorrect": false}, {"label": "B", "text": "queries", "isCorrect": false}, {"label": "C", "text": "experiment", "isCorrect": false}, {"label": "D", "text": "inquiries", "isCorrect": true}]'::jsonb, 'D', '''In the course of his inquiries'' fits the passage''s description of the scientist''s ongoing investigative process leading to a hypothesis.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0238', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 3, 'recall', 60, 'low', 'none', '[{"option": "B", "explanation": "''Deserving'' implies merit, unrelated to the cost of winning.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "''Easy victory'' is nearly the opposite of Pyrrhic, which implies a hard-won, costly win.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "A Pyrrhic victory is still a decisive win, just a costly one — ''indecisive'' is the wrong dimension.", "misconceptionId": "guessed_no_reasoning"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option nearest in meaning to the underlined word(s).

His success may be described as a

Pyrrhic

victory?', '[{"label": "A", "text": "a very costly victory", "isCorrect": true}, {"label": "B", "text": "a deserving victory", "isCorrect": false}, {"label": "C", "text": "an easy victory", "isCorrect": false}, {"label": "D", "text": "indecisive", "isCorrect": false}]'::jsonb, 'A', 'A ''Pyrrhic victory'' is one won at such great cost that it is almost as bad as a defeat; ''a very costly victory'' is the nearest match.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0239', 'Use of English', 'Vocabulary', 'Contextual Word Pairs', NULL, '[{"weight": 1, "conceptId": "nvgfyg"}]'::jsonb, '{}', 3, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Pairs a positive mood (''successful'') with members leaving, an inconsistent, illogical combination.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Cheerful'' is the wrong mood — losing members to other parties should look bad for this party, not good.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "Gets the mood right (''cheerless'') but the wrong direction — ''from other parties'' would mean gaining members, not losing them.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

As election day draws near, the party looks ...... because many of its members have....... other parties?', '[{"label": "A", "text": "successful / decleared for", "isCorrect": false}, {"label": "B", "text": "cheerless / cross-carpeted to", "isCorrect": true}, {"label": "C", "text": "cheerful / moved to", "isCorrect": false}, {"label": "D", "text": "cheerless / cross-carpeted from", "isCorrect": false}]'::jsonb, 'B', 'If members are defecting TO other parties, the party they''re leaving should look bad (''cheerless''), which requires ''cross-carpeted TO'' (leaving this party for others), not ''from''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0240', 'Use of English', 'Vocabulary', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "wwqc38"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Absurd'' is a plausible near-synonym but a different shade of meaning (illogical, rather than simply strange/foreign).", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "''Bizarre'' is also a plausible near-synonym, close in meaning but not the intended precise word.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Fantastic'' carries a positive connotation (amazing), inconsistent with the frustrated tone of the sentence.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

Musa has lived here for five years but he does not seem able to get over the enormously........ and elaborate rules that govern the society?', '[{"label": "A", "text": "adsurd", "isCorrect": false}, {"label": "B", "text": "bizarre", "isCorrect": false}, {"label": "C", "text": "fantastic", "isCorrect": false}, {"label": "D", "text": "outlandish", "isCorrect": true}]'::jsonb, 'D', 'The context (''enormously ___ and elaborate rules'') needs a word meaning strange/unusual with a negative, frustrated tone; ''outlandish'' fits precisely.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0241', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "B", "explanation": "''Disoriented'' (confused) is an unrelated quality, not the opposite of being unconquerable.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Unruly'' (hard to control/disorderly) is a different dimension from being conquerable.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "''Unconquerable'' is a direct synonym of indomitable, not its opposite.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

The athlete has unexpectedly become

indomitable

?', '[{"label": "A", "text": "easily defeated", "isCorrect": true}, {"label": "B", "text": "disoriented", "isCorrect": false}, {"label": "C", "text": "unruly", "isCorrect": false}, {"label": "D", "text": "unconquerable", "isCorrect": false}]'::jsonb, 'A', '''Indomitable'' means unable to be defeated/subdued; its opposite is ''easily defeated''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0242', 'Use of English', 'Comprehension', 'Comprehension and Summary', NULL, '[{"weight": 1, "conceptId": "3r5lb7"}]'::jsonb, '{}', 2, 'application', 60, 'high', 'none', '[{"option": "B", "explanation": "Gets the style right (impersonal) but the wrong valence — the passage says it usually is NOT dull.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Wrongly identifies the style as personal, when the passage explicitly says it is impersonal.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "Wrong on both counts — wrong style and wrong valence.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Recgnizing the need for objectivity in their work, the early report writers to develop a writing style which convey this attitude. They reasoned that the source of the subjective quality in a report is the human being.  And they reasoned that objectivity is best attained by emphasizing the factual material of a report rather 5than the personalities involved. So they worked to remove the human being from their writing. Impersonal writing style was the result. By impersonal writing is meant writing in the third person-without I’s, we’s or you’s.

In recent years, impersonal writing has been strenuously questioned by many writers. These writers point out that personal writing is more forceful and direct than is impersonal writing. They contend that writing which brings both reader and writer into the picture is more like conversation and therefore more interesting. And the answer to the point on objectivity when written in personal style as when in impersonal style. Frequently, they counter with the argument that impersonal writing leads to an overuse of passive voice and a generally dull writing style. This last argument however lacks substances. Impersonal writing can and should be interesting. Any dullness it may have is wholly the fault of the writer. As proof, one has only to look at the lovely styles used by the writers for newspapers, news magazines and journals. Most of this writing is impersonal and usually it is not dull.

As in most cases of controversy, there is some merit to the arguments on both sides. There are situations in which personal writing is best. There are situations in which impersonal writing is best. And there are situations in which either style is appropriate. The writer must decide at the outset of his work which style is best for his own situation.

Her decision should be based on the circumstances of each report situation. First, he should consider the expectations or desires of those for whom he is preparing the report. More than likely he will find a preference for impersonal style for like most human beings; businessman has been slow to break tradition. Next, the writer should consider the formality of the report situation. If the situation is informal, as when the report is really a personal communication of information between business associates, personal writing is appropriate. But if the situation is formal, as is case with most reports, the conventional impersonal style is best.

According to the passage, most of the writing in newspaper, news magazines and journals is', '[{"label": "A", "text": "impersonal and interesting", "isCorrect": true}, {"label": "B", "text": "impersonal and uninteresting", "isCorrect": false}, {"label": "C", "text": "personal and interesting", "isCorrect": false}, {"label": "D", "text": "personal and uninteresting", "isCorrect": false}]'::jsonb, 'A', 'The passage states directly: ''Most of this writing is impersonal and usually it is not dull'' — i.e. impersonal AND interesting.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0243', 'Use of English', 'Grammatical usage', 'Concord (Subject-Verb Agreement)', NULL, '[{"weight": 1, "conceptId": "59ii9v"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "B", "explanation": "Has the right plural noun ''analyses'' but the wrong verb form ''attract'' instead of the required participle ''attracted''.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Uses the singular ''analysis'' with the plural demonstrative ''These'', and the wrong verb form ''attract''.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "Uses the singular ''analysis'' with ''These'', which requires a plural noun.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

These ........ must have ........ the World Bank officials.', '[{"label": "A", "text": "analyses / attracted", "isCorrect": true}, {"label": "B", "text": "analyses / attract", "isCorrect": false}, {"label": "C", "text": "analysis / attract", "isCorrect": false}, {"label": "D", "text": "analysis / attracted", "isCorrect": false}]'::jsonb, 'A', '''These'' requires the plural noun ''analyses'' (not singular ''analysis''), and ''must have ___'' requires the past participle ''attracted'' (perfect construction), not the bare form ''attract''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0244', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Fidgety'' is a synonym of restive (restless), not its opposite.", "misconceptionId": "misunderstood_terminology"}, {"option": "B", "explanation": "''Disorderly'' is also close in meaning to restive (unruly), not its opposite.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Mutinous'' (rebellious) is a synonym of restive, not its opposite.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

The workers suddenly became

restive

?', '[{"label": "A", "text": "fidgety", "isCorrect": false}, {"label": "B", "text": "disorderly", "isCorrect": false}, {"label": "C", "text": "submissive", "isCorrect": true}, {"label": "D", "text": "mutinous", "isCorrect": false}]'::jsonb, 'C', '''Restive'' means restless and resistant to control; its direct opposite is ''submissive'' (easily controlled).', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0245', 'Use of English', 'Stress', 'Word Stress', NULL, '[{"weight": 1, "conceptId": "stfgmb"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "B", "explanation": "''Commute'' is stressed on the second syllable (com-MUTE), the same pattern as the other two.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "''Intend'' is stressed on the second syllable (in-TEND) too.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "''Import'' as a verb is stressed on the second syllable (im-PORT); only as a noun would it shift to the first syllable.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Identify the word that has the stress on the first syllable.', '[{"label": "A", "text": "practice", "isCorrect": true}, {"label": "B", "text": "commute", "isCorrect": false}, {"label": "C", "text": "intend", "isCorrect": false}, {"label": "D", "text": "import (verb)", "isCorrect": false}]'::jsonb, 'A', '''Commute'', ''intend'' and ''import'' (as a verb) are all stressed on the second syllable. ''Practice'' is stressed on the first syllable, the odd one out.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0246', 'Use of English', 'Stress', 'Emphatic Stress', NULL, '[{"weight": 1, "conceptId": "odd0o9"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Wrongly changes ''before'' to ''after'', altering the meaning.", "misconceptionId": "misunderstood_terminology"}, {"option": "B", "explanation": "Replaces the stressed word ''only'' with ''exactly'', a different word with a different nuance.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Changes the subject to ''you'' and the verb to ''walk'' instead of preserving ''he'' and ''travel''.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'The word in capital letters has the emphatic stress. Choose the option that best fits the expression in the sentence.

He travelled ONLY 20 kilometres before his car stopped.', '[{"label": "A", "text": "Did he travel only 20 kilometres after his car stopped?", "isCorrect": false}, {"label": "B", "text": "Did he travel exactly 20 kilometres before his car stopped?", "isCorrect": false}, {"label": "C", "text": "Did you walk only 20 kilometres before the vehicle stopped?", "isCorrect": false}, {"label": "D", "text": "Did he travel only 20 kilometres before his car stopped?", "isCorrect": true}]'::jsonb, 'D', 'The stressed word ONLY must be preserved exactly, along with the unchanged subject ''he'', verb ''travel'', and ''before his car stopped''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0247', 'Use of English', 'Comprehension', 'Cloze/Gap-fill in Context', NULL, '[{"weight": 1, "conceptId": "hbrpoi"}]'::jsonb, '{}', 2, 'application', 60, 'high', 'none', '[{"option": "A", "explanation": "''Experiment'' doesn''t fit — the sentence is about finding common underlying elements, not a single experiment.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "''Instruments'' refers to physical tools, unrelated to abstract underlying causes.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "''Approaches'' describes methods, not the underlying elements the sentence describes.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'The passage below has gaps numbered 11 to 20. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.

It is the business of the scientist to accumulate knowledge about the universe and all that is in it and to find if he is able, common

……11…..[A. experiment B. instruments C. approaches D. factors]

which underlie and account for the facts that he knows. He chooses when he can, the method of the controlled

…….12…..[A. respondent B. experiment C. system D. data]

. If he wants to find out the effect of light on growing plants, he takes many plants, as alike as possible. Some he stands in the sun, some in the shade, some in the dark, all the time keeping all other

.....13.....[A. studies B. procedures C. objects D. conditions]

(temperature, moisture, nourishments) the same. In this way, by keeping other variables

……..14……[A. constant B. good C. dark D. natural]

and by varying the light only, the effect of light on plants can be clearly seen. This

…….15…..[A. research B. method C. tool D. rationale]

of using ‘controls’ can be applied to a variety of situations and can be used to find the answers to questions as widely different as ‘must moisture be present if

…….16….[A. an alloy B. gold C. bar D. iron]

is to rust?’ and which variety of beans give the greatest yield in one

……17…..[A. climate B. period C. season D. weather]?

In the course of his

……18…..[A. finding B. queries C. experiment D. inquiries]

, the scientist may find what he thinks is one common explanation for an increasing number of facts the explanation, if it seems consistently to fit the various facts, is called

…….19……[A. an antithesis B. a principle C. a thesis D. a hypothesis]

. If this continues to stand the test of numerous experiments and remains unshaken, it becomes a

……20…..[A. deduction B. law C. notion D. thesis].

In question number 11 above, choose the best option from letters A-D that best completes the gap.', '[{"label": "A", "text": "experiment", "isCorrect": false}, {"label": "B", "text": "instruments", "isCorrect": false}, {"label": "C", "text": "approaches", "isCorrect": false}, {"label": "D", "text": "factors", "isCorrect": true}]'::jsonb, 'D', '''Common factors which underlie and account for the facts'' is the natural reading — the scientist seeks the common underlying factors, not a single experiment or set of instruments.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0248', 'Use of English', 'Vocabulary', 'Contextual Word Pairs', NULL, '[{"weight": 1, "conceptId": "nvgfyg"}]'::jsonb, '{}', 1, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "Anxiety is not specifically associated with amnesia (memory loss).", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Arm pain is a physical symptom unrelated to memory.", "misconceptionId": "guessed_no_reasoning"}, {"option": "D", "explanation": "Malaria is an unrelated illness, not connected to memory loss.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Fill each gap with the most appropriate option from the lists provided.

Ali has been cured of his amnesia, he no longer suffers from ...... ?', '[{"label": "A", "text": "rounds of anxeity", "isCorrect": false}, {"label": "B", "text": "memory lapses", "isCorrect": true}, {"label": "C", "text": "pains in his arms", "isCorrect": false}, {"label": "D", "text": "bouts of malaria", "isCorrect": false}]'::jsonb, 'B', 'Since amnesia is memory loss, being ''cured of amnesia'' means no longer suffering from memory-related problems, i.e. ''memory lapses''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0249', 'Use of English', 'Comprehension', 'Comprehension and Summary', NULL, '[{"weight": 1, "conceptId": "3r5lb7"}]'::jsonb, '{}', 3, 'application', 60, 'high', 'none', '[{"option": "A", "explanation": "The passage says the NLC merely ''threatened'' to act, not that it succeeded in preventing deregulation.", "misconceptionId": "guessed_no_reasoning"}, {"option": "B", "explanation": "Contradicts the passage''s broader, optimistic claim that competition benefits consumers generally, not just a few.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "Overstates the passage''s claim — it never says a better life is strictly ''conditional upon'' deregulation, only that deregulation should help.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Those who have been following the argument for and against the deregulation of the oil industry in Nigeria may have got the impression that deregulation connotes lack of control or indifference on the part of the government. But there is nothing so far from official quarters to suggest that deregulation will cause the government to relinquish its control of the oil industry because the absence of direct control does not mean that it will surrender all its rights to the entrepreneurs who may want to participate in the industry. Yet the opposition expressed so far against stems from the fear that the government would leave Nigerians at the mercy of a heartless cartel who would command the heights of the oil industry and cause pump price of fuel to rise above the means of most Nigerians.

`As a result of such fears, many Nigerians have become resentful of deregulation and in fact the Nigeria Labour Congress  (NLC) has threatened to ‘deregulate’ the government if it should go ahead with the deregulation plan. But Nigerians have not fared any better with the economy totally in government control. Until recently, the most important sectors of the economy were in the hands of the government. Today, the deregulation of some of these sectors has broken its monopoly and introduced healthy competition to make a little easier for Nigerians. A good example is the breaking of the stifling monopoly of Nigeria Airways. Today, the traveller is king at the domestic airports as opposed to the struggle that air travels used to be under Nigeria Airways monopoly. Before, it was almost easier for a camel to pass through the eye of a needle than for travellers to board a plane.

Following from this, the apostles of deregulation rightly heap all the blame for the problems associated with petroleum products distribution in this country squarely on the government, which owns all the refineries and which sells fuel to local consumers through its agency, the Nigerian National Petroleum Corporation (NNPC). In the same way, the government argues that if the current NNPC monopoly were broken with the introduction of entrepreneurs to the refining and sale of petroleum products in the country, the Nigerian people would be all the better for it. It stands to reason that once the government continues to fix maximum prices would be all the better for it. It stands to reason that once the government continues to fix maximum prices for petroleum products in this country, the deregulation of the oil sector should bring some relief to the people by ensuring that wastage, corruption and inefficiency are reduced to the minimum. Consumers will also have the last laugh because competition will result in the availability of the products at reasonable prices. This appears to be the sense in deregulation.

Which of the following statements is true according to the passage?', '[{"label": "A", "text": "the nigerian labour congress has been able to prevent the government from deregulating the economy", "isCorrect": false}, {"label": "B", "text": "the introduction of entrepreneurs to the oil industry wil make life easy only for a few nigerians", "isCorrect": false}, {"label": "C", "text": "competition resulting from deregulation should make petroleum products available to nigerians at reasonable prices", "isCorrect": true}, {"label": "D", "text": "a better life for all nigerians is conditional upon the deregulation of the economy.", "isCorrect": false}]'::jsonb, 'C', 'The passage states competition will result in products being ''available at reasonable prices'' for consumers — the measured, textually-supported conclusion.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0250', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "Rude describes bad manners generally but misses the specific sense of belittling someone''s reputation that ''disparaging'' carries.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Parochial means narrow-minded or provincial, an unrelated meaning a student might guess from surface familiarity with the word.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "Cynical describes a distrustful attitude, not the act of belittling someone in speech, so it is a near-miss based on general negative tone.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2002, 'JAMB', '{}', 'Choose the option nearest in meaning to the underlined word(s).

The manager made

disparaging

remarks about the retiring officer?', '[{"label": "A", "text": "rude", "isCorrect": false}, {"label": "B", "text": "derogatory", "isCorrect": true}, {"label": "C", "text": "parochial", "isCorrect": false}, {"label": "D", "text": "cynical", "isCorrect": false}]'::jsonb, 'B', '''Disparaging'' means belittling or critical in a scornful way; ''derogatory'' captures this negative, belittling tone precisely.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb);