insert into kairo.concepts (id, name, subject, topic, subtopic, difficulty_weight, dependency_ids, question_pool_ids) values
($q$fb792s$q$, $q$Avogadro's Law$q$, $q$Chemistry$q$, $q$Nature of Matter$q$, $q$Avogadro's Law$q$, 1.1, '{}', '{}'),
($q$e5q9c8$q$, $q$Mass-Mass Stoichiometry$q$, $q$Chemistry$q$, $q$Chemical Combination$q$, $q$Mass-Mass Stoichiometry$q$, 1.2, '{}', '{}'),
($q$f0dj68$q$, $q$Metals vs Non-Metals — Periodic Position$q$, $q$Chemistry$q$, $q$Atomic Structure & Bonding$q$, $q$Metals vs Non-Metals — Periodic Position$q$, 1.1, '{}', '{}'),
($q$gzi1bc$q$, $q$Isotopic Abundance Calculations$q$, $q$Chemistry$q$, $q$Atomic Structure & Bonding$q$, $q$Isotopic Abundance Calculations$q$, 1.3, '{}', '{}'),
($q$v89sra$q$, $q$Kinetic Theory — Temperature and Energy$q$, $q$Chemistry$q$, $q$Kinetic Theory & Gas Laws$q$, $q$Kinetic Theory — Temperature and Energy$q$, 1.0, '{}', '{}'),
($q$nucy3t$q$, $q$History of Atomic Theory$q$, $q$Chemistry$q$, $q$Atomic Structure & Bonding$q$, $q$History of Atomic Theory$q$, 1.1, '{}', '{}'),
($q$f4y1pg$q$, $q$Subatomic Particles and Ion Charge$q$, $q$Chemistry$q$, $q$Atomic Structure & Bonding$q$, $q$Subatomic Particles and Ion Charge$q$, 1.2, '{}', '{}'),
($q$m4b114$q$, $q$Vapour Density and Molar Mass$q$, $q$Chemistry$q$, $q$Chemical Combination$q$, $q$Vapour Density and Molar Mass$q$, 1.3, '{}', '{}'),
($q$u8nzau$q$, $q$Vehicle Emissions and Heavy Metal Pollution$q$, $q$Chemistry$q$, $q$Environmental Pollution$q$, $q$Vehicle Emissions and Heavy Metal Pollution$q$, 1.1, '{}', '{}'),
($q$vejcxc$q$, $q$Reactivity and Storage of Elements$q$, $q$Chemistry$q$, $q$Non-Metals & Their Compounds$q$, $q$Reactivity and Storage of Elements$q$, 1.1, '{}', '{}'),
($q$syb7rg$q$, $q$Deliquescent and Hygroscopic Substances$q$, $q$Chemistry$q$, $q$Nature of Matter$q$, $q$Deliquescent and Hygroscopic Substances$q$, 1.1, '{}', '{}'),
($q$txr2h3$q$, $q$Oxygen Content of Air — Pyrogallol Absorption$q$, $q$Chemistry$q$, $q$Air and Water$q$, $q$Oxygen Content of Air — Pyrogallol Absorption$q$, 1.3, '{}', '{}'),
($q$s55vck$q$, $q$Entropy and Disorder$q$, $q$Chemistry$q$, $q$Energy Changes$q$, $q$Entropy and Disorder$q$, 1.3, '{}', '{}'),
($q$kzcd9t$q$, $q$Le Chatelier's Principle — Pressure & Temperature Effects$q$, $q$Chemistry$q$, $q$Chemical Equilibrium$q$, $q$Le Chatelier's Principle — Pressure & Temperature Effects$q$, 1.4, '{}', '{}'),
($q$kwcqvs$q$, $q$Conductivity of Electrolytes$q$, $q$Chemistry$q$, $q$Electrolysis$q$, $q$Conductivity of Electrolytes$q$, 1.1, '{}', '{}'),
($q$kshq1j$q$, $q$Interpreting Enthalpy Sign and Magnitude$q$, $q$Chemistry$q$, $q$Energy Changes$q$, $q$Interpreting Enthalpy Sign and Magnitude$q$, 1.1, '{}', '{}'),
($q$ocems4$q$, $q$Rate of Reaction — Temperature and Collision Theory$q$, $q$Chemistry$q$, $q$Rates of Reaction$q$, $q$Rate of Reaction — Temperature and Collision Theory$q$, 1.2, '{}', '{}'),
($q$hwsbxw$q$, $q$Basicity of Acids$q$, $q$Chemistry$q$, $q$Acids, Bases & Salts$q$, $q$Basicity of Acids$q$, 1.1, '{}', '{}'),
($q$lbnthq$q$, $q$Hybridization$q$, $q$Chemistry$q$, $q$Atomic Structure & Bonding$q$, $q$Hybridization$q$, 1.2, '{}', '{}'),
($q$a7c5wm$q$, $q$Proteins and Hydrolysis$q$, $q$Chemistry$q$, $q$Organic Chemistry$q$, $q$Proteins and Hydrolysis$q$, 1.1, '{}', '{}'),
($q$it0oem$q$, $q$Hydrogenation of Aromatic Compounds$q$, $q$Chemistry$q$, $q$Organic Chemistry$q$, $q$Hydrogenation of Aromatic Compounds$q$, 1.2, '{}', '{}'),
($q$bb5rj9$q$, $q$Reactions of Alkenes — Polymerization$q$, $q$Chemistry$q$, $q$Organic Chemistry$q$, $q$Reactions of Alkenes — Polymerization$q$, 1.2, '{}', '{}'),
($q$gbh920$q$, $q$Chlorine Water and Photodecomposition$q$, $q$Chemistry$q$, $q$Non-Metals & Their Compounds$q$, $q$Chlorine Water and Photodecomposition$q$, 1.2, '{}', '{}'),
($q$so95ev$q$, $q$Dehydrating Agents — Concentrated Sulphuric Acid$q$, $q$Chemistry$q$, $q$Organic Chemistry$q$, $q$Dehydrating Agents — Concentrated Sulphuric Acid$q$, 1.2, '{}', '{}'),
($q$bo2kcr$q$, $q$Functional Group General Formulas$q$, $q$Chemistry$q$, $q$Organic Chemistry$q$, $q$Functional Group General Formulas$q$, 1.0, '{}', '{}'),
($q$ewcz01$q$, $q$Gas Collection Methods$q$, $q$Chemistry$q$, $q$Non-Metals & Their Compounds$q$, $q$Gas Collection Methods$q$, 1.1, '{}', '{}'),
($q$kswl2e$q$, $q$Polyhydric Alcohols$q$, $q$Chemistry$q$, $q$Organic Chemistry$q$, $q$Polyhydric Alcohols$q$, 1.0, '{}', '{}'),
($q$hse3ru$q$, $q$Extraction of Iron — Impurities and Slag$q$, $q$Chemistry$q$, $q$Metals & Their Compounds$q$, $q$Extraction of Iron — Impurities and Slag$q$, 1.2, '{}', '{}');
