insert into kairo.concepts (id, name, subject, topic, subtopic, difficulty_weight, dependency_ids, question_pool_ids) values
($q$cq46o7$q$, $q$Conjugate Acid-Base Pairs$q$, $q$Chemistry$q$, $q$Acids, Bases & Salts$q$, $q$Conjugate Acid-Base Pairs$q$, 1.2, '{}', '{}'),
($q$8ocrzy$q$, $q$pH and pOH Calculations$q$, $q$Chemistry$q$, $q$Acids, Bases & Salts$q$, $q$pH and pOH Calculations$q$, 1.2, '{}', '{}'),
($q$2oceg6$q$, $q$Periodic Trends$q$, $q$Chemistry$q$, $q$Atomic Structure & Bonding$q$, $q$Periodic Trends$q$, 1.1, '{}', '{}'),
($q$ot0voy$q$, $q$Radioactivity and Half-Life$q$, $q$Chemistry$q$, $q$Atomic Structure & Bonding$q$, $q$Radioactivity and Half-Life$q$, 1.1, '{}', '{}'),
($q$25qyuy$q$, $q$Coordinate Bonding — Ligands$q$, $q$Chemistry$q$, $q$Atomic Structure & Bonding$q$, $q$Coordinate Bonding — Ligands$q$, 1.3, '{}', '{}'),
($q$z2f3rl$q$, $q$Metallic Bonding vs. Compound Formation$q$, $q$Chemistry$q$, $q$Atomic Structure & Bonding$q$, $q$Metallic Bonding vs. Compound Formation$q$, 1.2, '{}', '{}'),
($q$kt2ylw$q$, $q$Syngas$q$, $q$Chemistry$q$, $q$Chemistry & Industry$q$, $q$Syngas$q$, 1.1, '{}', '{}'),
($q$yklr2g$q$, $q$Uses of Chlorinated Solvents$q$, $q$Chemistry$q$, $q$Chemistry & Industry$q$, $q$Uses of Chlorinated Solvents$q$, 1.1, '{}', '{}'),
($q$cbvosp$q$, $q$Faraday's Laws$q$, $q$Chemistry$q$, $q$Electrolysis$q$, $q$Faraday's Laws$q$, 1.2, '{}', '{}'),
($q$6in5n9$q$, $q$Heat of Combustion Calculations$q$, $q$Chemistry$q$, $q$Energy Changes$q$, $q$Heat of Combustion Calculations$q$, 1.3, '{}', '{}'),
($q$jiwfyk$q$, $q$Greenhouse Gases$q$, $q$Chemistry$q$, $q$Environmental Pollution$q$, $q$Greenhouse Gases$q$, 1.1, '{}', '{}'),
($q$4w8vof$q$, $q$Natural vs. Synthetic Pollutants$q$, $q$Chemistry$q$, $q$Environmental Pollution$q$, $q$Natural vs. Synthetic Pollutants$q$, 1.2, '{}', '{}'),
($q$3b7g4n$q$, $q$Ores of Metals$q$, $q$Chemistry$q$, $q$Metals & Their Compounds$q$, $q$Ores of Metals$q$, 1.0, '{}', '{}'),
($q$5q74k0$q$, $q$Reactivity and Corrosion Resistance$q$, $q$Chemistry$q$, $q$Metals & Their Compounds$q$, $q$Reactivity and Corrosion Resistance$q$, 1.1, '{}', '{}'),
($q$shtbq8$q$, $q$Equilibrium Constant Expressions$q$, $q$Chemistry$q$, $q$Chemical Equilibrium$q$, $q$Equilibrium Constant Expressions$q$, 1.2, '{}', '{}'),
($q$b3vqsm$q$, $q$Rubber Chemistry$q$, $q$Chemistry$q$, $q$Organic Chemistry$q$, $q$Rubber Chemistry$q$, 1.1, '{}', '{}'),
($q$kflkb0$q$, $q$Extraction of a Water Molecule Between Alcohols$q$, $q$Chemistry$q$, $q$Organic Chemistry$q$, $q$Extraction of a Water Molecule Between Alcohols$q$, 1.4, '{}', '{}'),
($q$kmmznm$q$, $q$Functional Group Identification — Esters$q$, $q$Chemistry$q$, $q$Organic Chemistry$q$, $q$Functional Group Identification — Esters$q$, 1.2, '{}', '{}'),
($q$znym3c$q$, $q$Industrial Production of Acetylene$q$, $q$Chemistry$q$, $q$Organic Chemistry$q$, $q$Industrial Production of Acetylene$q$, 1.1, '{}', '{}'),
($q$4f68ue$q$, $q$Oxidation of Alcohols$q$, $q$Chemistry$q$, $q$Organic Chemistry$q$, $q$Oxidation of Alcohols$q$, 1.2, '{}', '{}'),
($q$xd7de2$q$, $q$Tests for Unsaturation$q$, $q$Chemistry$q$, $q$Organic Chemistry$q$, $q$Tests for Unsaturation$q$, 1.1, '{}', '{}'),
($q$1e6r0v$q$, $q$Allotropy$q$, $q$Chemistry$q$, $q$Nature of Matter$q$, $q$Allotropy$q$, 1.1, '{}', '{}'),
($q$5jews9$q$, $q$Adsorption$q$, $q$Chemistry$q$, $q$Nature of Matter$q$, $q$Adsorption$q$, 1.2, '{}', '{}'),
($q$5s3ecx$q$, $q$Composition of Common Compounds$q$, $q$Chemistry$q$, $q$Nature of Matter$q$, $q$Composition of Common Compounds$q$, 1.1, '{}', '{}'),
($q$fch4i1$q$, $q$Dissolved Gases in Drinks$q$, $q$Chemistry$q$, $q$Air and Water$q$, $q$Dissolved Gases in Drinks$q$, 1.0, '{}', '{}'),
($q$beypy2$q$, $q$Water Treatment and Hardness$q$, $q$Chemistry$q$, $q$Air and Water$q$, $q$Water Treatment and Hardness$q$, 1.2, '{}', '{}'),
($q$unbitv$q$, $q$States of Matter — Kinetic Theory$q$, $q$Chemistry$q$, $q$Nature of Matter$q$, $q$States of Matter — Kinetic Theory$q$, 1.0, '{}', '{}'),
($q$d3l5it$q$, $q$Balancing Half-Equations$q$, $q$Chemistry$q$, $q$Oxidation & Reduction$q$, $q$Balancing Half-Equations$q$, 1.3, '{}', '{}'),
($q$mt5suz$q$, $q$Separation Techniques — Selective Solubility$q$, $q$Chemistry$q$, $q$Separation of Mixtures$q$, $q$Separation Techniques — Selective Solubility$q$, 1.3, '{}', '{}'),
($q$eo9w1a$q$, $q$Partial Pressure and Mole Fraction$q$, $q$Chemistry$q$, $q$Kinetic Theory & Gas Laws$q$, $q$Partial Pressure and Mole Fraction$q$, 1.2, '{}', '{}'),
($q$5cybu4$q$, $q$Solubility Product Calculations$q$, $q$Chemistry$q$, $q$Solubility$q$, $q$Solubility Product Calculations$q$, 1.4, '{}', '{}');
