INSERT INTO kairo.questions (id, subject, topic, subtopic, learning_objective, concepts_tested, prerequisite_concepts, difficulty_rating, cognitive_level, estimated_solving_time_sec, reading_load, calculation_load, distractors, skills_assessed, source, year, exam_body, related_question_ids, stem, options, correct_option, explanation, lifecycle_state, empirical_stats) VALUES
('use_of_english_0325', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Expensive'' is closely associated with sumptuous, not its opposite.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "''Desirable'' is a positive quality consistent with sumptuous, not its opposite.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "''Lavish'' is a direct synonym of sumptuous.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

Some people consider the leather upholstery and thick rugs a bit

sumptuous.', '[{"label": "A", "text": "expensive", "isCorrect": false}, {"label": "B", "text": "desirable", "isCorrect": false}, {"label": "C", "text": "lavish", "isCorrect": false}, {"label": "D", "text": "simple", "isCorrect": true}]'::jsonb, 'D', '''Sumptuous'' means luxurious and lavish; its opposite is ''simple''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0326', 'Use of English', 'Appropriate word choice', 'Word Choice in Context', NULL, '[{"weight": 1, "conceptId": "kxwnre"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Concerned reasons'' is not idiomatic English.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "''Plenty'' requires ''of'' before a noun (''plenty of reasons''), so ''for plenty reasons'' is ungrammatical.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "''Myriad of'' without an article is non-standard; the idiomatic forms are ''a myriad of'' or simply ''myriad reasons''.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

I am writing to you for ....... reasons?', '[{"label": "A", "text": "concerned", "isCorrect": false}, {"label": "B", "text": "several", "isCorrect": true}, {"label": "C", "text": "plenty", "isCorrect": false}, {"label": "D", "text": "myriad of", "isCorrect": false}]'::jsonb, 'B', '''Several reasons'' is the natural, grammatical phrase; ''myriad'' would need to be used without ''of'' or with an article (''a myriad of''), and ''plenty'' needs ''of'' before the noun.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0327', 'Use of English', 'Vowels', 'Vowel Sounds', NULL, '[{"weight": 1, "conceptId": "namskj"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Bear'' has the /eə/ diphthong, a different sound.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "''Pear'' also has /eə/, not /ɪə/.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "''Fair'' has /eə/ as well, the same different sound as bear and pear.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that has the same vowel sound as the one represented by the letter(s) underlined.

b

ee

r', '[{"label": "A", "text": "bear", "isCorrect": false}, {"label": "B", "text": "pear", "isCorrect": false}, {"label": "C", "text": "fair", "isCorrect": false}, {"label": "D", "text": "pier", "isCorrect": true}]'::jsonb, 'D', '''Beer'' has the /ɪə/ diphthong. ''Pier'' shares this exact sound (in fact, ''beer'' and ''pier'' rhyme).', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0328', 'Use of English', 'Idiomatic expressions', 'Figures of Speech', NULL, '[{"weight": 1, "conceptId": "lwt4xp"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Step from step'' is not a standard English phrase.", "misconceptionId": "memorized_not_understood"}, {"option": "C", "explanation": "''Steps after steps'' is not the correct fixed idiom.", "misconceptionId": "overgeneralized_rule"}, {"option": "D", "explanation": "''Steps by steps'' incorrectly pluralizes both nouns in the fixed phrase.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

Tsadu always cautions that difficult jobs should be done .......?', '[{"label": "A", "text": "step from step", "isCorrect": false}, {"label": "B", "text": "step by step", "isCorrect": true}, {"label": "C", "text": "steps after steps", "isCorrect": false}, {"label": "D", "text": "steps by steps", "isCorrect": false}]'::jsonb, 'B', '''Step by step'' is the fixed idiom meaning gradually and methodically, fitting how difficult jobs should be approached.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0329', 'Use of English', 'Appropriate word choice', 'Historic/Historical', NULL, '[{"weight": 1, "conceptId": "2ae5n3"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Historical'' means ''relating to history'' generally, not ''significant in history'', so it doesn''t fit an event marking a new beginning.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "''Historicity of the'' is an awkward abstract noun phrase that doesn''t fit grammatically as an adjective before ''event''.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "''History of the'' turns the sentence into an incomplete noun phrase rather than describing the event itself.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

The ...... event marked the beginning of a new life for the entire cabinet?', '[{"label": "A", "text": "historical", "isCorrect": false}, {"label": "B", "text": "historicity of the", "isCorrect": false}, {"label": "C", "text": "historic", "isCorrect": true}, {"label": "D", "text": "history of the", "isCorrect": false}]'::jsonb, 'C', '''Historic'' means significant in history (a historic event), while ''historical'' means merely relating to history in general -- a different meaning needed here.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0330', 'Use of English', 'Vocabulary', 'Spelling', NULL, '[{"weight": 1, "conceptId": "k8pk3y"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Unkept'' is not a recognized English word -- a common confusion with ''unkempt''.", "misconceptionId": "memorized_not_understood"}, {"option": "C", "explanation": "''Unwashed'' specifically means not washed, a narrower and different claim than being untidy.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Uncleaned for'' is an awkward, non-idiomatic construction.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

In spite of Shade''s good looks, her hair is always ...... ?', '[{"label": "A", "text": "unkept", "isCorrect": false}, {"label": "B", "text": "unkempt", "isCorrect": true}, {"label": "C", "text": "unwashed", "isCorrect": false}, {"label": "D", "text": "uncleaned for", "isCorrect": false}]'::jsonb, 'B', '''Unkempt'' is the correct word for untidy hair; ''unkept'' is not a standard English word.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0331', 'Use of English', 'Sentence structure', 'Word Order', NULL, '[{"weight": 1, "conceptId": "mecosf"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Places the material ''wooden'' before the participle ''carved'', reversing the correct order.", "misconceptionId": "overgeneralized_rule"}, {"option": "B", "explanation": "Places the opinion adjective after the material entirely, badly out of order.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "Places the participle ''carved'' before the opinion adjective ''attractive'', reversing the correct order.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

The first prize was ....... tray?', '[{"label": "A", "text": "a carved wooden attractive", "isCorrect": false}, {"label": "B", "text": "a wooden attractive carved", "isCorrect": false}, {"label": "C", "text": "an attractive carved wooden", "isCorrect": true}, {"label": "D", "text": "a carved attractive wooden", "isCorrect": false}]'::jsonb, 'C', 'Standard English adjective order places opinion before participle/shape before material: ''an attractive carved wooden tray''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0332', 'Use of English', 'Grammatical usage', 'Tense', NULL, '[{"weight": 1, "conceptId": "hbp4zb"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "B", "explanation": "''Could return'' expresses past ability/possibility, not a completed prior action.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Should return'' expresses obligation, not what actually happened before the gates closed.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "''Would return'' expresses future-in-the-past intention, not a completed prior action.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

Is it true that Okoro ........ when the gates were closed?', '[{"label": "A", "text": "had returned", "isCorrect": true}, {"label": "B", "text": "could return", "isCorrect": false}, {"label": "C", "text": "should return", "isCorrect": false}, {"label": "D", "text": "would return", "isCorrect": false}]'::jsonb, 'A', 'Okoro''s return happened before another past event (the gates closing), requiring the past perfect: ''had returned''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0333', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Bad'' is vague and doesn''t specifically reverse the unfriendliness of a sour look.", "misconceptionId": "overgeneralized_rule"}, {"option": "B", "explanation": "''Satisfactory'' describes adequacy, not the friendliness dimension being tested.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Sinister'' intensifies the negative meaning rather than opposing it.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

Idris gives me a

sour

look every time I pass by him.', '[{"label": "A", "text": "bad", "isCorrect": false}, {"label": "B", "text": "satisfactory", "isCorrect": false}, {"label": "C", "text": "friendly", "isCorrect": true}, {"label": "D", "text": "sinister", "isCorrect": false}]'::jsonb, 'C', 'A ''sour look'' is an unfriendly expression; its opposite is ''friendly''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0334', 'Use of English', 'Idiomatic expressions', 'Sentence Interpretation (Idiom)', NULL, '[{"weight": 1, "conceptId": "91ez3x"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Desires to assert his will'' is close but frames it as a wish rather than the demonstrated firmness the idiom actually describes.", "misconceptionId": "overgeneralized_rule"}, {"option": "B", "explanation": "''Makes his mark wherever he goes'' is a different idiom about leaving an impression, not asserting firmness in a decision.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "The idiom describes firmness, not oppressing others.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Select the option that best explains the information conveyed in the sentence.

The man puts his foot down whenever he is convinced of his action?', '[{"label": "A", "text": "He desires to assert his will in the situation", "isCorrect": false}, {"label": "B", "text": "He makes his mark whereever he goes", "isCorrect": false}, {"label": "C", "text": "His attitude demonstrates someone who likes to oppress others around him", "isCorrect": false}, {"label": "D", "text": "He demonstrates firmness of character", "isCorrect": true}]'::jsonb, 'D', '''Puts his foot down'' is an idiom meaning to act with firm decisiveness, i.e. he demonstrates firmness of character.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0335', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 2, 'recall', 60, 'medium', 'none', '[{"option": "A", "explanation": "''Creditable'' means praiseworthy, a different quality from being essential.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Respectable'' also concerns reputation, not essentiality.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "''Laudable'' means praiseworthy, again a different quality from being essential.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the

option nearest in meaning

to the word or phrase underlined.

Nigeria has been playing a

vital

role in the political and economic development of Africa.', '[{"label": "A", "text": "creditable", "isCorrect": false}, {"label": "B", "text": "crucial", "isCorrect": true}, {"label": "C", "text": "respectable", "isCorrect": false}, {"label": "D", "text": "laudable", "isCorrect": false}]'::jsonb, 'B', '''Vital'' means essential; ''crucial'' is its nearest match.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0336', 'Use of English', 'Stress', 'Word Stress', NULL, '[{"weight": 1, "conceptId": "stfgmb"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Impound'' is stressed on its second syllable (im-POUND), matching the others.", "misconceptionId": "overgeneralized_rule"}, {"option": "B", "explanation": "''Subject'' as a verb is stressed on its second syllable (sub-JECT).", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Canoe'' is stressed on its second syllable (ca-NOE).", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that has a different stress pattern from the others.', '[{"label": "A", "text": "impound", "isCorrect": false}, {"label": "B", "text": "subject (verb)", "isCorrect": false}, {"label": "C", "text": "canoe", "isCorrect": false}, {"label": "D", "text": "knowledge", "isCorrect": true}]'::jsonb, 'D', '''Impound'', ''subject'' (verb), and ''canoe'' are all stressed on the second syllable. ''Knowledge'' is stressed on the first syllable, the odd one out.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0337', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 2, 'recall', 60, 'medium', 'none', '[{"option": "A", "explanation": "''Inevitable'' means unavoidable, an unrelated meaning.", "misconceptionId": "misunderstood_terminology"}, {"option": "B", "explanation": "''Wonderful'' describes quality, not the inability to express something in words.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "''Unbearable'' means intolerable, a different concept from being indescribable.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option nearest in meaning to the underlined word(s).

The greatness of the creator of the universe is always

inexpressible

to many adherents of certain faiths?', '[{"label": "A", "text": "inevitable", "isCorrect": false}, {"label": "B", "text": "wonderful", "isCorrect": false}, {"label": "C", "text": "unbearable", "isCorrect": false}, {"label": "D", "text": "ineffable", "isCorrect": true}]'::jsonb, 'D', '''Inexpressible'' means unable to be put into words; ''ineffable'' is the precise literary synonym for this.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0338', 'Use of English', 'Grammatical usage', 'Noun Modifiers (Singular Attributive Nouns)', NULL, '[{"weight": 1, "conceptId": "1gp2vz"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Wrongly adds a possessive apostrophe and misspells ''soldiers''.", "misconceptionId": "misunderstood_terminology"}, {"option": "B", "explanation": "''Childish'' means immature, a different word from the noun modifier ''child''.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "Using the plural ''children'' as a modifier before another noun is a common but incorrect overgeneralization from normal plural rules.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

The Secretary-General was shocked at the number of...... ?', '[{"label": "A", "text": "child''s soildiers", "isCorrect": false}, {"label": "B", "text": "childish soldiers", "isCorrect": false}, {"label": "C", "text": "children soldiers", "isCorrect": false}, {"label": "D", "text": "child soldiers", "isCorrect": true}]'::jsonb, 'D', 'A noun used attributively before another noun stays singular: ''child soldiers'' (like ''car parks''), not ''children soldiers''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0339', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 2, 'recall', 60, 'medium', 'none', '[{"option": "B", "explanation": "''Rampant'' implies uncontrolled spread with a stronger negative connotation than the neutral ''common'' here.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "''Ordinary'' addresses unremarkableness, not the frequency/widespread sense ''common'' has in this context.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Cogent'' means convincing, an unrelated meaning.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the

option nearest in meaning

to the word or phrase underlined.

The

common

practice among some media practitioners is to be sensational in their reporting.', '[{"label": "A", "text": "prevalent", "isCorrect": true}, {"label": "B", "text": "rampant", "isCorrect": false}, {"label": "C", "text": "ordinary", "isCorrect": false}, {"label": "D", "text": "cogent", "isCorrect": false}]'::jsonb, 'A', 'Here ''common'' means widespread/frequent, which ''prevalent'' captures precisely, rather than ''ordinary'' (which describes quality, not frequency).', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0340', 'Use of English', 'Synonyms/antonyms', 'Antonyms', NULL, '[{"weight": 1, "conceptId": "v4agon"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Deluded'' means holding false beliefs, an unrelated quality to motivation.", "misconceptionId": "misunderstood_terminology"}, {"option": "B", "explanation": "''Disillusioned'' is close but centers on lost belief/idealism rather than the drained energy that opposes ''motivated'' most directly.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Immature'' is an unrelated quality, not the opposite of being motivated.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option opposite in meaning to the underlined word(s).

It would be difficult to defeat such a

highly motivated

team.', '[{"label": "A", "text": "highly deluded", "isCorrect": false}, {"label": "B", "text": "completely disillusioned", "isCorrect": false}, {"label": "C", "text": "very demoralized", "isCorrect": true}, {"label": "D", "text": "very immature", "isCorrect": false}]'::jsonb, 'C', '''Motivated'' means driven and enthusiastic; its opposite is ''demoralized''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0341', 'Use of English', 'Idiomatic expressions', 'Sentence Interpretation (Idiom)', NULL, '[{"weight": 1, "conceptId": "91ez3x"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "B", "explanation": "This describes exactly what being a ''pawn'' would mean, the opposite of what the sentence states.", "misconceptionId": "confused_similar_concepts"}, {"option": "C", "explanation": "This directly contradicts the ''not'' in the original sentence.", "misconceptionId": "misunderstood_terminology"}, {"option": "D", "explanation": "Nothing in the sentence suggests they enjoyed political games.", "misconceptionId": "guessed_no_reasoning"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Select the option that best explains the information conveyed in the sentence.

The men were not pawns in someone else''s political game.', '[{"label": "A", "text": "The action they executed was their idea", "isCorrect": true}, {"label": "B", "text": "The men used someone else''s plan", "isCorrect": false}, {"label": "C", "text": "They were used by someone''s political game", "isCorrect": false}, {"label": "D", "text": "They loved playing political games", "isCorrect": false}]'::jsonb, 'A', '''Pawns in someone else''s game'' means being used/controlled by others; being told they were NOT pawns means their actions were their own idea.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0342', 'Use of English', 'Grammatical usage', 'Tense & Aspect', NULL, '[{"weight": 1, "conceptId": "h5mkn9"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Using ''will'' in a time clause after ''until'' is a common but incorrect overgeneralization of future-tense marking.", "misconceptionId": "overgeneralized_rule"}, {"option": "B", "explanation": "''Stopped'' (past tense) doesn''t fit a statement about the future.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Has stopped'' is grammatically possible but ''stops'' is the standard simple-present form expected in this construction.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

We won''t leave until it ........ raining?', '[{"label": "A", "text": "will stop", "isCorrect": false}, {"label": "B", "text": "stopped", "isCorrect": false}, {"label": "C", "text": "stops", "isCorrect": true}, {"label": "D", "text": "has stopped", "isCorrect": false}]'::jsonb, 'C', 'Time clauses introduced by ''until'' use the simple present to refer to future time, not ''will'': ''until it stops raining''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0343', 'Use of English', 'Consonants', 'Consonant Sounds', NULL, '[{"weight": 1, "conceptId": "3p5hul"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "B", "explanation": "The ''l'' in ''walk'' is silent.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "The ''l'' in ''psalm'' is silent (as is the ''p'').", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "The ''l'' in ''chalk'' is silent.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that has the same consonant sound as the one represented by the letters underlined.

Fi

l

m?', '[{"label": "A", "text": "salt", "isCorrect": true}, {"label": "B", "text": "walk", "isCorrect": false}, {"label": "C", "text": "Psalm", "isCorrect": false}, {"label": "D", "text": "chalk", "isCorrect": false}]'::jsonb, 'A', 'The underlined ''l'' in ''film'' is pronounced /l/. ''Salt'' also has a pronounced /l/, while ''walk'', ''psalm'', and ''chalk'' all have a silent ''l''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0344', 'Use of English', 'Grammatical usage', 'Prepositional Collocations', NULL, '[{"weight": 1, "conceptId": "cepp3x"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''As regard to'' is not a standard English phrase.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "''In regard of'' uses the wrong preposition; the fixed phrase is ''in regard to'' or ''with regard to''.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Regards'' (plural) is a common but non-standard variant of the fixed singular phrase ''with regard to''.", "misconceptionId": "overgeneralized_rule"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

The Bank Manager assured us that there was nothing to worry about ...... ?', '[{"label": "A", "text": "as regard to the loan", "isCorrect": false}, {"label": "B", "text": "with regard to the loan", "isCorrect": true}, {"label": "C", "text": "in regard of the loan", "isCorrect": false}, {"label": "D", "text": "with regards to the loan", "isCorrect": false}]'::jsonb, 'B', 'The fixed phrase is ''with regard to'' (singular ''regard'', no ''s''), not ''regards'' or other prepositions.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0345', 'Use of English', 'Stress', 'Word Stress', NULL, '[{"weight": 1, "conceptId": "stfgmb"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Stress on the first syllable doesn''t match the word''s actual pronunciation.", "misconceptionId": "memorized_not_understood"}, {"option": "B", "explanation": "Stress on the second syllable is incorrect for this word.", "misconceptionId": "memorized_not_understood"}, {"option": "D", "explanation": "Stress on the final syllable is incorrect; the primary stress falls on ''pru'', not ''dence''.", "misconceptionId": "memorized_not_understood"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the appropriate stress pattern from the options. The syllables are written in capital letters.

jurisprudence?', '[{"label": "A", "text": "jUsprudence", "isCorrect": false}, {"label": "B", "text": "juRIsprudence", "isCorrect": false}, {"label": "C", "text": "jurisPRUdence", "isCorrect": true}, {"label": "D", "text": "jurispruDENCE", "isCorrect": false}]'::jsonb, 'C', '''Jurisprudence'' is stressed on its third syllable: ju-ris-PRU-dence.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0346', 'Use of English', 'Stress', 'Emphatic Stress', NULL, '[{"weight": 1, "conceptId": "odd0o9"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "Changes the verb to ''lose'', altering the meaning rather than just contrasting the stressed subject.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "A ''who'' question doesn''t match the yes/no-confirmation pattern used throughout this question type.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "Queries the object (''what''), not a confirmation involving the stressed subject.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'The word in capital letters has the emphatic stress. Choose the option to which the given sentence relates.

The EAGLES won the match.', '[{"label": "A", "text": "Did the Eagles lose the match?", "isCorrect": false}, {"label": "B", "text": "Who won the match ?", "isCorrect": false}, {"label": "C", "text": "What did the Eagles win?", "isCorrect": false}, {"label": "D", "text": "Did the Eagles win the match?", "isCorrect": true}]'::jsonb, 'D', 'The stress on EAGLES highlights that team specifically as the winner; the matching sentence keeps everything else the same and confirms it with a yes/no question: ''Did the Eagles win the match?''', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0347', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 2, 'recall', 60, 'medium', 'none', '[{"option": "A", "explanation": "''Picturesque'' describes visual charm, not accuracy to reality.", "misconceptionId": "confused_similar_concepts"}, {"option": "B", "explanation": "''Concrete'' means specific/tangible, not the same as lifelike.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "''Lively'' describes energy, not accuracy to reality.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the

option nearest in meaning

to the word or phrase underlined.

Emeka''s painting was so

realistic

that it could almost have been a photograph.', '[{"label": "A", "text": "picturesque", "isCorrect": false}, {"label": "B", "text": "concrete", "isCorrect": false}, {"label": "C", "text": "lively", "isCorrect": false}, {"label": "D", "text": "authentic", "isCorrect": true}]'::jsonb, 'D', 'A ''realistic'' painting looks true to life; among the options, ''authentic'' (genuine, true-to-reality) is the nearest match.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0348', 'Use of English', 'Synonyms/antonyms', 'Synonyms', NULL, '[{"weight": 1, "conceptId": "r0mfcp"}]'::jsonb, '{}', 2, 'recall', 60, 'low', 'none', '[{"option": "A", "explanation": "''Obliviousness'' means being unaware, an unrelated quality to being silent.", "misconceptionId": "misunderstood_terminology"}, {"option": "C", "explanation": "''Sensibility'' means emotional responsiveness, unrelated to silence.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Pervasiveness'' means being widespread, an unrelated quality.", "misconceptionId": "misunderstood_terminology"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the

option nearest in meaning

to the word or phrase underlined.

His

taciturnity

amazed everyone in the court during the legal tussle', '[{"label": "A", "text": "obliviousness", "isCorrect": false}, {"label": "B", "text": "reticence", "isCorrect": true}, {"label": "C", "text": "sensibility", "isCorrect": false}, {"label": "D", "text": "pervasiveness", "isCorrect": false}]'::jsonb, 'B', '''Taciturnity'' means habitual silence or reluctance to speak; ''reticence'' is its precise synonym.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb),
('use_of_english_0349', 'Use of English', 'Grammatical usage', 'Question Tags', NULL, '[{"weight": 1, "conceptId": "fmyji5"}]'::jsonb, '{}', 2, 'application', 60, 'low', 'none', '[{"option": "A", "explanation": "''Isn''t it'' doesn''t match the modal verb ''can'' used in the main clause.", "misconceptionId": "overgeneralized_rule"}, {"option": "C", "explanation": "''Won''t you'' uses a different modal (''will'') than the one in the main clause.", "misconceptionId": "confused_similar_concepts"}, {"option": "D", "explanation": "''Shan''t you'' also uses a mismatched modal (''shall'') rather than echoing ''can''.", "misconceptionId": "confused_similar_concepts"}]'::jsonb, '{}', 'jamb_past_question', 2005, 'JAMB', '{}', 'Choose the option that best completes the gap(S).

You can travel on your own ....?', '[{"label": "A", "text": "isn''t it", "isCorrect": false}, {"label": "B", "text": "can''t you", "isCorrect": true}, {"label": "C", "text": "won''t you", "isCorrect": false}, {"label": "D", "text": "shan''t you", "isCorrect": false}]'::jsonb, 'B', 'The main clause uses the modal ''can'' affirmatively, so the tag must be negative and repeat the same modal: ''can''t you''.', 'live', '{"totalAttempts": 0, "correctCount": 0, "avgResponseTimeMs": 0, "distractorSelectionCounts": {}}'::jsonb);