INSERT INTO kairo.concepts (id, name, subject, topic, subtopic, difficulty_weight, dependency_ids, question_pool_ids) VALUES
('r9oudo', 'Profit and Loss', 'Mathematics', 'Percentages', 'Profit and Loss', 1.0, '{}', '{}'),
('cuzren', 'Identity and Inverse Elements', 'Mathematics', 'Binary operations', 'Identity and Inverse Elements', 1.0, '{}', '{}'),
('un5z3j', 'Sum and Product of Roots', 'Mathematics', 'Quadratic equations', 'Sum and Product of Roots', 1.0, '{}', '{}'),
('qip98q', 'Perpendicular Lines', 'Mathematics', 'Coordinate geometry', 'Perpendicular Lines', 1.0, '{}', '{}'),
('1zxoi6', 'Locus of Points Equidistant from Two Fixed Points', 'Mathematics', 'Loci', 'Locus of Points Equidistant from Two Fixed Points', 1.0, '{}', '{}'),
('5fdhjk', 'Volume of Revolution', 'Mathematics', 'Applications of integration', 'Volume of Revolution', 1.0, '{}', '{}'),
('1eyy37', 'Range and Mode', 'Mathematics', 'Measures of dispersion', 'Range and Mode', 1.0, '{}', '{}'),
('q9ah8r', 'Pie Chart Angles', 'Mathematics', 'Data collection and presentation', 'Pie Chart Angles', 1.0, '{}', '{}'),
('vhs1k3', 'Independent Events', 'Mathematics', 'Probability', 'Independent Events', 1.0, '{}', '{}'),
('aq6l6g', 'Coefficients from Derivative Conditions', 'Mathematics', 'Differentiation', 'Coefficients from Derivative Conditions', 1.0, '{}', '{}'),
('t6mjxk', 'Word Arrangement Permutations', 'Mathematics', 'Permutations and combinations', 'Word Arrangement Permutations', 1.0, '{}', '{}'),
('87au5b', 'Related Rates', 'Mathematics', 'Applications of differentiation', 'Related Rates', 1.0, '{}', '{}'),
('hxtpdp', 'Matrix Transpose', 'Mathematics', 'Matrices and determinants', 'Matrix Transpose', 1.0, '{}', '{}'),
('ff5e8i', 'Rationalizing the Denominator', 'Mathematics', 'Surds', 'Rationalizing the Denominator', 1.0, '{}', '{}'),
('i49kq7', 'Interior and Exterior Angles', 'Mathematics', 'Polygons', 'Interior and Exterior Angles', 1.0, '{}', '{}'),
('1n8mtz', 'Finding a Function from Its Derivative', 'Mathematics', 'Integration', 'Finding a Function from Its Derivative', 1.0, '{}', '{}'),
('x272hp', 'Significant Figures', 'Mathematics', 'Fractions, decimals and approximations', 'Significant Figures', 1.0, '{}', '{}'),
('oevb9o', 'Venn Diagram Word Problems', 'Mathematics', 'Sets', 'Venn Diagram Word Problems', 1.0, '{}', '{}'),
('oaedoe', 'Solving Binary Operation Equations', 'Mathematics', 'Binary operations', 'Solving Binary Operation Equations', 1.0, '{}', '{}'),
('cve6pr', 'Sum to Infinity', 'Mathematics', 'Geometric progression', 'Sum to Infinity', 1.0, '{}', '{}'),
('5n8i4p', 'Definite Integrals with Trigonometric Identities', 'Mathematics', 'Integration', 'Definite Integrals with Trigonometric Identities', 1.0, '{}', '{}'),
('40mgg1', 'Product Rule at a Point', 'Mathematics', 'Differentiation', 'Product Rule at a Point', 1.0, '{}', '{}'),
('w103dg', 'Quadratic Inequalities', 'Mathematics', 'Inequalities', 'Quadratic Inequalities', 1.0, '{}', '{}'),
('dzvgpm', 'Circumradius of an Equilateral Triangle', 'Mathematics', 'Circles', 'Circumradius of an Equilateral Triangle', 1.0, '{}', '{}'),
('m82i1l', 'Compound Interest (Present Value)', 'Mathematics', 'Percentages', 'Compound Interest (Present Value)', 1.0, '{}', '{}'),
('r3pe29', 'Standard Deviation of a Linear Data Set', 'Mathematics', 'Measures of dispersion', 'Standard Deviation of a Linear Data Set', 1.0, '{}', '{}'),
('gd8afp', 'Maximizing a Profit Function', 'Mathematics', 'Applications of differentiation', 'Maximizing a Profit Function', 1.0, '{}', '{}'),
('k054nz', 'Circle Theorems (Chord Perpendicular to a Diameter)', 'Mathematics', 'Circles', 'Circle Theorems (Chord Perpendicular to a Diameter)', 1.0, '{}', '{}'),
('dkyayq', 'Mean Deviation', 'Mathematics', 'Measures of dispersion', 'Mean Deviation', 1.0, '{}', '{}'),
('3s195j', 'Finding Coefficients from Known Factors', 'Mathematics', 'Polynomials', 'Finding Coefficients from Known Factors', 1.0, '{}', '{}'),
('msnd8d', 'Intersection of a Circle and a Line', 'Mathematics', 'Coordinate geometry', 'Intersection of a Circle and a Line', 1.0, '{}', '{}'),
('udd467', 'Bearings (Resultant Displacement)', 'Mathematics', 'Trigonometric functions', 'Bearings (Resultant Displacement)', 1.0, '{}', '{}'),
('kd6fle', 'Common Difference from Two Terms', 'Mathematics', 'Arithmetic progression', 'Common Difference from Two Terms', 1.0, '{}', '{}'),
('epzhpc', 'Locus of a Point Moving Parallel to a Line', 'Mathematics', 'Loci', 'Locus of a Point Moving Parallel to a Line', 1.0, '{}', '{}'),
('f07uqn', 'Determinant of a 3x3 Matrix', 'Mathematics', 'Matrices and determinants', 'Determinant of a 3x3 Matrix', 1.0, '{}', '{}'),
('upqzit', 'Set Difference and Intersection', 'Mathematics', 'Sets', 'Set Difference and Intersection', 1.0, '{}', '{}'),
('3uea3g', 'Combinations with a Minimum-of-Each-Group Constraint', 'Mathematics', 'Permutations and combinations', 'Combinations with a Minimum-of-Each-Group Constraint', 1.0, '{}', '{}'),
('e8n6qi', 'Base Conversion and Solving for an Unknown Base', 'Mathematics', 'Number bases', 'Base Conversion and Solving for an Unknown Base', 1.0, '{}', '{}'),
('wepxsk', 'Solving for an Unknown Digit in a Base Subtraction', 'Mathematics', 'Number bases', 'Solving for an Unknown Digit in a Base Subtraction', 1.0, '{}', '{}');